use crate::auto_generated::extern_impl::*;
// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Mutex;
use std::fs;
use serde::{Serialize, Deserialize};
use serde_json::{to_string_pretty, from_slice};
use serde_json::Value;
/// auth.at — ported from backend/crates/musk/src/auth.rs.
/// 
/// Minimal RBAC + session auth for auto-musk (MVP). Strategy (plan 014):
/// - data model + role/permission logic -> Auto
/// - password hashing (sha2/hex) + random token (rand) -> #[rs] escape hatch
/// (these use external-crate APIs a2r maps poorly; #[rs] passes Rust through)
/// - AuthStore sessions use std::sync::Mutex -> #[rs] for the mutex-guarded
/// HashMap ops; load/save users reuse the specs.rs IO pattern.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Permission {
    RunAgent = 1,
    EditSpecs = 2,
    Read = 3,
    ManageUsers = 4,
}

impl std::fmt::Display for Permission {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Permission::RunAgent => write!(f, "RunAgent"),
            Permission::EditSpecs => write!(f, "EditSpecs"),
            Permission::Read => write!(f, "Read"),
            Permission::ManageUsers => write!(f, "ManageUsers"),
        }
    }
}
impl Permission {
    pub fn from_id(id: &str) -> Self {
        match id {
            "RunAgent" | "runagent" => Permission::RunAgent,
            "EditSpecs" | "editspecs" => Permission::EditSpecs,
            "Read" | "read" => Permission::Read,
            "ManageUsers" | "manageusers" => Permission::ManageUsers,
            _ => Permission::RunAgent
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Role {
    Admin = 1,
    Developer = 2,
    Viewer = 3,
}

impl std::fmt::Display for Role {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Role::Admin => write!(f, "Admin"),
            Role::Developer => write!(f, "Developer"),
            Role::Viewer => write!(f, "Viewer"),
        }
    }
}
impl Role {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Admin" | "admin" => Role::Admin,
            "Developer" | "developer" => Role::Developer,
            "Viewer" | "viewer" => Role::Viewer,
            _ => Role::Admin
        }
    }
}

impl Role {
    pub fn permissions(&self) -> Vec<Permission> {
        match self {
            Role::Admin => return vec![Permission::RunAgent, Permission::EditSpecs, Permission::Read, Permission::ManageUsers],
            Role::Developer => return vec![Permission::RunAgent, Permission::EditSpecs, Permission::Read],
            Role::Viewer => return vec![Permission::Read],
        };
    }
    pub fn allows(&self, perm: Permission) -> bool {
        let perms: Vec<Permission> = self.permissions();
        for p in perms {
            if p == perm {
                return true;
            }
        }
        return false;
    }
}

/// The permission set for this role. (原版返回 &'static [Permission];
/// Auto 无静态切片，返回 List<Permission>。)
/// Does this role grant `perm`?
/// A persisted user (password hashed + salted).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct User {
    pub username: String,
    pub role: Role,
    pub password_hash: String,
    pub salt: String,
}

/// Public user shape (no secret material).
#[derive(Clone, Debug, Serialize)]
pub struct UserInfo {
    pub username: String,
    pub role: Role,
}

impl UserInfo {
    pub fn from_user(u: User) -> UserInfo {
        return UserInfo { username: u.username.clone().to_string(), role: u.role };
    }
}

/// From a User (strips secret material). (原版 impl From<&User>;
/// Auto 无 trait impl，用 static fn 替代。)
/// A live session (bearer token -> username).
#[derive(Clone, Debug)]
pub struct Session {
    pub token: String,
    pub username: String,
}

/// The auth store: persisted users (JSON file) + in-memory sessions.
/// NOTE: sessions (Mutex<HashMap>) and login/session_user/logout (which need
/// the Mutex guard) stay hand-written in Rust — a2r/#[rs] can't express
/// `mutex.lock().unwrap().insert(&k, v)`. Only the user-file IO + seeding
/// logic is ported here.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct AuthStore {
    pub users_path: PathBuf,
}

impl AuthStore {
    pub fn new(users_path: PathBuf) -> AuthStore {
        let store: AuthStore = AuthStore { users_path: users_path };
        store.ensure_default_admin();
        return store;
    }
    pub fn ensure_default_admin(&self) {
        let users: Vec<User> = self.load_users();
        if (users.len() as i32) > 0 {
            return;
        }

        let salt: String = random_hex(16);
        let hash: String = hash_password("admin", &salt);
        let admin: User = User { username: "admin".to_string(), role: Role::Admin, password_hash: hash.to_string(), salt: salt.to_string() };
        let _ = self.save_users(vec![admin]);
    }
    pub fn load_users(&self) -> Vec<User> {
        let read_result = fs::read(self.users_path.clone());
        match read_result {
            Ok(bytes) => {
                let parse_result = from_slice(&bytes);
                match parse_result {
                    Ok(users) => return users,
                    Err(e) => return vec![],
                };
            },
            Err(e) => return vec![],
        };
    }
    pub fn save_users(&self, users: Vec<User>) -> bool {
        let parent = self.users_path.parent();
        match parent {
            Some(p) => {
                let mkdir_result = fs::create_dir_all(p.clone());
                match mkdir_result {
                    Ok(ok) => {},
                    Err(e) => {},
                };
            },
            None => {},
        };
        let json_result = to_string_pretty(&users);
        match json_result {
            Ok(json) => {
                let ok: bool = std::fs::write(self.users_path.to_str().unwrap(), json.as_str()).is_ok();
                return ok;
            },
            Err(e) => return false,
        };
    }
}
