use crate::auto_generated::extern_impl::*;
// Auto-generated by a2r transpiler

use std::sync::Arc;
use crate::tools::{ReadFile, WriteFile, EditFile, BatchReplace, Search, ListDir, ListSymbols, Glob, RunCommand};
use crate::spec_tools::{ReadSpecs, ListSpecs, WriteSpec, UpdateSpec, WriteGoals};
use crate::orch_tools::{SpawnRelay, Dispatch, BringIn};
use crate::tool_context::ToolContext;
trait Role {
    fn name(&self) -> String;
    fn system_prompt(&self) -> String;
    fn model(&self) -> String;
    fn model_tier(&self) -> ModelTier;
    fn temperature(&self) -> f64;
    fn max_turns(&self) -> u32;
    fn allowed_tools(&self) -> Vec<String>;
    fn memory_limit(&self) -> Option<u32>;
    fn allowed_tiers(&self) -> Vec<ModelTier>;
    fn token_budget(&self) -> Option<u64>;
    fn skills(&self) -> Vec<String>;
}


#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct OwnedRole {
    pub inner: Arc<dyn Role>,
    pub extra_prompt: Option<String>,
    pub prompt: String,
}

impl OwnedRole {
    pub fn new(inner: Arc<dyn Role>) -> OwnedRole {
        let p = role_system_prompt(inner);
        return OwnedRole { inner: inner, extra_prompt: None, prompt: p.to_string() };
    }
    pub fn with_extra_prompt(&self, extra: &str) -> OwnedRole {
        let mut p = self.prompt.clone();
        if (extra.trim().to_string().len() as i32) > 0 {
            p = role_system_prompt(self.inner.clone());
            p = format!("{}{}", format!("{}{}", p, "\n\n"), extra)
        }
        let mut result = self.clone();
        result.prompt = p;
        return result;
    }
}

impl Role for OwnedRole {
    fn name(&self) -> String {
        return role_name(self.inner.clone());
    }
    fn system_prompt(&self) -> String {
        return self.prompt.clone();
    }
    fn model(&self) -> String {
        return role_model(self.inner.clone());
    }
    fn model_tier(&self) -> ModelTier {
        return role_model_tier(self.inner.clone());
    }
    fn temperature(&self) -> f64 {
        return role_temperature(self.inner.clone());
    }
    fn max_turns(&self) -> u32 {
        return role_max_turns(self.inner.clone());
    }
    fn allowed_tools(&self) -> Vec<String> {
        return role_allowed_tools(self.inner.clone());
    }
    fn memory_limit(&self) -> Option<u32> {
        return role_memory_limit(self.inner.clone());
    }
    fn allowed_tiers(&self) -> Vec<ModelTier> {
        return role_allowed_tiers(self.inner.clone());
    }
    fn token_budget(&self) -> Option<u64> {
        return role_token_budget(self.inner.clone());
    }
    fn skills(&self) -> Vec<String> {
        return role_skills(self.inner.clone());
    }
}

pub fn build_agent_from_mode(mode: AgentMode, client: Arc<dyn Client>) -> Result<Agent, String> {
    let role = resolve_role(mode.role).unwrap();
    let owned = OwnedRole::new(role);
    let owned2 = owned.with_extra_prompt(mode.extra_system_prompt);
    let agent = Agent::new(owned2, client);
    let all_tools: Vec<(String, Arc<dyn Tool>)> = vec![("read_file".to_string(), Arc::new(ReadFile {})), ("write_file".to_string(), Arc::new(WriteFile {})), ("edit_file".to_string(), Arc::new(EditFile {})), ("batch_replace".to_string(), Arc::new(BatchReplace {})), ("search".to_string(), Arc::new(Search {})), ("list_dir".to_string(), Arc::new(ListDir {})), ("list_symbols".to_string(), Arc::new(ListSymbols {})), ("glob".to_string(), Arc::new(Glob {})), ("run_command".to_string(), Arc::new(RunCommand {})), ("read_specs".to_string(), Arc::new(ReadSpecs {})), ("list_specs".to_string(), Arc::new(ListSpecs {})), ("write_spec".to_string(), Arc::new(WriteSpec {})), ("update_spec".to_string(), Arc::new(UpdateSpec {})), ("write_goals".to_string(), Arc::new(WriteGoals {}))];
    for pair in all_tools {
        let tool_name = pair.0.clone();
        let tool = pair.1.clone();
        if (mode.tools.len() as i32) == 0 {
            agent_register_shared(agent, tool)
        } else {
            if mode_tools_contains(mode, tool_name) {
                agent_register_shared(agent, tool);
            }        }

    }
    if mode.skills {
        agent_register_skill_tool(agent);
    }
    if (mode.context_file.len() as i32) > 0 {
        agent_with_context_file(agent, mode.context_file)
    } else {
        let ctx = find_context_file();
        if ctx_is_some(ctx) {
            agent_with_context_file(agent, ctx_unwrap(ctx));
        }    }

    return Ok(agent);
}

pub fn build_agent_with_context(mode: AgentMode, client: Arc<dyn Client>, ctx: Option<ToolContext>) -> Result<Agent, String> {
    let agent = build_agent_from_mode(mode.clone(), client.clone()).unwrap();
    match ctx {
        Some(c) => {
            let orch: Vec<(String, Arc<dyn Tool>)> = vec![("spawn_relay".to_string(), Arc::new(SpawnRelay::new(c))), ("dispatch".to_string(), Arc::new(Dispatch::new(c))), ("bring_in".to_string(), Arc::new(BringIn::new(c)))];
            for pair in orch {
                let tool_name = pair.0.clone();
                let tool = pair.1.clone();
                if (mode.tools.len() as i32) == 0 {
                    agent_register_shared(agent, tool)
                } else {
                    if mode_tools_contains(mode, tool_name) {
                        agent_register_shared(agent, tool);
                    }                }

            }
        },
        None => {},
    };
    return Ok(agent);
}

fn resolve_role(spec_input: &str) -> Result<Arc<dyn Role>, String> {
    let registry = RoleRegistry::load();
    let r = registry_resolve(registry, spec_input);
    match r {
        Some(role) => return Ok(role),
        None => {},
    };
    let builtin = load_builtin(spec_input);
    match builtin {
        Some(role) => return Ok(role),
        None => {},
    };
    let content = read_at_file(spec_input);
    return load_role(content);
}

fn find_context_file() -> Option<String> {
    let cwd = current_dir();
    return find_ctx_upward(cwd);
}
