use super::extern_impl::*;
// Auto-generated by a2r transpiler

use std::sync::Arc;
use auto_ai_agent::{Agent, Client, Tool, SkillRegistry, SkillTool, ModelTier, RoleRegistry, load_builtin, load_role};
use crate::tools::{ReadFile, WriteFile, EditFile, BatchReplace, Search, ListDir, ListSymbols, Glob, RunCommand};
use crate::spec_tools::{ReadSpecs, ListSpecs, WriteSpec, UpdateSpec, WriteGoals};
use crate::orch_tools::{SpawnRelay, Dispatch, BringIn};
use crate::tool_context::ToolContext;
#[derive(Clone)]
struct OwnedRole {
    pub inner: Arc<dyn Role>,
    pub extra_prompt: Option<String>,
    pub prompt: String,
}

impl OwnedRole {
    pub fn new(inner: Arc<dyn Role>) -> OwnedRole {
        let p = role_system_prompt(&inner);
        return OwnedRole { inner: inner, extra_prompt: None, prompt: p.to_string() };
    }
    pub fn with_extra_prompt(&self, extra: &str) -> OwnedRole {
        let mut p = self.prompt.clone();
        if (extra.trim().to_string().len() as i32) > 0 {
            p = role_system_prompt(&self.inner.clone());
            p = format!("{}{}", format!("{}{}", p, "\n\n"), extra)
        }
        return OwnedRole { inner: self.inner.clone(), extra_prompt: self.extra_prompt.clone(), prompt: p.to_string() };
    }
}

pub fn build_agent_from_mode(mode: AgentMode, client: Arc<dyn Client>) -> Result<Agent, String> {
    let role = resolve_role(&mode.role).unwrap();
    let owned = OwnedRole::new(role);
    let owned2 = owned.with_extra_prompt(&mode.extra_system_prompt);
    let mut agent = Agent::new(owned2, client);
    let all_tools: Vec<(String, Arc<dyn Tool>)> = vec![("read_file".to_string(), Arc::new(ReadFile::new())), ("write_file".to_string(), Arc::new(WriteFile::new())), ("edit_file".to_string(), Arc::new(EditFile::new())), ("batch_replace".to_string(), Arc::new(BatchReplace::new())), ("search".to_string(), Arc::new(Search::new())), ("list_dir".to_string(), Arc::new(ListDir::new())), ("list_symbols".to_string(), Arc::new(ListSymbols::new())), ("glob".to_string(), Arc::new(Glob::new())), ("run_command".to_string(), Arc::new(RunCommand::new())), ("read_specs".to_string(), Arc::new(ReadSpecs::new())), ("list_specs".to_string(), Arc::new(ListSpecs::new())), ("write_spec".to_string(), Arc::new(WriteSpec::new())), ("update_spec".to_string(), Arc::new(UpdateSpec::new())), ("write_goals".to_string(), Arc::new(WriteGoals::new()))];
    for pair in &all_tools {
        let tool_name = pair.0.clone();
        let tool = pair.1.clone();
        if (mode.tools.len() as i32) == 0 {
            agent_register_shared(&mut agent, tool)
        } else {
            if mode_tools_contains(&mode, &tool_name) {
                agent_register_shared(&mut agent, tool);
            }        }

    }
    if mode.skills {
        agent_register_skill_tool(&mut agent);
    }
    if (mode.context_file.len() as i32) > 0 {
        agent = agent_with_context_file(agent, &mode.context_file)
    } else {
        let ctx = find_context_file();
        if ctx_is_some(&ctx) {
            agent = agent_with_context_file(agent, &ctx_unwrap(ctx))
        }    }

    return Ok(agent);
}

pub fn build_agent_with_context(mode: AgentMode, client: Arc<dyn Client>, ctx: Option<ToolContext>) -> Result<Agent, String> {
    let mut agent = build_agent_from_mode(mode.clone(), client.clone()).unwrap();
    match ctx {
        Some(c) => {
            let orch: Vec<(String, Arc<dyn Tool>)> = vec![("spawn_relay".to_string(), Arc::new(SpawnRelay::new(c.clone()))), ("dispatch".to_string(), Arc::new(Dispatch::new(c.clone()))), ("bring_in".to_string(), Arc::new(BringIn::new(c)))];
            for pair in &orch {
                let tool_name = pair.0.clone();
                let tool = pair.1.clone();
                if (mode.tools.len() as i32) == 0 {
                    agent_register_shared(&mut agent, tool)
                } else {
                    if mode_tools_contains(&mode, &tool_name) {
                        agent_register_shared(&mut agent, tool);
                    }                }

            }
        },
        None => {},
    };
    return Ok(agent);
}

fn resolve_role(spec_input: &str) -> Result<Arc<dyn Role>, String> {
    let registry = RoleRegistry::load();
    let r = registry_resolve(registry, spec_input);
    match r {
        Some(role) => return Ok(role),
        None => {},
    };
    let builtin = load_builtin(spec_input);
    match builtin {
        Some(role) => return Ok(role),
        None => {},
    };
    let content = read_at_file(spec_input);
    let r = load_role(&content);
    match r {
        Ok(role) => return Ok(role),
        Err(e) => return Err(e.to_string()),
    }
}

fn find_context_file() -> Option<String> {
    let cwd = current_dir();
    return find_ctx_upward(&cwd);
}impl auto_ai_agent::Role for OwnedRole {
    fn name(&self) -> &str { self.inner.name() }
    fn system_prompt(&self) -> &str { self.inner.system_prompt() }
    fn model_tier(&self) -> ModelTier { self.inner.model_tier() }
    fn model(&self) -> &str { self.inner.model() }
    fn temperature(&self) -> f64 { self.inner.temperature() }
    fn max_turns(&self) -> usize { self.inner.max_turns() }
    fn allowed_tools(&self) -> Vec<String> { self.inner.allowed_tools() }
    fn memory_limit(&self) -> Option<usize> { self.inner.memory_limit() }
    fn allowed_tiers(&self) -> Vec<ModelTier> { self.inner.allowed_tiers() }
    fn token_budget(&self) -> Option<u64> { self.inner.token_budget() }
    fn skills(&self) -> Vec<String> { self.inner.skills() }
}
