use super::extern_impl::*;
// Auto-generated by a2r transpiler
//
// NOTE: main.at defines a full `main()` entry + Client trait, but the real
// binary entry is the hand-written `main.rs`. a2r also mis-transpiles
// `#[derive(Parser)]` on `type Cli` (adds a spurious `Subcommand` derive +
// duplicate `use clap::Parser`), so this file is hand-trimmed to the minimal
// compilable surface (just the `Cli` struct). See plan 015 §3 (a2r issue #1/#2).

use clap::Parser;

#[derive(Parser)]
#[command(name = "musk", version)]
pub struct Cli {
    pub cmd: String,
}
