use super::extern_impl::*;
// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use serde::{Serialize, Deserialize};
use std::collections::HashMap;
use std::path::PathBuf;
use std::fs;
use std::time::{SystemTime, Duration};
use serde_json::{to_string_pretty, from_slice};
use serde_json::Value;
use crate::auto_generated::specs::{SpecChange, SpecItem, SpecsDocument, SpecsSection, SpecsStore};

/// chats.at — ported from backend/crates/musk/src/chats.rs.
/// 
/// Persistent multi-turn chat sessions. Strategy (plan 014 mixed):
/// - data model (Role/ToolCall/ChatMessage/ChatSession/ChatSessionSummary)
/// + summary/append pure logic -> Auto
/// - new_id (rand) -> hand-written Rust (rand crate API, like auth.rs)
/// - ChatStore IO (load/save) -> Auto (specs.rs pattern: .view + serde_json)
/// 
/// Cross-module types: 自 C1(approve_spec_change 移植)起,SpecChange/SpecStatus/
/// SpecItem/SpecsDocument/SpecsSection/SpecsStore 直接引用真实
/// crate::auto_generated::specs(不再 self-contained mirror —— mirror 只有
/// Empty/Draft 两个 SpecStatus,无法支撑 approve 的完整状态机)。ChatSession 与
/// hw 一样携带 Vec<crate::specs::SpecChange>。
fn now_sec() -> u64 {
    let now = SystemTime::now();
    let elapsed = now.elapsed().unwrap();
    return elapsed.as_secs();
}

/// Who produced a message.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    User = 1,
    Assistant = 2,
    Tool = 3,
}

impl std::fmt::Display for Role {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Role::User => write!(f, "User"),
            Role::Assistant => write!(f, "Assistant"),
            Role::Tool => write!(f, "Tool"),
        }
    }
}
impl Role {
    pub fn from_id(id: &str) -> Self {
        match id {
            "User" | "user" => Role::User,
            "Assistant" | "assistant" => Role::Assistant,
            "Tool" | "tool" => Role::Tool,
            _ => Role::User
        }
    }
}

/// A tool call recorded on an assistant message.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ToolCall {
    #[serde(rename = "name", alias = "tool")]
    pub tool: String,
    #[serde(rename = "arguments", alias = "args")]
    pub args: Value,
    pub result: String,
    #[serde(default = "default_status", skip_serializing_if = "is_default_status")]
    pub status: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub id: String,
}

/// Default tool-call status (used by serde `default = "default_status"`).
fn default_status() -> String {
    return "success".to_string();
}

/// Whether a tool-call status is the default (used by serde skip_serializing_if).
fn is_default_status(s: &str) -> bool {
    return s == "success";
}

/// A single chat message.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ChatMessage {
    pub id: String,
    pub role: Role,
    pub content: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tool_calls: Vec<ToolCall>,
    pub created_at: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
}

impl ChatMessage {
    pub fn user(content: &str) -> ChatMessage {
        return ChatMessage { id: new_id(8).to_string(), role: Role::User, content: content.clone().to_string(), tool_calls: vec![], created_at: now_sec(), parent_id: None };
    }
    pub fn assistant(content: &str) -> ChatMessage {
        return ChatMessage { id: new_id(8).to_string(), role: Role::Assistant, content: content.clone().to_string(), tool_calls: vec![], created_at: now_sec(), parent_id: None };
    }
}

/// Factory: a user message. new_id() is hand-written Rust (rand).
/// Factory: an assistant message.
/// A persisted multi-turn chat session.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ChatSession {
    pub id: String,
    pub name: String,
    pub mode: String,
    pub messages: Vec<ChatMessage>,
    pub created_at: u64,
    pub updated_at: u64,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub pending_spec_changes: Vec<SpecChange>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workspace_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active_leaf: Option<String>,
}

impl ChatSession {
    pub fn new(mode: &str, workspace_id: Option<String>) -> ChatSession {
        let now: u64 = now_sec();
        return ChatSession { id: new_id(12).to_string(), name: "New chat".to_string(), mode: mode.clone().to_string(), messages: vec![], created_at: now, updated_at: now, pending_spec_changes: vec![], workspace_id: workspace_id, active_leaf: None };
    }
    pub fn summary(&self) -> ChatSessionSummary {

        let mut preview: String = "".to_string();
        let mut i: i32 = ((self.messages.len() as i32) as i32) - 1;
        let mut done: bool = false;
        while done == false {
            if i < 0 {
                done = true;
            } else {
                let mut m = self.messages[(i) as usize].clone();
                if m.role == Role::User {
                    preview = m.content.clone();
                    done = true;
                } else {
                    i = i - 1;
                }
            }

        }



        if (preview.len() as i32) > 80 {
            preview = format!("{}{}", &preview[0 as usize..80 as usize], "…");
        }
        let result: ChatSessionSummary = ChatSessionSummary { id: self.id.clone().to_string(), name: self.name.clone().to_string(), mode: self.mode.clone().to_string(), message_count: ((self.messages.len() as i32) as u32), preview: preview.to_string(), updated_at: self.updated_at.clone() };
        return result;
    }
    pub fn append(&mut self, msg: ChatMessage) {
        let mut new_messages: Vec<ChatMessage> = self.messages.clone();
        new_messages.push(msg.clone());
        let mut new_name: String = self.name.clone();
        if self.name == "New chat" {
            

            let mut found: bool = false;
            for m in new_messages.clone() {
                if found == false {
                    if m.role == Role::User {
                        let mut nm: String = m.content.clone();
                        if (nm.len() as i32) > 40 {
                            nm = format!("{}{}", &nm[0 as usize..40 as usize], "");
                        }                        new_name = format!("{}{}", nm.trim().to_string(), "");
                        found = true;
                    }                }
            }
        }
        self.messages = new_messages;
        self.updated_at = now_sec();
        self.name = new_name;
    }
}

/// A lightweight summary for list views (no message bodies).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ChatSessionSummary {
    pub id: String,
    pub name: String,
    pub mode: String,
    pub message_count: u32,
    pub preview: String,
    pub updated_at: u64,
}

/// Factory: a new empty session. new_id() is hand-written Rust (rand).
/// Build a list-view summary. Preview = last user message, truncated.
/// iterator chain (iter/rev/find/map/chars/take/collect) rewritten as a
/// reverse for-loop + a simple substring truncation.
/// Append a message + bump updated_at. Auto-names from first user msg.
/// a2r-11: build new messages list + whole-field reassign.
/// 命名 `push_message`(非 hw 的 `append`):a2r 的方法分发对 struct receiver
/// 的 .append 仍误重映射为 .push_str(Plan 392 E1 待续,a2r 方法分发路径深)。
/// 行为与 hw append 完全一致。
/// Apply one SpecChange to a specs doc via the ag specs store (mirror of hw
/// apply_spec_change), 返回更新后的 doc 供调用方保存。跨模块调用标记:
/// - `.mut` → `&mut d`(a2r 的 fn_mut_params 只注册当前转译单元,对
/// crate::auto_generated::specs 的方法不注入 &mut;且 `mut p T` 参数发射
/// `p: &mut T` 缺 `mut` 绑定,`&mut p` 重借会 E0596 —— 所以按值收 doc +
/// `var d` 本地可变绑定,文档化 a2r 缺口)
/// - `.view` → `&field`(&str 参数;未知 callee 不自动 borrow owned String)
fn apply_spec_change_to_doc(doc: SpecsDocument, store: SpecsStore, change: SpecChange) -> Result<SpecsDocument, String> {
    let mut d: SpecsDocument = doc.clone();
    match change.status {
        Some(st) => {
            let r: Result<bool, String> = store.transition_item(&mut d, &change.section_id, &change.item_id, st);
            match r {
                Ok(ok) => return Ok(d),
                Err(e) => return Err(e),
            };
        },
        None => {
            

            let mut existing: Option<SpecItem> = None;
            for s in &d.sections {
                if s.id == change.section_id {
                    for it in &s.items {
                        if it.id == change.item_id {
                            existing = Some(it.clone());
                        }
                    }
                }
            }
            let mut item: SpecItem = SpecItem::new(&change.item_id.as_str(), "");
            match existing {
                Some(e) => item = e,
                None => {},
            };
            match change.title {
                Some(t) => item.title = t.clone(),
                None => {},
            };
            match change.content {
                Some(c) => item.content = c.clone(),
                None => {},
            };
            if (item.title.len() as i32) == 0 {
                if (item.content.len() as i32) == 0 {
                    item.title = "(empty)".to_string();
                }            }
            let r: Result<bool, String> = store.upsert_item(&mut d, &change.section_id, item);
            match r {
                Ok(ok) => return Ok(d),
                Err(e) => return Err(e),
            };
        },
    }
}

/// JSON-file-backed store of chat sessions, keyed by session id.
#[derive(Clone, Debug)]
pub struct ChatStore {
    pub path: PathBuf,
}

impl ChatStore {
    pub fn at(path: PathBuf) -> ChatStore {
        return ChatStore { path: path };
    }
    pub fn load_map(&self) -> HashMap<String, ChatSession> {
        let read_result = fs::read(self.path.clone());
        match read_result {
            Ok(bytes) => {
                let parse_result = from_slice(&bytes);
                match parse_result {
                    Ok(map) => return map,
                    Err(e) => return HashMap::new(),
                };
            },
            Err(e) => return HashMap::new(),
        }
    }
    pub fn save_map(&self, map: HashMap<String, ChatSession>) -> bool {
        let parent = self.path.parent();
        match parent {
            Some(p) => {
                let mkdir_result = fs::create_dir_all(p.clone());
                match mkdir_result {
                    Ok(ok) => {},
                    Err(e) => {},
                };
            },
            None => {},
        };
        let json_result = to_string_pretty(&map);
        match json_result {
            Ok(json) => {
                let ok: bool = std::fs::write(self.path.to_str().unwrap(), json.as_str()).is_ok();
                return ok;
            },
            Err(e) => return false,
        }
    }
    pub fn create(&self, mode: &str, workspace_id: Option<String>) -> Result<ChatSession, String> {
        let session: ChatSession = ChatSession::new(mode, workspace_id);
        let mut map: HashMap<String, ChatSession> = self.load_map();
        map.insert(session.id.clone(), session.clone());
        if self.save_map(map) == false {
            return Err("write failed".into());
        }
        return Ok(session);
    }
    pub fn list(&self) -> Vec<ChatSessionSummary> {
        let mut map: HashMap<String, ChatSession> = self.load_map();
        let mut summaries: Vec<ChatSessionSummary> = vec![];
        for s in map.values() {
            summaries.push(s.summary());
        }
        summaries.sort_by(|a, b| b.updated_at.cmp(&a.updated_at));
        return summaries;
    }
    pub fn get(&self, id: &str) -> Option<ChatSession> {
        let mut map: HashMap<String, ChatSession> = self.load_map();
        let mut found: Option<ChatSession> = None;
        for s in map.values() {
            if s.id == id {
                found = Some(s.clone());
            }
        }
        return found;
    }
    pub fn rename(&self, id: &str, mut name: &str) -> Result<Option<ChatSession>, String> {
        let mut map: HashMap<String, ChatSession> = self.load_map();
        let mut target: Option<ChatSession> = None;
        let mut found: bool = false;
        let mut updated_map: HashMap<String, ChatSession> = HashMap::new();
        for s in map.values() {
            if s.id == id {
                found = true;
                let mut renamed: ChatSession = s.clone();
                renamed.name = name.to_string();
                renamed.updated_at = now_sec();
                updated_map.insert(renamed.id.clone(), renamed.clone());
                target = Some(renamed);
            } else {
                updated_map.insert(s.id.clone(), s.clone());
            }

        }
        if found == false {
            return Ok(None);
        }
        if self.save_map(updated_map) == false {
            return Err("write failed".into());
        }
        return Ok(target);
    }
    pub fn delete(&self, id: &str) -> Result<bool, String> {
        let mut map: HashMap<String, ChatSession> = self.load_map();
        let mut existed: bool = false;
        let mut updated_map: HashMap<String, ChatSession> = HashMap::new();
        for s in map.values() {
            if s.id == id {
                existed = true;
            } else {
                updated_map.insert(s.id.clone(), s.clone());
            }

        }
        if existed == false {
            return Ok(false);
        }
        if self.save_map(updated_map) == false {
            return Err("write failed".into());
        }
        return Ok(true);
    }
    pub fn delete_all(&self) -> Result<bool, String> {
        let mut empty: HashMap<String, ChatSession> = HashMap::new();
        if self.save_map(empty) == false {
            return Err("write failed".into());
        }
        return Ok(true);
    }
    pub fn append_message(&self, id: &str, msg: ChatMessage) -> Result<Option<ChatSession>, String> {
        let mut map: HashMap<String, ChatSession> = self.load_map();
        let mut target: Option<ChatSession> = None;
        let mut found: bool = false;
        let mut updated_map: HashMap<String, ChatSession> = HashMap::new();
        for s in map.values() {
            if s.id == id {
                found = true;
                let mut updated: ChatSession = s.clone();
                updated.append(msg.clone());
                updated_map.insert(updated.id.clone(), updated.clone());
                target = Some(updated);
            } else {
                updated_map.insert(s.id.clone(), s.clone());
            }

        }
        if found == false {
            return Ok(None);
        }
        if self.save_map(updated_map) == false {
            return Err("write failed".into());
        }
        return Ok(target);
    }
    pub fn queue_spec_change(&self, id: &str, change: SpecChange) -> Result<Option<ChatSession>, String> {
        let mut map: HashMap<String, ChatSession> = self.load_map();
        let mut target: Option<ChatSession> = None;
        let mut found: bool = false;
        let mut updated_map: HashMap<String, ChatSession> = HashMap::new();
        for s in map.values() {
            if s.id == id {
                found = true;
                let mut updated: ChatSession = s.clone();
                updated.pending_spec_changes.push(change.clone());
                updated.updated_at = now_sec();
                updated_map.insert(updated.id.clone(), updated.clone());
                target = Some(updated);
            } else {
                updated_map.insert(s.id.clone(), s.clone());
            }

        }
        if found == false {
            return Ok(None);
        }
        if self.save_map(updated_map) == false {
            return Err("write failed".into());
        }
        return Ok(target);
    }
    pub fn reject_spec_change(&self, id: &str, index: u32) -> Result<Option<ChatSession>, String> {
        let mut map: HashMap<String, ChatSession> = self.load_map();
        let mut target: Option<ChatSession> = None;
        let mut found: bool = false;
        let mut updated_map: HashMap<String, ChatSession> = HashMap::new();
        for s in map.values() {
            if s.id == id {
                found = true;
                if index >= ((s.pending_spec_changes.len() as i32) as u32) {
                    return Err("pending change index out of range".into());
                }                

                let mut new_pending: Vec<SpecChange> = vec![];
                let mut i: u32 = 0 as u32;
                for c in s.pending_spec_changes.clone() {
                    if i != index {
                        new_pending.push(c.clone());
                    }
                    i = i + 1;
                }
                let mut updated: ChatSession = s.clone();
                updated.pending_spec_changes = new_pending;
                updated.updated_at = now_sec();
                updated_map.insert(updated.id.clone(), updated.clone());
                target = Some(updated);
            } else {
                updated_map.insert(s.id.clone(), s.clone());
            }

        }
        if found == false {
            return Err(format!("{}{}", format!("{}{}", "session '", id), "' not found"));
        }
        if self.save_map(updated_map) == false {
            return Err("write failed".into());
        }
        return Ok(target);
    }
    pub fn reject_all_spec_changes(&self, id: &str) -> Result<Option<ChatSession>, String> {
        let mut map: HashMap<String, ChatSession> = self.load_map();
        let mut target: Option<ChatSession> = None;
        let mut found: bool = false;
        let mut updated_map: HashMap<String, ChatSession> = HashMap::new();
        for s in map.values() {
            if s.id == id {
                found = true;
                let mut updated: ChatSession = s.clone();
                updated.pending_spec_changes = vec![];
                updated.updated_at = now_sec();
                updated_map.insert(updated.id.clone(), updated.clone());
                target = Some(updated);
            } else {
                updated_map.insert(s.id.clone(), s.clone());
            }

        }
        if found == false {
            return Err(format!("{}{}", format!("{}{}", "session '", id), "' not found"));
        }
        if self.save_map(updated_map) == false {
            return Err("write failed".into());
        }
        return Ok(target);
    }
    pub fn approve_spec_change(&self, id: &str, index: u32, specs: SpecsStore) -> Result<Option<(SpecChange, ChatSession)>, String> {
        let mut map: HashMap<String, ChatSession> = self.load_map();
        let mut target: Option<(SpecChange, ChatSession)> = None;
        let mut found: bool = false;
        let mut updated_map: HashMap<String, ChatSession> = HashMap::new();
        for s in map.values() {
            if s.id == id {
                found = true;
                if index >= ((s.pending_spec_changes.len() as i32) as u32) {
                    return Err("pending change index out of range".into());
                }                

                let mut pending: Vec<SpecChange> = vec![];
                let mut change_at: Option<SpecChange> = None;
                let mut i: u32 = 0 as u32;
                for c in s.pending_spec_changes.clone() {
                    if i == index {
                        change_at = Some(c.clone());
                    } else {
                        pending.push(c.clone());
                    }

                    i = i + 1;
                }
                let mut change: SpecChange = SpecChange { section_id: "".to_string(), item_id: "".to_string(), title: None, content: None, status: None, reason: "".to_string() };
                match change_at {
                    Some(c) => change = c,
                    None => {},
                };
                

                let doc_result: Result<SpecsDocument, String> = specs.load();
                match doc_result {
                    Ok(d) => {
                        let mut doc: SpecsDocument = d;
                        let apply_result: Result<SpecsDocument, String> = apply_spec_change_to_doc(doc.clone(), specs.clone(), change.clone());
                        match apply_result {
                            Ok(updated_doc) => {
                                let save_result: Result<String, String> = specs.save(updated_doc);
                                match save_result {
                                    Ok(so) => {},
                                    Err(se) => return Err(se),
                                };
                            },
                            Err(ae) => return Err(ae),
                        };
                    },
                    Err(e) => return Err(e),
                };
                

                let mut updated: ChatSession = s.clone();
                updated.pending_spec_changes = pending;
                updated.updated_at = now_sec();
                updated_map.insert(updated.id.clone(), updated.clone());
                let pair = (change.clone(), updated.clone());
                target = Some(pair);
            } else {
                updated_map.insert(s.id.clone(), s.clone());
            }

        }
        if found == false {
            return Err(format!("{}{}", format!("{}{}", "session '", id), "' not found"));
        }
        if self.save_map(updated_map) == false {
            return Err("write failed".into());
        }
        return Ok(target);
    }
}