use super::extern_impl::*;
// Auto-generated by a2r transpiler

use serde::{Serialize, Deserialize};
use std::time::{SystemTime, Duration};
use serde_json::Value;
/// conversation.at — ported from backend/crates/musk/src/conversation.rs.
/// 
/// Unified conversation model (chat + flow 共同抽象). Strategy (plan 014 mixed):
/// - 全部数据类型 (L14-157) + ConversationEvent + to_status_str +
/// chat_message_to_turns + now_secs -> Auto
/// - ConversationStore (Mutex<HashMap> + broadcast) + run_event_to_turns
/// (上游 RunEvent + macro_rules!) + 测试 -> 手写 Rust
/// 
/// Cross-module: ChatMessage/Role (from chats.rs) + RunEvent (from relay/store.rs)
/// re-declared here (self-contained; serde-compatible mirrors).
fn now_secs() -> u64 {
    let elapsed = SystemTime::now().duration_since(SystemTime::UNIX_EPOCH).unwrap_or_default();
    return elapsed.as_secs();
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    User = 1,
    Assistant = 2,
    Tool = 3,
}

impl std::fmt::Display for Role {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Role::User => write!(f, "User"),
            Role::Assistant => write!(f, "Assistant"),
            Role::Tool => write!(f, "Tool"),
        }
    }
}
impl Role {
    pub fn from_id(id: &str) -> Self {
        match id {
            "User" | "user" => Role::User,
            "Assistant" | "assistant" => Role::Assistant,
            "Tool" | "tool" => Role::Tool,
            _ => Role::User
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ToolCall {
    pub tool: String,
    pub args: Value,
    pub result: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ChatMessage {
    pub id: String,
    pub role: Role,
    pub content: String,
    pub tool_calls: Vec<ToolCall>,
    pub created_at: u64,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ConversationKind {
    Chat = 1,
    Flow = 2,
    Errand = 3,
}

impl std::fmt::Display for ConversationKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            ConversationKind::Chat => write!(f, "Chat"),
            ConversationKind::Flow => write!(f, "Flow"),
            ConversationKind::Errand => write!(f, "Errand"),
        }
    }
}
impl ConversationKind {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Chat" | "chat" => ConversationKind::Chat,
            "Flow" | "flow" => ConversationKind::Flow,
            "Errand" | "errand" => ConversationKind::Errand,
            _ => ConversationKind::Chat
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Driver {
    Human,
    Agent { agent_id: String },
    Flow { flow_id: String },
}


#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ConversationStatus {
    Active,
    WaitingGate,
    Completed,
    Failed { error: String },
    Paused { reason: String },
}


impl ConversationStatus {
    pub fn to_status_str(&self) -> String {
        match self {
            ConversationStatus::Active => return "active".to_string(),
            ConversationStatus::WaitingGate => return "waiting_gate".to_string(),
            ConversationStatus::Completed => return "completed".to_string(),
            ConversationStatus::Failed { .. } => return "failed".to_string(),
            ConversationStatus::Paused { .. } => return "paused".to_string(),
        }
    }
}

/// Snake-case status string. (a2r-18: named-field variant destructure to
/// *read* a field is broken, but { .. } ignore-arms work — these arms
/// discard error/reason, only need the variant tag.)
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TurnKind {
    Message = 1,
    ToolCall = 2,
    ToolResult = 3,
    Gate = 4,
    System = 5,
}

impl std::fmt::Display for TurnKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            TurnKind::Message => write!(f, "Message"),
            TurnKind::ToolCall => write!(f, "ToolCall"),
            TurnKind::ToolResult => write!(f, "ToolResult"),
            TurnKind::Gate => write!(f, "Gate"),
            TurnKind::System => write!(f, "System"),
        }
    }
}
impl TurnKind {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Message" | "message" => TurnKind::Message,
            "ToolCall" | "toolcall" => TurnKind::ToolCall,
            "ToolResult" | "toolresult" => TurnKind::ToolResult,
            "Gate" | "gate" => TurnKind::Gate,
            "System" | "system" => TurnKind::System,
            _ => TurnKind::Message
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ToolRecord {
    pub name: String,
    pub args: Value,
    #[serde(default)]
    pub result: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<Value>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct GateRecord {
    pub step_id: String,
    pub status: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub feedback: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct GateInfo {
    pub step_id: String,
    pub role_id: String,
    pub since: u64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Turn {
    pub id: String,
    pub seq: u32,
    pub from: String,
    #[serde(rename = "to", default, skip_serializing_if = "Option::is_none")]
    pub to_role: Option<String>,
    pub kind: TurnKind,
    #[serde(default)]
    pub content: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool: Option<ToolRecord>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gate: Option<GateRecord>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub child_conversation: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tokens: Option<u64>,
    pub timestamp: u64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Conversation {
    pub id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_turn_id: Option<String>,
    pub kind: ConversationKind,
    pub workspace_id: String,
    pub driver: Driver,
    pub status: ConversationStatus,
    #[serde(default)]
    pub turns: Vec<Turn>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub initial_prompt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub flow_id: Option<String>,
    #[serde(default)]
    pub current_step: u32,
    #[serde(default)]
    pub cumulative_tokens: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub budget_limit: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pending_gate: Option<GateInfo>,
    pub created_at: u64,
    pub updated_at: u64,
}

/// Lightweight summary for list views.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ConversationSummary {
    pub id: String,
    pub kind: ConversationKind,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    pub workspace_id: String,
    pub status: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    pub turn_count: u32,
    pub cumulative_tokens: u64,
    pub created_at: u64,
    pub updated_at: u64,
}

/// An event broadcast by ConversationStore (the bus payload). Mirrors the
/// hand-written shape exactly: conversation_id + optional Turn + optional
/// status string. (原版 derive 仅 Clone, Debug — 不序列化,事件走 broadcast 总线.)
#[derive(Clone, Debug)]
pub struct ConversationEvent {
    pub conversation_id: String,
    pub turn: Option<Turn>,
    pub status: Option<String>,
}

pub fn chat_message_to_turns(mut msg: ChatMessage, seq_base: u32) -> Vec<Turn> {
    let mut from: String = "system".to_string();
    match msg.role {
        Role::User => from = "human".to_string(),
        Role::Assistant => from = "assistant".to_string(),
        Role::Tool => from = "system".to_string(),
    };
    let mut turns: Vec<Turn> = vec![];



    let mut has_main_turn: bool = (msg.content.len() as i32) > 0 || (msg.tool_calls.len() as i32) == 0;
    if has_main_turn {
        let mut to_field: Option<String> = None;
        if msg.role == Role::User {
            to_field = Some("assistant".to_string())
        }        let main_turn: Turn = Turn { id: msg.id.clone().to_string(), seq: seq_base, from: from.clone().to_string(), to_role: to_field, kind: TurnKind::Message, content: msg.content.clone().to_string(), tool: None, gate: None, child_conversation: None, tokens: None, timestamp: msg.created_at };
        turns.push(main_turn.clone());
    }


    let mut i: u32 = 0;
    for tc in msg.tool_calls.clone() {
        let tc_id: String = format!("{}{}", format!("{}{}", msg.id.clone(), "-tc"), i);
        let tc_turn: Turn = Turn { id: tc_id.to_string(), seq: seq_base + ((turns.len() as i32) as u32), from: from.clone().to_string(), to_role: None, kind: TurnKind::ToolCall, content: "".to_string(), tool: Some(ToolRecord { name: tc.tool.clone().to_string(), args: tc.args.clone(), result: "".to_string(), tool_id: None, details: None }), gate: None, child_conversation: None, tokens: None, timestamp: msg.created_at };
        turns.push(tc_turn.clone());
        let tr_id: String = format!("{}{}", format!("{}{}", msg.id.clone(), "-tr"), i);
        let tr_turn: Turn = Turn { id: tr_id.to_string(), seq: seq_base + ((turns.len() as i32) as u32), from: "system".to_string(), to_role: None, kind: TurnKind::ToolResult, content: "".to_string(), tool: Some(ToolRecord { name: tc.tool.clone().to_string(), args: null_value(), result: tc.result.clone().to_string(), tool_id: None, details: None }), gate: None, child_conversation: None, tokens: None, timestamp: msg.created_at };
        turns.push(tr_turn.clone());
        i = i + 1;
    }

    return turns;
}