use super::extern_impl::*;
// Auto-generated by a2r transpiler

fn parse_json(s: &String) -> Value {
}

fn value_get_str(v: &T, k: &String) -> String {
}

fn value_get_bool(v: &T, k: &String) -> bool {
}

fn value_get_array(v: &T, k: &String) -> Value {
}

fn null_value() -> Value {
}

fn new_id(_: i32) -> String {
}

fn random_hex(n: i32) -> String {
}

fn hash_password(p: &String, s: &String) -> String {
}

fn auth_login_role(_s: &T, _u: &str, _p: &str) -> String {
}

fn auth_login_token(_s: &T, _u: &str, _p: &str) -> String {
}

fn auth_token_from_headers(_s: &T, _h: Value) -> String {
}

fn auth_username_from_token(_s: &T, _t: &String) -> String {
}

fn auth_role_from_token(_s: &T, _t: &String) -> String {
}

fn auth_logout_token(_s: &T, _h: Value) {
}

fn auth_header_token(_h: Value) -> Value {
}

fn specs_load(_s: &T, _q: Value) -> Value {
}

fn specs_overview_of(_s: &T, _q: Value) -> Value {
}

fn specs_drift(_s: &T, _q: Value) -> Value {
}

fn specs_rebuild(_s: &T, _q: Value) -> Value {
}

fn specs_related_of(_s: &T, _q: Value, _p: Value) -> Value {
}

fn specs_upsert_of(_s: &T, _q: Value, _b: Value) -> Value {
}

fn specs_transition_of(_s: &T, _q: Value, _b: Value) -> String {
}

fn specs_delete_of(_s: &T, _q: Value, _p: Value) -> String {
}

fn specs_read(_s: &str) -> String {
}

fn specs_list() -> String {
}

fn specs_write(_s: &str, _c: &str) -> String {
}

fn specs_update(_a: &str, _s: &str, _v: Value) -> String {
}

fn specs_write_goals(_g: &str) -> String {
}

fn professions_list() -> Value {
}

fn config_build() -> Value {
}

fn modes_all() -> Value {
}

fn skills_all() -> Value {
}

fn roles_all() -> Value {
}

fn role_get(_p: &T) -> Value {
}

fn role_save_of(_p: &T, _b: Value) {
}

fn role_delete_of(_p: &T) {
}

fn role_name(_r: Value) -> String {
}

fn role_system_prompt(_r: &T) -> String {
}

fn role_model(_r: Value) -> String {
}

fn role_model_tier(_r: Value) -> Value {
}

fn role_temperature(_r: Value) -> f64 {
}

fn role_max_turns(_r: Value) -> i32 {
}

fn role_allowed_tools(_r: Value) -> Value {
}

fn role_memory_limit(_r: Value) -> Value {
}

fn role_allowed_tiers(_r: Value) -> Value {
}

fn role_token_budget(_r: Value) -> Value {
}

fn role_skills(_r: Value) -> Value {
}

fn app_config_load() -> Value {
}

fn app_config_write(_b: Value) -> Value {
}

fn app_config_effective_daemon_url(_c: Value) -> String {
}

fn harness_list(_p: &T) -> Value {
}

fn harness_save(_p: &T, _b: Value) {
}

fn harness_delete(_p: &T) {
}

fn harness_name_from_path(_p: &T) -> String {
}

fn chats_create(_s: &T, _q: Value, _b: Value) -> Value {
}

fn chats_list(_s: &T, _q: Value) -> Value {
}

fn chats_get(_s: &T, _q: Value, _p: Value) -> Value {
}

fn chats_rename(_s: &T, _q: Value, _p: Value, _b: Value) -> Value {
}

fn chats_delete(_s: &T, _q: Value, _p: Value) {
}

fn chats_delete_all(_s: &T, _q: Value) -> i32 {
}

fn chats_message(_s: &T, _q: Value, _p: Value, _b: Value) {
}

fn chats_approve(_s: &T, _q: Value, _p: Value) -> bool {
}

fn chats_reject(_s: &T, _q: Value, _p: Value) -> Value {
}

fn chats_reject_all(_s: &T, _q: Value, _p: Value) -> Value {
}

fn conversations_list(_s: &T, _q: Value) -> Value {
}

fn conversations_get(_s: &T, _q: Value, _p: Value) -> Value {
}

fn conversations_delete(_s: &T, _q: Value, _p: Value) {
}

fn conversations_rename(_s: &T, _q: Value, _p: Value, _b: Value) -> Value {
}

fn conversations_subscribe(_s: &T, _q: Value) -> i32 {
}

fn conv_event_matches(_ev: &T, _id: &String) -> bool {
}

fn conv_event_id(_ev: &T) -> String {
}

fn conv_event_turn(_ev: &T) -> Value {
}

fn conv_event_status(_ev: &T) -> Value {
}

fn workspace_list_all(_s: &T) -> Value {
}

fn workspace_open_of(_s: &T, _b: Value) -> Value {
}

fn workspace_status_of(_s: &T, _q: Value) -> Value {
}

fn workspace_browse_of(_q: &T) -> Value {
}

fn workspace_initialize_of(_s: &T, _q: Value) {
}

fn workflows_builtin_names() -> Value {
}

fn wf_run(_s: &T, _q: Value, _b: Value) -> Value {
}

fn wf_run_with_progress(_s: &T, _q: Value, _b: Value, _sink: Value) {
}

fn orch_spawn_relay(_t: &str, _a: Value) -> String {
}

fn orch_dispatch(_t: &str, _to: &str) -> String {
}

fn orch_bring_in(_q: &str) -> String {
}

fn drive_set_root(_w: &String) {
}

fn drive_clear_root() {
}

fn relay_advance(_w: &String, _r: &String) -> Value {
}

fn relay_publish(_r: &String, _v: &T) {
}

fn advance_is_none(_r: &T) -> bool {
}

fn advance_kind(_r: &T) -> String {
}

fn advance_role_id(_r: &T) -> String {
}

fn relay_submit_error(_r: &String, _r2: &String, _e: &String) {
}

fn relay_step_context(_w: &String, _r: &String) -> String {
}

fn factory_build_agent(_s: &T, _w: &String, _r: &String, _r2: &String) -> Value {
}

fn drive_accumulated(_w: &String, _r: &String) -> String {
}

fn drive_finalize_output(_o: &str, _r: &T) -> String {
}

fn drive_submit_handoff(_w: &String, _r: &String, _r2: &String, _o: &String, _v: &T) {
}

fn drive_handle_stream_event(_w: &String, _r: &String, _r2: &String, _e: i32) {
}

fn agent_register_shared(_a: &T, _t: Value) {
}

fn agent_register_skill_tool(_a: &T) {
}

fn agent_with_context_file(_a: Value, _p: &String) -> Value {
}

fn agent_with_history(_a: Value, _h: &String) -> Value {
}

fn build_agent_with_context(_m: Value, _c: Value, _ctx: Value) -> Value {
}

fn mode_tools_contains(_m: &T, _n: &String) -> bool {
}

fn resolve_role(_s: &str) -> Value {
}

fn registry_resolve(_r: Value, _s: &String) -> Value {
}

fn load_builtin_role(_s: &String) -> Value {
}

fn read_at_file(_s: &String) -> String {
}

fn find_context_file() -> Value {
}

fn find_ctx_upward(_c: &String) -> Value {
}

fn current_dir() -> String {
}

fn ctx_is_some(_c: &T) -> bool {
}

fn ctx_unwrap(_c: Value) -> String {
}

fn handoff_render(_h: &str) -> String {
}

fn agent_run(_s: &T, _q: Value, _b: Value) -> Value {
}

fn chat_run_stream(_s: &T, _q: Value, _p: Value, _sink: Value) {
}

fn agent_run_stream(_s: &T, _q: Value, _b: Value, _sink: Value) {
}

fn agent_run_stream_with_sink(_a: Value, _t: &str, _sink: Value, _c: Value) -> Value {
}

fn serve_init_state(_c: Value) -> Value {
}

fn serve_build_static() {
}

fn serve_build_cors() {
}

fn stream_event_map(_e: i32) -> Value {
}

fn workflow_event_map(_e: i32) -> Value {
}

fn step_err_is_err(e: &str) -> bool {
}

fn resolve_within_project(p: &String) -> String {
}

fn write_file_do(p: &String, c: &String) {
}

fn command_needs_approval(c: &String) -> bool {
}

fn run_shell_command(c: &String) -> String {
}

fn edit_file_do(p: &String, o: &String, n: &String) -> String {
}

fn batch_replace_do(p: &String, _r: Value) -> String {
}

fn search_files(p: &String) -> String {
}

fn list_directory(p: &String) -> String {
}

fn list_symbols_in(p: &String) -> String {
}

fn glob_files(p: &String) -> String {
}

fn http_post_json(_u: &String) -> Value {
}

fn mpsc_channel() -> Value {
}

fn mpsc_try_send(t: &T, m: Value) {
}

fn mpsc_recv(r: &T) -> Value {
}

fn msg_is_none(m: &T) -> bool {
}

fn msg_unwrap(m: Value) -> Value {
}

fn broadcast_recv(_r: i32) -> Value {
}

fn path_inner(p: &T) -> String {
}

fn json_response(_d: Value) -> Value {
}

fn error_response(_c: i32, _d: Value) -> Value {
}

fn atomic_bool_false() -> Value {
}
