use super::extern_impl::*;
// Auto-generated by a2r transpiler

use std::collections::HashMap;
use std::sync::Arc;
use std::path::PathBuf;
use std::time::SystemTime;
use serde::Serialize;
use serde_json::Value;
use serde_json::to_value;
use auto_ai_agent::orchestration::{AdvanceResult, FlowSpec, FlowStep, HandoffDocument, PipelineEngine};
use crate::server::AppState;
use crate::workspace::WorkspaceStores;
use crate::mode::AgentMode;
use crate::auto_generated::auto_lib::build_agent_from_mode;
/// feature_dev.at — port of backend/crates/musk/src/relay/feature_dev.rs
/// (Plan 020 Phase A: Relay 引擎层 .at 移植)。对齐 hw 409 行。
/// 
/// 移植策略:
/// - 纯逻辑全移植:builtin_names / require_builtin / flow / step_spec /
/// substitute / eval_condition / now_secs + StepSpec / FeatureDevResult /
/// WorkflowStreamEvent 类型。
/// - drive loop 移植:PipelineEngine / FlowSpec / FlowStep / HandoffDocument /
/// AdvanceResult 是 auto_ai_agent 的 Auto 类型,可直接驱动;Agent::run 也是
/// Auto 方法。仅 3 个副作用 extern:feature_dev_set_root /
/// feature_dev_clear_root(tool_safety)、agent_error_msg(AgentError → str)。
/// Agent 构建直接调用 auto_generated::auto_lib::build_agent_from_mode
/// (全链路 Auto,不绕 hw)。
/// - run_stream 的 on_event 闭包 + tokio::spawn Auto 无法表达 → drive 接收
/// emit 句柄(Option<mpsc sender>),stream 事件经既有 extern mpsc_try_send
/// 发送;非流式 run() 传 None。hw run_stream 的 spawn 桥接放 extern
/// (Phase F 接线)。
/// 
/// 与 hw 的行为差异(均已文档化):
/// - tracing::info!/warn!(skip 日志 / 未识别 condition)不移植——纯日志,无行为。
/// - substitute 用 split("$") 等价实现(hw 是字节扫描)——对 `$` 语义逐项等价
/// (含 `$` 后接非标识符、`$$`、多字节字符),不移植 utf8_len_at。
/// - eval_condition 的引号剥离用 replace 替代 trim_matches——对未测试的
/// 双端多层引号边界不完全等价,测试形态(pass/fail 裸字面量)等价。
/// The tool whitelist for every feature-dev step — the old `shared_tools()`
/// set (read/write/run). Matches the original workflow's tool exposure.
fn step_tools() -> Vec<String> {
    return vec!["read_file".to_string(), "write_file".to_string(), "run_command".to_string()];
}

/// One step of the feature-dev workflow (hw `StepSpec`, &'static str → str)。
#[derive(Clone, Debug)]
pub struct StepSpec {
    pub step_id: String,
    pub profession: String,
    pub input_template: String,
    pub output_var: String,
    pub condition: Option<String>,
}

/// The profession this step runs (musk role id).
/// Per-step input template; `$var` refs are substituted from prior outputs.
/// The output variable this step's result is stored under (e.g. `$design`).
/// Optional skip condition (`$var` non-empty, or `$var.contains("...")`).
/// Port of `backend/crates/musk/workflows/feature-dev.at` (architect → coder →
/// tester → reviewer), verbatim prompt templates.
fn feature_dev_steps() -> Vec<StepSpec> {
    return vec![StepSpec { step_id: "architect".to_string(), profession: "architect".to_string(), input_template: "Design a plan for the following task. Output only the plan.\n\nTask:\n$user_request".to_string(), output_var: "$design".to_string(), condition: None }, StepSpec { step_id: "coder".to_string(), profession: "coder".to_string(), input_template: "Implement the following plan using the available tools (read_file/write_file/run_command). Write real code.\n\nPlan:\n$design".to_string(), output_var: "$code".to_string(), condition: None }, StepSpec { step_id: "tester".to_string(), profession: "tester".to_string(), input_template: "Write and run tests for the implementation described below. Use run_command to execute them. Report pass/fail.\n\nImplementation:\n$code".to_string(), output_var: "$test_report".to_string(), condition: None }, StepSpec { step_id: "reviewer".to_string(), profession: "reviewer".to_string(), input_template: "Review the implementation and test results. List issues, or confirm approval.\n\nImplementation:\n$code\n\nTests:\n$test_report".to_string(), output_var: "$review".to_string(), condition: Some("$test_report".to_string()) }];
}

fn step_spec(step_id: &str) -> Option<StepSpec> {
    for s in feature_dev_steps() {
        if s.step_id == step_id {
            return Some(s);
        }
    }
    return None;
}

pub fn builtin_names() -> Vec<String> {
    return vec!["feature-dev".to_string()];
}

pub fn require_builtin(workflow: &str) -> Result<(), String> {
    for name in builtin_names() {
        if name == workflow {
            return Ok(());
        }
    }
    return Err(format!("{}{}", format!("{}{}", "unknown workflow '", workflow), "' (built-ins: feature-dev) — custom .at workflows are retired"));
}

pub fn flow() -> FlowSpec {
    let mut f = FlowSpec::new("feature-dev");
    for s in feature_dev_steps() {
        let step = FlowStep::new(s.step_id, s.profession);
        f.add_step(step);
    }
    return f;
}

/// All built-in workflow names.
/// Validate a workflow spec: only the built-in name is accepted. Custom
/// `.at` workflow files are no longer supported (the old parser is retired).
/// The linear FlowSpec PipelineEngine drives for feature-dev.
/// Outcome of a feature-dev run — the same shape the old `WorkflowResult`
/// exposed (`/api/workflow/run` response contract)。
#[derive(Clone, Debug, Serialize)]
pub struct FeatureDevResult {
    pub steps: HashMap<String, String>,
    pub outputs: HashMap<String, String>,
    pub total_tokens: u64,
}

impl FeatureDevResult {
    pub fn default() -> FeatureDevResult {
        return FeatureDevResult { steps: HashMap::new(), outputs: HashMap::new(), total_tokens: 0 };
    }
}

/// Each step id → its textual output (skipped steps are absent).
/// Each output variable (no `$`) → its value.
/// Total tokens consumed across all steps (与 hw 同型 u64)。
/// Step-level progress events — byte-for-byte the old `WorkflowEvent` SSE
/// shapes (`{"type":...}`), so existing consumers are unaffected.
#[derive(Clone, Debug, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum WorkflowStreamEvent {
    StepStart { step_id: String, role: String, input: String },
    StepDone { step_id: String, output: String },
    StepSkipped { step_id: String },
    Finished { steps: HashMap<String, String>, outputs: HashMap<String, String> },
}


/// Seconds since the UNIX epoch (hw now_secs; wiki.at 同款实现)。
fn now_secs() -> u64 {
    let elapsed = SystemTime::now().duration_since(SystemTime::UNIX_EPOCH).unwrap_or_default();
    return elapsed.as_secs();
}

/// Scan leading `[A-Za-z0-9_]` chars; return [name, remainder].
/// 
/// NOTE: 用 starts_with 逐字符扫描而非 per-byte slicing——hw 是字节扫描
/// (is_ascii_alphanumeric),而 a2r 的 substring(i, i+1) 生成 `&s[i..i+1]`,
/// 对多字节 UTF-8 字符(如 'é')会 panic(char boundary)。starts_with 是安全
/// 的 UTF-8 查找;命中 1 字符后 substring(1, len) 必在 char boundary。
fn take_identifier(s: &str) -> Vec<String> {
    let mut name: String = "".to_string();
    let mut rest: String = s.to_string();
    let alphabet: Vec<String> = vec!["a".to_string(), "b".to_string(), "c".to_string(), "d".to_string(), "e".to_string(), "f".to_string(), "g".to_string(), "h".to_string(), "i".to_string(), "j".to_string(), "k".to_string(), "l".to_string(), "m".to_string(), "n".to_string(), "o".to_string(), "p".to_string(), "q".to_string(), "r".to_string(), "s".to_string(), "t".to_string(), "u".to_string(), "v".to_string(), "w".to_string(), "x".to_string(), "y".to_string(), "z".to_string(), "A".to_string(), "B".to_string(), "C".to_string(), "D".to_string(), "E".to_string(), "F".to_string(), "G".to_string(), "H".to_string(), "I".to_string(), "J".to_string(), "K".to_string(), "L".to_string(), "M".to_string(), "N".to_string(), "O".to_string(), "P".to_string(), "Q".to_string(), "R".to_string(), "S".to_string(), "T".to_string(), "U".to_string(), "V".to_string(), "W".to_string(), "X".to_string(), "Y".to_string(), "Z".to_string(), "0".to_string(), "1".to_string(), "2".to_string(), "3".to_string(), "4".to_string(), "5".to_string(), "6".to_string(), "7".to_string(), "8".to_string(), "9".to_string(), "_".to_string()];
    let mut done: bool = false;
    while !(done) {
        let mut matched: bool = false;
        for c in alphabet.clone() {
            if rest.starts_with(&c) {
                name = format!("{}{}", name, c);
                let c_len = (c.len() as i32);
                let r_len = (rest.len() as i32);
                rest = rest[c_len as usize..r_len as usize].to_string();
                matched = true;
                break;
            }
        }
        if !(matched) {
            done = true;
        }
    }
    return vec![name, rest];
}

pub fn substitute(template: &str, vars: HashMap<String, String>) -> String {
    let mut out: String = "".to_string();
    let parts = template.split("$").collect::<Vec<_>>();
    let mut first: bool = true;
    for part in parts.clone() {
        
        let part_owned = part.to_string();
        if first {
            out = part_owned;
            first = false;
        } else {
            let scanned = take_identifier(&part_owned);
            let name: String = scanned[0].clone();
            let remainder: String = scanned[1].clone();
            if (name.len() as i32) == 0 {
                

                out = format!("{}{}", format!("{}{}", out, "$"), part_owned);
            } else {
                match vars.get(&name) {
                    Some(val) => out = format!("{}{}", format!("{}{}", out, val), remainder),
                    None => out = format!("{}{}", format!("{}{}", format!("{}{}", out, "$"), name), remainder),
                };
            }
        }

    }
    return out;
}

pub fn eval_condition(expr: &str, vars: HashMap<String, String>) -> bool {
    let trimmed = expr.trim().to_string();
    if trimmed.starts_with("$") == false {
        return true;
    }
    let total: i32 = (trimmed.len() as i32);
    let rest = &trimmed[1 as usize..total as usize];

    let parts = rest.split(".contains(").collect::<Vec<_>>();
    if (parts.len() as i32) == 2 {
        let lit_parts = parts[1].clone().split(")").collect::<Vec<_>>();
        if (lit_parts.len() as i32) == 2 {
            let mut literal: String = lit_parts[0].clone().trim().to_string();
            literal = literal.replace("\"", "");
            literal = literal.replace("'", "");
            let var_name = parts[0].clone().to_string();
            match vars.get(&var_name) {
                Some(v) => return v.contains(&literal),
                None => return false,
            };
        }    }

    match vars.get(rest) {
        Some(v) => return (v.len() as i32) > 0,
        None => return false,
    }
}

pub async fn run(state: AppState, ws: Arc<WorkspaceStores>, task_text: &str) -> Result<FeatureDevResult, String> {
    return drive(state.clone(), ws.clone(), task_text, None).await;
}

pub async fn run_with_emit(state: AppState, ws: Arc<WorkspaceStores>, task_text: &str, emit: Value) -> Result<FeatureDevResult, String> {
    return drive(state.clone(), ws.clone(), task_text, Some(emit)).await;
}

/// Replace `$var` references in `template` with values from `vars`. Unknown
/// vars are left as-is so a missing dependency surfaces visibly. (hw 字节扫描
/// 的 split("$") 等价实现——`$` 后接非标识符 / `$$` / 多字节字符逐项等价。)
/// Evaluate a step condition (port of the old `evaluate_condition`):
/// `$var` → true iff non-empty; `$var.contains("lit")` → substring check.
/// Unknown shapes fail open (run the step).
/// Run feature-dev to completion (non-streaming)。
/// Streaming 变体:emit 为 mpsc sender 句柄(Value),事件经 mpsc_try_send 发出。
/// hw run_stream 的 on_event 闭包 + tokio::spawn 由 extern 桥接(Phase F)。
/// 发出一个 stream 事件(emit 为 None 时 no-op——非流式路径)。
fn emit_event(emit: Option<Value>, ev: WorkflowStreamEvent) {
    match emit {
        Some(tx) => {
            let v = to_value(ev).unwrap();
            mpsc_try_send(&tx, v);
        },
        None => {},
    };
}

/// The shared drive loop(hw `drive`;`on_event` → emit 句柄)。
/// - `done` 标志替代 hw 的 `break Ok(result)`(a2r 无 break-value);成功后
/// 在清理 tool root 之后再 emit Finished(与 hw 顺序一致)。
async fn drive(state: AppState, ws: Arc<WorkspaceStores>, task_text: &str, emit: Option<Value>) -> Result<FeatureDevResult, String> {

    feature_dev_set_root(ws.root.clone());

    let n: u64 = now_secs();
    let run_id: String = format!("workflow-feature-dev-{}", n);
    let mut engine = PipelineEngine::new(flow(), run_id.as_str());


    let mut vars: HashMap<String, String> = HashMap::new();
    vars.insert("user_request".to_string(), task_text.to_string());

    let mut result = FeatureDevResult::default();
    let mut drive_result: Result<FeatureDevResult, String> = Ok(result.clone());
    let mut done: bool = false;
    while !(done) {
        let ar = engine.advance();
        match ar {
            AdvanceResult::ExecuteStep { step_id: step_id, role_id: role_id } => {
                match step_spec(&step_id) {
                    None => {
                        drive_result = Err(format!("{}{}", format!("{}{}", "feature-dev: unknown step '", step_id), "'"));
                        done = true;
                    },
                    Some(s) => {
                        

                        let mut skip: bool = false;
                        match s.condition.clone() {
                            Some(cond) => {
                                if eval_condition(cond.as_str(), vars.clone()) == false {
                                    skip = true;
                                }
                            },
                            None => {},
                        };
                        if skip {
                            emit_event(emit.clone(), WorkflowStreamEvent::StepSkipped { step_id: step_id.clone() });
                            




                            let mut h = HandoffDocument::new(&role_id, "");
                            let r2 = engine.submit_handoff(h);
                            match r2 {
                                AdvanceResult::Completed => {
                                    drive_result = Ok(result.clone());
                                    done = true;
                                },
                                AdvanceResult::Failed { error: e } => {
                                    drive_result = Err(e);
                                    done = true;
                                },
                                AdvanceResult::Paused { step_id: sid, reason: reason } => {
                                    drive_result = Err(format!("{}{}", format!("{}{}", format!("{}{}", "paused at '", sid), "': "), reason));
                                    done = true;
                                },
                                _ => {},
                            };
                        } else {
                            let input = substitute(&s.input_template, vars.clone());
                            emit_event(emit.clone(), WorkflowStreamEvent::StepStart { step_id: step_id.clone(), role: role_id.clone(), input: input.clone() });
                            



                            let mode = AgentMode { name: format!("{}{}", "workflow-", step_id), description: "".to_string(), role: role_id.clone(), skills: false, tools: step_tools(), workflow: None, context_file: "".to_string(), extra_system_prompt: "".to_string() };
                            match build_agent_from_mode(mode, state.client.clone()) {
                                Err(e) => {
                                    drive_result = Err(format!("{}{}", format!("{}{}", format!("{}{}", "build agent '", role_id), "': "), e));
                                    done = true;
                                },
                                Ok(agent0) => {
                                    let mut agent = agent0;
                                    let run_result = agent.run(&input).await;
                                    match run_result {
                                        Err(e2) => {
                                            drive_result = Err(format!("{}{}", format!("{}{}", format!("{}{}", "agent '", step_id), "' failed: "), agent_error_msg(&e2)));
                                            done = true;
                                        },
                                        Ok(ar2) => {
                                            let output = ar2.output;
                                            emit_event(emit.clone(), WorkflowStreamEvent::StepDone { step_id: step_id.clone(), output: output.clone() });
                                            


                                            result.steps.insert(step_id.clone(), output.clone());
                                            let key = s.output_var.replace("$", "");
                                            vars.insert(key.clone(), output.clone().to_string());
                                            result.outputs.insert(key.to_string(), output.clone());
                                            result.total_tokens = result.total_tokens + ar2.total_tokens;
                                            



                                            let mut h = HandoffDocument::new(&role_id, "");
                                            h.summary = output;
                                            h.token_usage.step_tokens = ar2.total_tokens;
                                            

                                            let r3 = engine.submit_handoff(h);
                                            match r3 {
                                                AdvanceResult::Completed => {
                                                    drive_result = Ok(result.clone());
                                                    done = true;
                                                },
                                                AdvanceResult::Failed { error: e3 } => {
                                                    drive_result = Err(e3);
                                                    done = true;
                                                },
                                                AdvanceResult::Paused { step_id: sid2, reason: reason2 } => {
                                                    drive_result = Err(format!("{}{}", format!("{}{}", format!("{}{}", "paused at '", sid2), "': "), reason2));
                                                    done = true;
                                                },
                                                _ => {},
                                            };
                                        },
                                    };
                                },
                            };
                        }

                    },
                };
            },
            AdvanceResult::Completed => {
                drive_result = Ok(result.clone());
                done = true;
            },
            AdvanceResult::Failed { error: e } => {
                drive_result = Err(e);
                done = true;
            },
            AdvanceResult::Paused { step_id: sid, reason: reason } => {
                drive_result = Err(format!("{}{}", format!("{}{}", format!("{}{}", "paused at '", sid), "': "), reason));
                done = true;
            },
            AdvanceResult::WaitForHuman { step_id: sid } => {
                drive_result = Err("unexpected human gate in feature-dev".into());
                done = true;
            },
        };
    }

    feature_dev_clear_root();

    match drive_result {
        Err(e) => return Err(e),
        Ok(final_result) => {
            emit_event(emit.clone(), WorkflowStreamEvent::Finished { steps: final_result.steps.clone(), outputs: final_result.outputs.clone() });
            return Ok(final_result);
        },
    }
}