use super::extern_impl::*;
// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use std::sync::Mutex;
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::fs;
use serde_json::{to_string_pretty, from_str, to_value};
use serde_json::Value;

use crate::relay::store::RunStore;
use auto_ai_agent::orchestration::HandoffDocument;
/// handoff_store.at — Cross-run handoff storage (relay/handoff_store.rs) — Plan 018 Phase 3.5。
/// 
/// Ported from backend/crates/musk/src/relay/handoff_store.rs. Scope:
/// - HandoffStore (data_dir + Mutex cache) + save/load/resolve_path -> Auto
/// - save_from_run 依赖 crate::relay::store::RunStore (use.rust 上游类型) -> Auto
/// 
/// a2r 惯用法注记(本轮探测确认):
/// - tuple-key `HashMap<(String,String,String), _>` 不可用(insert 误加
/// .to_string() tuple 无 Display / get 缺 &) -> 字符串拼接 key 变通
/// (cache 是私有字段,行为等价,计划 §0 允许实现细节不同)
/// - `impl Into<PathBuf>` -> PathBuf 参数 (C6 已知退化)
/// - Result 链式 .ok()/.map_err -> is 匹配逐层展开
/// - `if let Some(parent) = path.parent()` -> is 匹配
/// Persist and query handoffs across TaskPlan runs.
#[derive(Debug)]
pub struct HandoffStore {
    pub data_dir: PathBuf,
    pub cache: Mutex<HashMap<String, HandoffDocument>>,
}

impl HandoffStore {
    pub fn new(data_dir: PathBuf) -> HandoffStore {
        HandoffStore { data_dir: data_dir, cache: Mutex::new(HashMap::new()) }
    }
    pub fn handoffs_dir(&self, task_plan_id: &str) -> PathBuf {


        let a: PathBuf = self.data_dir.join("task_plans");
        let b: PathBuf = a.join(".handoffs");
        let c: PathBuf = b.join(task_plan_id);
        return c;
    }
    pub fn handoff_path(&self, task_plan_id: &str, phase: &str, run: &str) -> PathBuf {
        let dir: PathBuf = self.handoffs_dir(task_plan_id);
        let a: PathBuf = dir.join(phase);
        let path: PathBuf = a.join(format!("{}{}", run, ".json"));
        return path;
    }
    pub fn save(&self, task_plan_id: &str, phase: &str, run: &str, handoff: HandoffDocument) -> Result<bool, String> {
        let path: PathBuf = self.handoff_path(task_plan_id, phase, run);
        match path.parent() {
            Some(parent) => {
                let mkdir_result = fs::create_dir_all(parent);
                match mkdir_result {
                    Err(e) => return Err(format!("{}{}", "failed to create handoff dir: ", e.to_string())),
                    Ok(_) => {},
                };
            },
            None => {},
        };
        let json_result = to_string_pretty(&handoff);
        match json_result {
            Err(e) => return Err(format!("{}{}", "failed to serialize handoff: ", e.to_string())),
            Ok(json) => {
                


                let write_ok: bool = std::fs::write(path, json.as_str()).is_ok();
                if write_ok == false {
                    return Err("failed to write handoff".into());
                }
            },
        };

        let key: String = format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", task_plan_id, "/"), phase), "/"), run);
        let _: bool = cache_put(&self.cache, &key, handoff.clone());
        return Ok(true);
    }
    pub fn load(&self, task_plan_id: &str, phase: &str, run: &str) -> Option<HandoffDocument> {
        let key: String = format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", task_plan_id, "/"), phase), "/"), run);



        let cached: Option<HandoffDocument> = cache_get(&self.cache, &key);
        match cached {
            Some(doc) => return Some(doc),
            None => {},
        };
        let path: PathBuf = self.handoff_path(task_plan_id, phase, run);
        let content_result = std::fs::read_to_string(path);
        match content_result {
            Err(_) => return None,
            Ok(content) => {
                let doc_opt: Option<HandoffDocument> = parse_handoff(content.as_str());
                match doc_opt {
                    None => return None,
                    Some(doc) => {
                        let _: bool = cache_put(&self.cache, &key, doc.clone());
                        return Some(doc);
                    },
                };
            },
        }
    }
    pub fn resolve_path(&self, path: &str) -> Option<Value> {
        let parts = path.split(".").collect::<Vec<_>>();
        if (parts.len() as i32) < 5 || parts[3].clone() != "handoff" {
            return None;
        }
        let task_plan_id = parts[0].clone();
        let phase = parts[1].clone();
        let run = parts[2].clone();
        let handoff_opt: Option<HandoffDocument> = self.load(task_plan_id, phase, run);
        match handoff_opt {
            None => return None,
            Some(handoff) => {
                let doc_json_result = to_value(&handoff);
                match doc_json_result {
                    Err(_) => return None,
                    Ok(doc_json) => {
                        let mut value = doc_json;
                        for i in 4..(parts.len() as i32) {
                            match value.get(&parts[(i) as usize].clone()) {
                                Some(v) => value = v.clone(),
                                None => return None,
                            };
                        }
                        return Some(value.clone());
                    },
                };
            },
        }
    }
    pub fn save_from_run(&self, store: &RunStore, task_plan_id: &str, phase: &str, run_name: &str, run_id: &str) -> Option<HandoffDocument> {
        let handoff_opt: Option<HandoffDocument> = store.last_handoff(&run_id);
        match handoff_opt {
            Some(h) => return Some(h.clone()),
            None => return None,
        }
    }
}

/// Optional in-memory cache keyed by "tp/phase/run" (string key — a2r
/// tuple-key 缺陷见文件头注记; hw 用 (String,String,String) tuple)。
/// Create a store rooted at the workspace data directory.
/// Directory where handoffs are persisted for a given task plan.
/// File path for a specific handoff.
/// Save a handoff to disk and cache. Ok(true) on success (hw: Result<(), String>
/// — a2r 无法表达 unit 类型,用 bool 载荷承载,与 task_plan/specs 同约定)。
/// Load a handoff from cache or disk.
/// Resolve a path like `task_plan_id.phase.run.handoff.field` to a JSON value.
/// Collect the final handoff from a completed relay run and save it.
/// Parse handoff JSON text. (独立辅助 fn — a2r 对 from_str 的返回类型推断在
/// Option 返回上下文中不可靠, 用显式返回类型驱动; 同 wiki parse_manifest 模式。)
fn parse_handoff(content: &str) -> Option<HandoffDocument> {
    let pr = from_str(content);
    match pr {
        Ok(doc) => return Some(doc),
        Err(_) => return None,
    }
}

/// Lock + read a cache entry. Guard drops at fn exit (avoids Mutex deadlock
/// from a2r's match-keeping-lock — see load() note).
fn cache_get(cache: &Mutex<HashMap<String, HandoffDocument>>, key: &str) -> Option<HandoffDocument> {
    let mut guard = cache.lock().unwrap();
    match guard.get(key) {
        Some(doc) => return Some(doc.clone()),
        None => return None,
    }
}

/// Lock + insert a cache entry.
fn cache_put(cache: &Mutex<HashMap<String, HandoffDocument>>, key: &str, doc: HandoffDocument) -> bool {
    let mut guard = cache.lock().unwrap();
    let _: Option<HandoffDocument> = guard.insert(key.to_string(), doc.clone());
    return true;
}