use super::extern_impl::*;
// Auto-generated by a2r transpiler

use clap::{Parser, Subcommand};
use clap::Parser;
use std::sync::Arc;
use auto_ai_client::AiClient;
#[derive(Parser, Subcommand)]
struct Cli {
    pub cmd: String,
}

#[tokio::main]
async fn main() {
    let cli = Cli::parse();
    init_project_root();
    apply_app_config();
    run_main(cli.clone()).await;
}

async fn run_main(cli: Cli) -> () {
    let cmd_input: String = cli.cmd.clone();
    if cmd_input == "professions" {
        list_professions()
    } else {
        if cmd_input == "modes" {
            list_modes()
        } else {
            if cmd_input == "serve" {
                let client = make_client_or_fallback();
                serve(cli).await
            } else {
                let client = make_client();
                run_task(cli).await
            }
        }
    }

}

#[async_trait::async_trait]
trait Client {
    async fn complete(&self, req: i32) -> String;
}


#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct NoDaemonClient {}

#[async_trait::async_trait]
impl Client for NoDaemonClient {
    async fn complete(&self, req: i32) -> String {
        return Ok("daemon not running");
    }
}

fn make_client() -> Arc<dyn Client> {
    return Arc::new(AiClient::new());
}

fn make_client_or_fallback() -> Arc<dyn Client> {
    let result = make_client_or_none();
    match result {
        Some(c) => return c,
        None => return Arc::new(NoDaemonClient {}),
    };
}
