use super::extern_impl::*;
// Auto-generated by a2r transpiler

use std::collections::HashMap;
/// mode.at — ported from backend/crates/musk/src/mode.rs.
/// 
/// Agent 运行模式配置。Strategy (plan 014 mixed):
/// - AgentMode struct + ModeRegistry pure logic (names/lookup/default) -> Auto
/// - parse_mode_at + auto_atom/auto_val navigation -> hand-written Rust
/// (AtomParser::parse / Atom::Node / node.get_prop_of / Value enum are
/// auto-lang upstream APIs a2r can't express)
/// - include_str! builtin embedding + user-dir file scan -> hand-written Rust
/// 一种运行模式的配置。
#[derive(Clone, Debug)]
pub struct AgentMode {
    pub name: String,
    pub description: String,
    pub role: String,
    pub skills: bool,
    pub tools: Vec<String>,
    pub workflow: Option<String>,
    pub context_file: String,
    pub extra_system_prompt: String,
}

/// 模式注册表:内置 + 用户自定义。用户模式同名时覆盖内置。
/// (用 List 而非 HashMap 存储 — a2r-10 对 HashMap<_, struct> 方法处理有缺陷;
/// 模式数量少，线性查找无性能影响。)
#[derive(Clone, Debug)]
pub struct ModeRegistry {
    pub modes: Vec<AgentMode>,
}

impl ModeRegistry {
    pub fn default_name() -> String {
        return "superpowers".to_string();
    }
    pub fn names(&self) -> Vec<String> {
        let mut result: Vec<String> = vec![];
        for m in self.modes.clone() {
            result.push(m.name.clone());
        }
        result.sort();
        return result;
    }
    pub fn get(&self, name: &str) -> Option<AgentMode> {
        for m in self.modes.clone() {
            if m.name == name {
                return Some(m);
            }
        }
        return None;
    }
    pub fn contains(&self, name: &str) -> bool {
        for m in self.modes.clone() {
            if m.name == name {
                return true;
            }
        }
        return false;
    }
    pub fn register(&mut self, mode: AgentMode) {
        let mut new_modes: Vec<AgentMode> = vec![];
        let mut found: bool = false;
        for m in self.modes.clone() {
            if m.name == mode.name {
                found = true;
                new_modes.push(mode.clone())
            } else {
                new_modes.push(m.clone())
            }

        }
        if found == false {
            new_modes.push(mode.clone());
        }
        self.modes = new_modes;
    }
}