use super::extern_impl::*;
// Auto-generated by a2r transpiler

use axum::Router;
use axum::routing::{get, post, delete, put, patch};
use axum::extract::{Query, Path, State};
use axum::Json;
use axum::response::Response;
use axum::response::IntoResponse;
use axum::response::sse::{Event, KeepAlive, Sse};
use std::convert::Infallible;
use serde::{Serialize, Deserialize};
use serde_json::Value;
use serde_json::to_value;
use crate::server::AppState;
use crate::auto_generated::relay_store::StartRunRequest;
/// relay_api.at — ported from backend/crates/musk/src/relay/api.rs (full HTTP layer,
/// Plan 020 Phase D: 13 relay + 6 task_plan handlers + 2 routers)。
/// 
/// Strategy (plan 014 mixed + 019 SSE precedent):
/// - 全部 handler -> Auto(State/Query/Path/Json extractor + ~Response + 错误包络)。
/// - Store/registry/driver/bus 访问 -> extern 委托(018/019 已固化的模式):
/// ws.relay / ws.task_plans / ProfessionRegistry::load / builtin_flows 由 extern
/// 封装返回序列化 Value;成功/404/400 状态码在 .at 侧决定(hw 等价)。
/// - run_events / task_plan_events SSE -> 019 server_stream 同 recipe:
/// extern 订阅 bus(RelaySub 持有 Receiver + run_id 过滤),.at ~Stream 循环
/// recv + sse_named_event(带 event 名,对齐 hw `.event(...)`)。
/// - advance_run / resolve_gate 的 tokio::spawn(drive_run) -> extern
/// (Arc + spawn 是 a2r 盲区;spawn 后返回当前 snapshot,与 hw 语义一致)。
/// - start_task_plan_run 的 engine + spawn -> extern(Arc<dyn TaskPlanExecutor>
/// 闭包适配 hw drive_task_plan_run 是 a2r 盲区)。
/// 
/// a2r 习得沿用:
/// - extern 的 @T/@str 参数调用点不写 .view(自动注入 &);本地 fn 的 str 参数
/// 生成 &str,跨模块调用需 .view。
/// - is 臂 block 内绑定 Some(v) 可用;Auto 关键字避让(spec/dep/task/var)。
/// An event on the relay broadcast bus (the SSE payload).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct BusEvent {
    pub run_id: String,
    pub event_type: String,
    pub payload: Value,
}

#[derive(Debug, Deserialize)]
pub struct ResolveGateBody {
    pub decision: String,
    #[serde(default)]
    pub feedback: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct SubmitHandoffBody {
    pub handoff: Value,
}

#[derive(Debug, Deserialize)]
pub struct UpdateTitleBody {
    pub title: String,
}

#[derive(Debug, Deserialize)]
pub struct ListRunsQuery {
    pub project_path: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct CreateTaskPlanBody {
    pub atom: String,
}

#[derive(Debug, Deserialize)]
pub struct StartTaskPlanRunBody {
    pub initial_input: String,
}

#[derive(Debug, Deserialize)]
pub struct WorkspaceQuery {
    pub workspace: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct DeletedResp {
    pub status: String,
    pub id: String,
}

#[derive(Debug, Serialize)]
pub struct SoulsResp {
    pub souls: Vec<Value>,
}

#[derive(Debug, Serialize)]
pub struct RegisteredResp {
    pub task_plan_registered: bool,
    pub id: String,
    pub phase_count: u32,
    pub run_count: u32,
}

#[derive(Debug, Serialize)]
pub struct StartedResp {
    pub instance_id: String,
    pub task_plan_id: String,
    pub status: String,
}

#[derive(Debug, Serialize)]
pub struct DeletedPlanResp {
    pub deleted: String,
}

/// SSE 单帧 payload — run_events 的 `{"event_type", "payload"}` 包装
/// (hw json! 逐键等价;run_id 由订阅端过滤,不进 wire)。
#[derive(Debug, Serialize)]
pub struct RunEventFrame {
    pub event_type: String,
    pub payload: Value,
}

pub async fn run_events(p: Path<String>) -> Response {
    let run_id: String = path_inner(&p);
    let sub = relay_bus_subscribe(&run_id);
    let stream = run_events_stream(sub.clone());
    let mut sse = Sse::new(stream);
    return sse.keep_alive(KeepAlive::new()).into_response();
}

/// GET /api/forge/relay/runs/{run_id}/events — SSE 流(run 事件,按 run_id 过滤)。
fn run_events_stream(sub: RelaySub) -> impl futures::Stream<Item = Result<Event, Infallible>> { async_stream::stream! {{
    loop {
        let msg = relay_sub_recv(&sub).await;
        if msg_is_none(&msg) {
            

            break;
        } else {
            let ev = msg_unwrap(msg);
            let ev_type: String = value_get_str(&ev, "event_type");
            let payload: Value = value_get(&ev, "payload");
            let frame = RunEventFrame { event_type: ev_type.to_string(), payload: payload };
            // PLAN-030 试用修复：未命名事件（onmessage 兼容）——具名事件
            // EventSource.onmessage 收不到，RunBox 实时更新全链路失效。
            let event = sse_plain_event(to_value(frame).unwrap());
            yield Ok(event);
        }

    }
} } }

pub async fn list_runs(s: State<AppState>, q: Query<WorkspaceQuery>) -> Response {
    let runs: Value = relay_runs_list(&s, q);
    return ok_response(runs);
}

pub async fn start_run(s: State<AppState>, q: Query<WorkspaceQuery>, body: Json<StartRunRequest>) -> Response {
    let resp: Value = relay_start_run(&s, q, body);
    return ok_response(resp);
}

/// GET /api/forge/relay/runs/{run_id}/report — PLAN-032: 汇报报告 HTML 全文。
pub async fn run_report_html(s: State<AppState>, p: Path<String>, q: Query<WorkspaceQuery>) -> Response {
    let run_id: String = path_inner(&p);
    let hw_q = crate::workspace::WorkspaceQuery { workspace: q.workspace.clone() };
    let ws_id = hw_q.id_or_default(&s.0.registry);
    let ws = s.0.registry.get(&ws_id);
    // 元数据优先；重启后 run 清空 → 磁盘确定性路径回退（hw 同款）。
    let fallback = crate::relay::store::ReportMeta {
        format: "html".into(),
        title: String::new(),
        path: format!(".autoos/reports/{}/report.html", run_id),
        structured: None,
    };
    match Some(ws.relay.report_meta(&run_id).unwrap_or(fallback)) {
        None => text_response(format!("run '{}' has no report", run_id), 404),
        Some(meta) => match std::fs::read_to_string(ws.root.join(&meta.path)) {
            Ok(html) => (
                [(axum::http::header::CONTENT_TYPE, "text/html; charset=utf-8")],
                html,
            )
                .into_response(),
            Err(e) => text_response(format!("report file missing: {} ({})", meta.path, e), 404),
        },
    }
}

pub async fn get_run(s: State<AppState>, p: Path<String>, q: Query<WorkspaceQuery>) -> Response {
    let run_id: String = path_inner(&p);
    let state: Value = relay_run_get(&s, q, &run_id);
    if value_is_null(&state) {
        return text_response(format!("{}{}", format!("{}{}", "run '", run_id), "' not found").as_str(), 404);
    }
    return ok_response(state);
}

pub async fn delete_run(s: State<AppState>, p: Path<String>, q: Query<WorkspaceQuery>) -> Response {
    let run_id: String = path_inner(&p);
    if relay_run_delete(&s, q, &run_id) {
        return ok_response(DeletedResp { status: "deleted".to_string(), id: run_id.to_string() });
    }
    return text_response(format!("{}{}", format!("{}{}", "run '", run_id), "' not found").as_str(), 404);
}

pub async fn update_title(s: State<AppState>, p: Path<String>, q: Query<WorkspaceQuery>, body: Json<UpdateTitleBody>) -> Response {
    let run_id: String = path_inner(&p);
    let state: Value = relay_run_set_title(&s, q, &run_id, &body.title);
    if value_is_null(&state) {
        return text_response(format!("{}{}", format!("{}{}", "run '", run_id), "' not found").as_str(), 404);
    }
    return ok_response(state);
}

pub async fn advance_run(s: State<AppState>, p: Path<String>, q: Query<WorkspaceQuery>) -> Response {
    let run_id: String = path_inner(&p);
    let state: Value = relay_run_advance(&s, q, &run_id);
    if value_is_null(&state) {
        return text_response(format!("{}{}", format!("{}{}", "run '", run_id), "' not found").as_str(), 404);
    }
    return ok_response(state);
}

pub async fn submit_handoff(s: State<AppState>, p: Path<String>, q: Query<WorkspaceQuery>, body: Json<SubmitHandoffBody>) -> Response {
    let run_id: String = path_inner(&p);
    let resp: Value = relay_submit_handoff(&s, q, &run_id, &body.handoff);
    if resp_is_err(&resp) {
        return text_response(resp_err_message(&resp), resp_err_code(&resp));
    }
    if value_is_null(&resp) {
        return text_response(format!("{}{}", format!("{}{}", "run '", run_id), "' not found").as_str(), 404);
    }
    return ok_response(resp);
}

pub async fn resolve_gate(s: State<AppState>, p: Path<String>, q: Query<WorkspaceQuery>, body: Json<ResolveGateBody>) -> Response {
    let run_id: String = path_inner(&p);
    let decision: String = body.decision.clone();
    if decision != "approve" {
        if decision != "edit" {
            if decision != "reject" {
                return text_response(format!("{}{}", format!("{}{}", "unknown gate decision '", decision), "' (want approve|reject|edit)").as_str(), 400);
            }        }    }
    let mut feedback: String = "".to_string();


    match body.feedback.clone() {
        Some(f) => feedback = f,
        None => {},
    };
    let resp: Value = relay_resolve_gate(&s, q, &run_id, &decision, &feedback);
    if value_is_null(&resp) {
        return text_response(format!("{}{}", format!("{}{}", "run '", run_id), "' not found").as_str(), 404);
    }
    return ok_response(resp);
}

pub async fn rerun_run(s: State<AppState>, p: Path<String>, q: Query<WorkspaceQuery>) -> Response {
    let run_id: String = path_inner(&p);
    let state: Value = relay_rerun(&s, q, &run_id);
    if value_is_null(&state) {
        return text_response(format!("{}{}", format!("{}{}", "run '", run_id), "' not found").as_str(), 404);
    }
    return ok_response(state);
}

pub async fn list_professions() -> Response {
    return ok_response(relay_professions_list());
}

pub async fn list_souls() -> Response {
    let mut souls: Vec<Value> = vec![];
    return ok_response(SoulsResp { souls: souls });
}

pub async fn list_flows() -> Response {
    return ok_response(relay_flows_list());
}

pub async fn list_task_plans(s: State<AppState>, q: Query<WorkspaceQuery>) -> Response {
    let plans: Value = relay_task_plans_list(&s, q);
    return ok_response(plans);
}

pub async fn get_task_plan(s: State<AppState>, q: Query<WorkspaceQuery>, p: Path<String>) -> Response {
    let plan_id: String = path_inner(&p);
    let plan: Value = relay_task_plan_get(&s, q, &plan_id);
    if value_is_null(&plan) {
        return text_response(format!("{}{}", format!("{}{}", "task_plan '", plan_id), "' not found").as_str(), 404);
    }
    return ok_response(plan);
}

pub async fn create_task_plan(s: State<AppState>, q: Query<WorkspaceQuery>, body: Json<CreateTaskPlanBody>) -> Response {
    let resp: Value = relay_task_plan_register(&s, q, &body.atom);
    if resp_is_err(&resp) {
        return text_response(resp_err_message(&resp), resp_err_code(&resp));
    }
    return ok_response(resp);
}

pub async fn delete_task_plan(s: State<AppState>, q: Query<WorkspaceQuery>, p: Path<String>) -> Response {
    let plan_id: String = path_inner(&p);
    if relay_task_plan_delete(&s, q, &plan_id) {
        return ok_response(DeletedPlanResp { deleted: plan_id.to_string() });
    }
    return text_response(format!("{}{}", format!("{}{}", "cannot remove '", plan_id), "' (not found or built-in)").as_str(), 400);
}

pub async fn start_task_plan_run(s: State<AppState>, q: Query<WorkspaceQuery>, p: Path<String>, body: Json<StartTaskPlanRunBody>) -> Response {
    let plan_id: String = path_inner(&p);
    let resp: Value = relay_task_plan_start(&s, q, &plan_id, &body.initial_input);
    if resp_is_err(&resp) {
        return text_response(resp_err_message(&resp), resp_err_code(&resp));
    }
    if value_is_null(&resp) {
        return text_response(format!("{}{}", format!("{}{}", "task_plan '", plan_id), "' not found").as_str(), 404);
    }
    return ok_response(resp);
}

pub async fn task_plan_events(p: Path<String>) -> Response {
    let instance_id: String = path_inner(&p);
    let sub = relay_bus_subscribe(&instance_id);
    let stream = task_plan_events_stream(sub.clone());
    let mut sse = Sse::new(stream);
    return sse.keep_alive(KeepAlive::new()).into_response();
}

/// GET /api/forge/relay/runs — list all runs (newest first)。
/// useRelay.loadRuns 容忍 {runs:[...]} 或裸数组;extern 返回 {runs:[...]} 包装体。
/// POST /api/forge/relay/runs — start a run(extern 内部 start_run + 合成
/// relay_update 广播,返回 {run_id, state})。
/// GET /api/forge/relay/runs/{run_id} — detailed run state。
/// DELETE /api/forge/relay/runs/{run_id} — delete a run。
/// PATCH /api/forge/relay/runs/{run_id}/title — rename a run。
/// POST /api/forge/relay/runs/{run_id}/advance — kick off the background driver。
/// 已 running 的 run 是 no-op(直接返回 snapshot);extern 负责 is_running 检查
/// + tokio::spawn(drive_run),返回当前 run state。
/// POST /api/forge/relay/runs/{run_id}/handoff — submit a handoff directly。
/// extern 解析 HandoffDocument(400 invalid handoff,纯文本 hw 等价) + submit +
/// publish_advance_result。
/// POST /api/forge/relay/runs/{run_id}/gate — resolve a pending gate。
/// 决策字符串合法性在 .at 校验(hw 400 等价);extern 负责 resolve + publish +
/// ExecuteStep 时 resume driver。
/// POST /api/forge/relay/runs/{run_id}/rerun — rerun from the failed step。
/// GET /api/forge/relay/professions — list professions。
/// GET /api/forge/relay/souls — list souls(empty in P2b.1;soul.rs comes later)。
/// GET /api/forge/relay/flows — list built-in flows。
/// GET /api/forge/relay/task_plans — list all registered TaskPlans。
/// GET /api/forge/relay/task_plans/{id} — one TaskPlan detail。
/// POST /api/forge/relay/task_plans — register a TaskPlan from Atom source。
/// extern 返回 {task_plan_registered,...} 或 {"error":{code:400,message}} 包络;
/// 错误转纯文本 body(与 hw `format!("register failed: {e}")` 等价)。
/// DELETE /api/forge/relay/task_plans/{id} — delete a user TaskPlan
/// (built-ins cannot be removed → 400,hw 等价)。
/// POST /api/forge/relay/task_plans/{id}/runs — start a TaskPlan instance。
/// extern:registry get(404) + engine new/validate(400) + spawn(后台执行)。
/// 400 转纯文本 body(与 hw `format!("plan invalid: {e}")` 等价)。
/// GET /api/forge/relay/task_plans/{instance_id}/events — SSE stream of
/// TaskPlan lifecycle events (reuses the run-event bus)。
fn task_plan_events_stream(sub: RelaySub) -> impl futures::Stream<Item = Result<Event, Infallible>> { async_stream::stream! {{
    loop {
        let msg = relay_sub_recv(&sub).await;
        if msg_is_none(&msg) {
            break;
        } else {
            let ev = msg_unwrap(msg);
            let ev_type: String = value_get_str(&ev, "event_type");
            let payload: Value = value_get(&ev, "payload");
            

            // PLAN-030 试用修复：未命名帧（onmessage 兼容），类型并入 data
            let frame = RunEventFrame { event_type: ev_type.to_string(), payload: payload };
            let event = sse_plain_event(to_value(frame).unwrap());
            yield Ok(event);
        }

    }
} } }

pub fn relay_routes() -> Router<AppState> {
    let mut app = Router::new();
    app = app.route("/api/forge/relay/runs", get(list_runs).post(start_run));
    app = app.route("/api/forge/relay/runs/{run_id}", get(get_run).delete(delete_run));
    app = app.route("/api/forge/relay/runs/{run_id}/title", patch(update_title));
    app = app.route("/api/forge/relay/runs/{run_id}/advance", post(advance_run));
    app = app.route("/api/forge/relay/runs/{run_id}/rerun", post(rerun_run));
    app = app.route("/api/forge/relay/runs/{run_id}/handoff", post(submit_handoff));
    app = app.route("/api/forge/relay/runs/{run_id}/gate", post(resolve_gate));
    app = app.route("/api/forge/relay/runs/{run_id}/events", get(run_events));
    app = app.route("/api/forge/relay/runs/{run_id}/report", get(run_report_html));
    app = app.route("/api/forge/relay/professions", get(list_professions));
    app = app.route("/api/forge/relay/souls", get(list_souls));
    app = app.route("/api/forge/relay/flows", get(list_flows));
    return app;
}

pub fn task_plan_routes() -> Router<AppState> {
    let mut app = Router::new();
    app = app.route("/api/forge/relay/task_plans", get(list_task_plans).post(create_task_plan));
    app = app.route("/api/forge/relay/task_plans/{id}", get(get_task_plan).delete(delete_task_plan));
    app = app.route("/api/forge/relay/task_plans/{id}/runs", post(start_task_plan_run));
    app = app.route("/api/forge/relay/task_plans/{instance_id}/events", get(task_plan_events));
    return app;
}