use super::extern_impl::*;
// Auto-generated by a2r transpiler

use std::sync::Arc;
use crate::server::AppState;
use crate::tool_context::ToolContext;
use crate::mode::AgentMode;
use serde_json::Value;
trait AgentFactory {
    fn build_agent(&self, role_id: &str, handoff: Option<String>) -> Result<Agent, String>;
}


/// relay_driver.at — MuskAgentFactory + AgentFactory impl (relay/driver.rs)
/// + drive_run/drive_loop/run_step (Plan 020 Phase G: 从 server_serve.at 搬入并激活,
/// 依赖 extern 真实化)。async 闘包捕获的 StreamEvent 处理经 DriveSink sink 模式
/// 转给 extern(完整复刻 hw 8 分支 match);advance/handoff/publish 经 extern 委托 hw store。
#[derive(Clone)]
pub struct MuskAgentFactory {
    pub state: Arc<AppState>,
    pub workspace_id: String,
    pub run_id: String,
}

impl MuskAgentFactory {
    pub fn build_agent(&self, role_id: &str, handoff: Option<String>) -> Result<Agent, String> {
        let mode = AgentMode { name: format!("{}{}", "relay-", role_id), description: "".to_string(), role: role_id.to_string(), skills: false, tools: vec![], workflow: None, context_file: "".to_string(), extra_system_prompt: "".to_string() };
        // PLAN-040 T5：工具进度挂 run_id（与 hw relay/driver.rs 同款）。
        let tool_ctx = ToolContext { state: self.state.clone(), workspace_id: self.workspace_id.clone(), parent_conversation_id: self.run_id.clone(), progress: Some(crate::tool_context::ProgressSink::for_run(&self.run_id)) };
        let agent = build_agent_with_context(mode, self.state.client.clone(), Some(tool_ctx));
        match handoff {
            Some(h) => {
                let prior = handoff_render(h);
                if (prior.len() as i32) > 0 {
                    let agent2 = agent_with_history(agent, &prior);
                    return Ok(agent2);
                }
                return Ok(agent);
            },
            None => return Ok(agent),
        }
    }
}

pub async fn drive_run(state: Arc<AppState>, ws_id: &str, run_id: &str) -> Result<bool, String> {
    drive_set_root(&state, ws_id);
    let _ = drive_loop(state.clone(), ws_id, run_id).await;
    // PLAN-034 T9：完成事件在 submit_handoff 内已落库——驱动循环的下一轮
    // advance 对已完成 run 返回 None 直接退出，Completed 分支不可达；此处
    // 按终态判断（completed 才写回；gate/failed 不写）。
    if state.registry.get(ws_id).relay.status(run_id).as_deref() == Some("completed") {
        let ws = state.registry.get(ws_id);
        super::extern_impl::relay_append_report_message_to(&ws, run_id);
    }
    drive_clear_root();
    return Ok(true);
}

async fn drive_loop(state: Arc<AppState>, ws_id: &str, run_id: &str) -> Result<bool, String> {
    let mut done: bool = false;
    while !(done) {
        let result = relay_advance(&state, ws_id, run_id);
        if advance_is_none(&result) {
            done = true;
        } else {
            relay_publish(&state, ws_id, run_id, &result);
            let kind = advance_kind(&result);
            if kind == "execute" {
                let role_id = advance_role_id(&result);
                let step_err = run_step(state.clone(), ws_id, run_id, &role_id).await;
                if step_err_is_err(&step_err) {
                    // PLAN-030 试用修复：置败并停车，不级联后续相位
                    relay_submit_error(&state, ws_id, run_id, &role_id, &step_err);
                    done = true;
                }
            } else {
                // PLAN-067 T-04(a)/T-05：human gate——①镜像 gate_waiting 到
                // 发起会话的 chat 流（总线桥按 run_id==session_id 过滤,此前
                // 该事件无生产者,审批卡永不出现）;②会话审批模式 = auto 时
                // 即刻放行（store.resolve_gate 落 GateResolved 审计）并继续
                // 驱动,实现无人干预跑通;human（缺省）停车等 POST /gate。
                let mut handled = false;
                if kind == "wait" {
                    let ws = state.registry.get(ws_id);
                    if let Some(chat_sid) = ws.relay.context_var(run_id, "chat_session_id") {
                        if !chat_sid.is_empty() {
                            crate::relay::api::publish_task_plan_event(
                                &chat_sid,
                                "relay_gate_waiting",
                                serde_json::json!({ "run_id": run_id, "step_id": run_id }),
                            );
                        }
                    }
                    if ws.relay.context_var(run_id, "approval_mode").as_deref() == Some("auto") {
                        if let Some((res2, _st2)) = ws.relay.resolve_gate(run_id, crate::relay::GateDecision::Approve) {
                            let mut kind2 = String::new();
                            let mut role2 = String::new();
                            match &res2 {
                                crate::relay::AdvanceResult::ExecuteStep { role_id, .. } => {
                                    kind2 = "execute".into();
                                    role2 = role_id.clone();
                                }
                                crate::relay::AdvanceResult::Completed => { kind2 = "completed".into(); }
                                _ => {}
                            }
                            if kind2 == "execute" {
                                let step_err = run_step(state.clone(), ws_id, run_id, &role2).await;
                                if step_err_is_err(&step_err) {
                                    relay_submit_error(&state, ws_id, run_id, &role2, &step_err);
                                }
                                handled = true;
                            } else if kind2 == "completed" {
                                let ws = state.registry.get(ws_id);
                                super::extern_impl::relay_append_report_message_to(&ws, run_id);
                                handled = true;
                            }
                        }
                    }
                }
                if kind == "completed" {
                    let ws = state.registry.get(ws_id);
                    super::extern_impl::relay_append_report_message_to(&ws, run_id);
                }
                if !handled {
                    done = true;
                }
            }
        }

    }
    return Ok(true);
}

async fn run_step(state: Arc<AppState>, ws_id: &str, run_id: &str, role_id: &str) -> Result<String, String> {
    let task_input = relay_step_context(&state, ws_id, run_id);
    let agent = factory_build_agent(&state, ws_id, run_id, role_id).await;
    let sink = DriveStreamSink { state: state.clone(), ws_id: ws_id.to_string(), run_id: run_id.to_string(), role_id: role_id.to_string() };
    let cancel = atomic_bool_false();
    let result = agent_run_stream_with_sink(agent, task_input, Arc::new(sink), cancel).await;
    match result {
        Ok(r) => {
            let output = drive_accumulated(&state, ws_id, run_id);
            let final_output = drive_finalize_output(&output, &r);
            drive_submit_handoff(&state, ws_id, run_id, role_id, &final_output, &r);
            return Ok(final_output);
        },
        Err(e) => return Err(e),
    }
}

pub trait DriveSink {
    fn on_event(&self, ev: Value);
}


#[derive(Clone)]
pub struct DriveStreamSink {
    pub state: Arc<AppState>,
    pub ws_id: String,
    pub run_id: String,
    pub role_id: String,
}

impl DriveSink for DriveStreamSink {
    fn on_event(&self, ev: Value) {
        drive_handle_stream_event(&self.state, &self.ws_id, &self.run_id, &self.role_id, ev);
    }
}