use super::extern_impl::*;
// Auto-generated by a2r transpiler

use serde::{Serialize, Deserialize};
use std::collections::HashMap;
use std::time::{SystemTime, Duration};
use serde_json::Value;
/// relay_store.at — ported from backend/crates/musk/src/relay/store.rs.
/// 
/// Run store data model. Strategy (plan 014 mixed):
/// - RunEvent (hetero enum, 15 variants) + RunSummary + StepState + GateState
/// + RunMetadata + StartRunRequest + StartRunStep -> Auto
/// - RunState / RunEntry (contain upstream types crate::relay::{StepRecord,
/// PipelineEngine}) -> hand-written Rust (those are auto_ai_agent types
/// that can't be re-declared as plain data)
/// - RunStore (Mutex<HashMap> + disk persistence) -> hand-written Rust (Mutex)
/// 
/// Cross-module: GateType re-declared as scalar enum (real one in
/// crate::relay, from auto_ai_agent::orchestration).
fn now_secs() -> u64 {
    let now = SystemTime::now();
    let elapsed = now.elapsed().unwrap();
    return elapsed.as_secs();
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GateType {
    Auto = 1,
    Human = 2,
}

impl std::fmt::Display for GateType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            GateType::Auto => write!(f, "Auto"),
            GateType::Human => write!(f, "Human"),
        }
    }
}
impl GateType {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Auto" | "auto" => GateType::Auto,
            "Human" | "human" => GateType::Human,
            _ => GateType::Auto
        }
    }
}

/// A run event for SSE streaming + history replay. Tagged so the frontend's
/// event_type switch maps 1:1.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum RunEvent {
    StepStarted { timestamp: u64, step_id: String, role_id: String },
    StepCompleted { timestamp: u64, step_id: String, handoff_summary: String },
    GateWaiting { timestamp: u64, step_id: String, gate: String },
    GateResolved { timestamp: u64, step_id: String, decision: String },
    // PLAN-031 T5: report payload (hw store::RunReportPayload — wire parity
    // with the handwritten enum; #[serde(default)] keeps old events loadable).
    RunCompleted { timestamp: u64, #[serde(default)] report: crate::relay::store::RunReportPayload },
    // PLAN-032 手补：ReportEmitted 与 hw 枚举 wire parity（crate::relay::store
    // 同款；.at 无法表达外部类型，重生成后需手工补回——parity 测试编译期拦截）。
    ReportEmitted { timestamp: u64, #[serde(default)] format: String, #[serde(default)] title: String, #[serde(default)] path: String },
    RunFailed { timestamp: u64, error: String },
    TokenSpend { timestamp: u64, cumulative: u64, step_tokens: u64 },
    RelayUpdate { timestamp: u64, step_id: String, role_id: String, status: String },
    TurnDelta { timestamp: u64, role_id: String, text: String },
    TurnToolCall { timestamp: u64, role_id: String, tool_id: String, tool_name: String, arguments: Value },
    TurnToolResult { timestamp: u64, role_id: String, tool_id: String, result: String },
    TurnComplete { timestamp: u64, role_id: String },
    TurnError { timestamp: u64, role_id: String, message: String },
    TurnBudgetWarning { timestamp: u64, role_id: String, remaining: u64 },
    TurnBudgetExceeded { timestamp: u64, role_id: String },
    // PLAN-040 手补：ToolUpdate 与 hw 枚举 wire parity（crate::relay::store
    // 同款；重生成后需手工补回——parity 测试编译期拦截）。
    ToolUpdate {
        timestamp: u64,
        #[serde(default)] run_id: String,
        #[serde(default)] tool_call_id: String,
        #[serde(default)] tool_name: String,
        #[serde(default)] partial: String,
    },
}


impl RunEvent {
    pub fn event_type(&self) -> String {
        match self {
            RunEvent::StepStarted { .. } => return "step_started".to_string(),
            RunEvent::StepCompleted { .. } => return "step_completed".to_string(),
            RunEvent::GateWaiting { .. } => return "gate_waiting".to_string(),
            RunEvent::GateResolved { .. } => return "gate_resolved".to_string(),
            RunEvent::RunCompleted { .. } => return "run_completed".to_string(),
            RunEvent::ReportEmitted { .. } => return "report_emitted".to_string(),
            RunEvent::RunFailed { .. } => return "run_failed".to_string(),
            RunEvent::TokenSpend { .. } => return "token_spend".to_string(),
            RunEvent::RelayUpdate { .. } => return "relay_update".to_string(),
            RunEvent::TurnDelta { .. } => return "turn_delta".to_string(),
            RunEvent::TurnToolCall { .. } => return "turn_tool_call".to_string(),
            RunEvent::TurnToolResult { .. } => return "turn_tool_result".to_string(),
            RunEvent::TurnComplete { .. } => return "turn_complete".to_string(),
            RunEvent::TurnError { .. } => return "turn_error".to_string(),
            RunEvent::TurnBudgetWarning { .. } => return "turn_budget_warning".to_string(),
            RunEvent::TurnBudgetExceeded { .. } => return "turn_budget_exceeded".to_string(),
            RunEvent::ToolUpdate { .. } => return "tool_update".to_string(),
        }
    }
}

/// Snake-case event_type the frontend switches on.
/// (a2r tag-union is-match generates match Variant{..} arms.)
/// The timestamp carried by every variant.
/// NOTE: a2r misparses named-field tag-union destructuring
/// (`Variant(e)` binds e to the first field and omits `..`, E0027). The
/// original timestamp() stays hand-written in relay/store.rs; event_type()
/// above (no destructuring) ports cleanly.
/// Lightweight summary for list views.
#[derive(Clone, Debug, Serialize)]
pub struct RunSummary {
    pub run_id: String,
    pub status: String,
    pub current_step: u32,
    pub total_steps: u32,
    pub current_profession: Option<String>,
    pub cumulative_tokens: u64,
    pub created_at: u64,
    pub updated_at: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub task: Option<String>,
}

/// One step's state in a run.
#[derive(Clone, Debug, Serialize)]
pub struct StepState {
    pub id: String,
    pub role_id: String,
    pub status: String,
    pub gate: String,
}

/// A gate waiting for resolution.
#[derive(Clone, Debug, Serialize)]
pub struct GateState {
    pub step_id: String,
    pub role_id: String,
    pub since: u64,
}

/// Run metadata (title/task/origin/workspace + TaskPlan tracing)。对齐 hw
/// store.rs 全字段(wire parity;hw 各字段 #[serde(default)] 对 Option 冗余,
/// a2r Option 默认 None 等价)。
#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub struct RunMetadata {
    pub title: Option<String>,
    pub initial_task: Option<String>,
    pub originating_chat_session: Option<String>,
    pub workspace_id: Option<String>,
    // PLAN-032 手补：汇报报告元数据（crate::relay::store::ReportMeta；.at 无法
    // 表达外部类型，重生成后需手工补回——parity 编译期拦截）。
    #[serde(default)]
    pub report: Option<crate::relay::store::ReportMeta>,
    pub task_plan_id: Option<String>,
    pub task_run_name: Option<String>,
    pub phase_name: Option<String>,
    pub phase_index: Option<u32>,
    pub parent_run_id: Option<String>,
    pub root_run_id: Option<String>,
}

/// Request body for POST /api/forge/relay/runs.
/// `steps` 带 #[serde(default)] 对齐 hw store.rs:212(缺省请求体可省略 steps)。
#[derive(Clone, Debug, Deserialize)]
pub struct StartRunRequest {
    pub run_id: Option<String>,
    pub flow_id: Option<String>,
    #[serde(default)]
    pub steps: Vec<StartRunStep>,
    pub task: Option<String>,
}

#[derive(Clone, Debug, Deserialize)]
pub struct StartRunStep {
    pub id: String,
    pub role_id: String,
    pub gate: Option<GateType>,
}