use crate::auto_generated::extern_impl::*;
// Auto-generated by a2r transpiler

use serde::{Serialize, Deserialize};
use serde_json::Value;
/// relay_api.at — ported from backend/crates/musk/src/relay/api.rs (DTO layer).
/// 
/// Relay REST API DTOs. Strategy (plan 014 mixed):
/// - 5 DTO structs (L34-86) -> Auto (pure Deserialize data)
/// - bus() (OnceLock + broadcast) + publish() + all handlers (async + extractor
/// + impl Trait Sse) + relay_routes() -> hand-written Rust (a2r blind spots)
/// An event on the relay broadcast bus (the SSE payload).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct BusEvent {
    pub run_id: String,
    pub event_type: String,
    pub payload: Value,
}

#[derive(Debug, Deserialize)]
pub struct ResolveGateBody {
    pub decision: String,
    pub feedback: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct SubmitHandoffBody {
    pub handoff: Value,
}

#[derive(Debug, Deserialize)]
pub struct UpdateTitleBody {
    pub title: String,
}

#[derive(Debug, Deserialize)]
pub struct ListRunsQuery {
    pub project_path: Option<String>,
}
