use super::extern_impl::*;
// Auto-generated by a2r transpiler

use serde::{Serialize, Deserialize};
use std::collections::HashMap;
use std::path::PathBuf;
/// relay_profession.at — ported from backend/crates/musk/src/relay/profession.rs.
/// 
/// Profession registry — app-layer orchestration metadata (P2a). Strategy
/// (plan 014 mixed):
/// - Profession struct + ForgePhase enum + as_str + ProfessionRegistry logic
/// -> Auto (List not HashMap, per a2r-10)
/// - default_professions (292 lines of hardcoded Profession data) + config_dir
/// (dirs crate) + save_professions IO -> hand-written Rust (bulk data +
/// dirs crate API)
/// 
/// Cross-module: crate::specs::SectionType re-declared as a scalar enum here
/// (the real one lives in specs.at/specs.rs; only the variant set matters for
/// serialization).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum SectionType {
    Goals = 1,
    Architecture = 2,
    Designs = 3,
    Tests = 5,
    Reviews = 6,
    Reports = 7,
}

impl std::fmt::Display for SectionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            SectionType::Goals => write!(f, "Goals"),
            SectionType::Architecture => write!(f, "Architecture"),
            SectionType::Designs => write!(f, "Designs"),
            SectionType::Tests => write!(f, "Tests"),
            SectionType::Reviews => write!(f, "Reviews"),
            SectionType::Reports => write!(f, "Reports"),
        }
    }
}
impl SectionType {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Goals" | "goals" => SectionType::Goals,
            "Architecture" | "architecture" => SectionType::Architecture,
            "Designs" | "designs" => SectionType::Designs,
            "Tests" | "tests" => SectionType::Tests,
            "Reviews" | "reviews" => SectionType::Reviews,
            "Reports" | "reports" => SectionType::Reports,
            _ => SectionType::Goals
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ForgePhase {
    Intake = 1,
    Discovery = 2,
    GoalGate = 3,
    Design = 4,
    Planning = 5,
    Execution = 6,
    Verification = 7,
    Report = 8,
    Errand = 9,
}

impl std::fmt::Display for ForgePhase {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            ForgePhase::Intake => write!(f, "Intake"),
            ForgePhase::Discovery => write!(f, "Discovery"),
            ForgePhase::GoalGate => write!(f, "GoalGate"),
            ForgePhase::Design => write!(f, "Design"),
            ForgePhase::Planning => write!(f, "Planning"),
            ForgePhase::Execution => write!(f, "Execution"),
            ForgePhase::Verification => write!(f, "Verification"),
            ForgePhase::Report => write!(f, "Report"),
            ForgePhase::Errand => write!(f, "Errand"),
        }
    }
}
impl ForgePhase {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Intake" | "intake" => ForgePhase::Intake,
            "Discovery" | "discovery" => ForgePhase::Discovery,
            "GoalGate" | "goalgate" => ForgePhase::GoalGate,
            "Design" | "design" => ForgePhase::Design,
            "Planning" | "planning" => ForgePhase::Planning,
            "Execution" | "execution" => ForgePhase::Execution,
            "Verification" | "verification" => ForgePhase::Verification,
            "Report" | "report" => ForgePhase::Report,
            "Errand" | "errand" => ForgePhase::Errand,
            _ => ForgePhase::Intake
        }
    }
}

impl ForgePhase {
    pub fn as_str(&self) -> String {
        match self {
            ForgePhase::Intake => return "intake".to_string(),
            ForgePhase::Discovery => return "discovery".to_string(),
            ForgePhase::GoalGate => return "goal_gate".to_string(),
            ForgePhase::Design => return "design".to_string(),
            ForgePhase::Planning => return "planning".to_string(),
            ForgePhase::Execution => return "execution".to_string(),
            ForgePhase::Verification => return "verification".to_string(),
            ForgePhase::Report => return "report".to_string(),
            ForgePhase::Errand => return "errand".to_string(),
        };
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Profession {
    pub id: String,
    pub name: String,
    pub phase: ForgePhase,
    pub owned_sections: Vec<SectionType>,
    pub readable_sections: Vec<SectionType>,
    pub allowed_tools: Vec<String>,
    pub handoff_to: Vec<String>,
    pub dispatchable_to: Vec<String>,
    pub approval_gates: Vec<String>,
    pub max_turns: u32,
    pub token_budget: u64,
}

/// Registry of professions. Stored as List (a2r-10: HashMap<_,struct> method
/// calls mishandled); linear lookup, profession counts are small.
#[derive(Clone, Debug)]
pub struct ProfessionRegistry {
    pub professions: Vec<Profession>,
}

impl ProfessionRegistry {
    pub fn get(&self, id: &str) -> Option<Profession> {
        for p in self.professions.clone() {
            if p.id == id {
                return Some(p);
            }
        }
        return None;
    }
    pub fn list(&self) -> Vec<Profession> {
        let mut result: Vec<Profession> = self.professions.clone();



        return result;
    }
    pub fn can_handoff(&self, from_id: &str, to_id: &str) -> bool {
        for p in self.professions.clone() {
            if p.id == from_id {
                for h in p.handoff_to.clone() {
                    if h == to_id {
                        return true;
                    }
                }
                return false;
            }
        }
        return false;
    }
    pub fn needs_approval(&self, from_id: &str, to_id: &str) -> bool {
        for p in self.professions.clone() {
            if p.id == from_id {
                for g in p.approval_gates.clone() {
                    if g == to_id {
                        return true;
                    }
                }
                return false;
            }
        }
        return false;
    }
    pub fn register(&mut self, p: Profession) {
        let mut new_list: Vec<Profession> = vec![];
        let mut found: bool = false;
        for existing in self.professions.clone() {
            if existing.id == p.id {
                found = true;
                new_list.push(p.clone())
            } else {
                new_list.push(existing.clone())
            }

        }
        if found == false {
            new_list.push(p.clone());
        }
        self.professions = new_list;
    }
}