use super::extern_impl::*;
// Auto-generated by a2r transpiler

use axum::Router;
use axum::routing::{get};
use axum::response::Response;
use axum::Json;
use std::sync::Arc;
use std::path::PathBuf;
use serde::{Serialize};
use serde_json::Value;
#[derive(Serialize)]
pub struct SettingsLinkOk {
    pub status: String,
    pub url: String,
}

#[derive(Serialize)]
pub struct SettingsLinkErr {
    pub status: String,
    pub error: String,
}

async fn serve(addr: &str, client: Arc<dyn Client>) -> Result<String, String> {
    let state = serve_init_state(client);
    let static_service = serve_build_static();
    let cors = serve_build_cors();
    let app = serve_build_app(state, static_service, cors);
    serve_listen(addr, app).await;
    return Ok("");
}

async fn settings_link() -> Response {
    let cfg = app_config_load();
    let daemon_url = app_config_effective_daemon_url(cfg);
    let ensure_url: String = format!("{}{}", daemon_url, "/v1/services/os-config/ensure");
    let result = http_post_json(ensure_url.as_str()).await;
    match result {
        Ok(val) => {
            let status = value_get_str(val, "status");
            let url = value_get_str(val, "url");
            if status == "running" {
                if (url.len() as i32) > 0 {
                    return json_response(SettingsLinkOk { status: "running".to_string(), url: url.to_string() });
                }            }
            let error_val = value_get_str(val, "error");
            return error_response(500, SettingsLinkErr { status: "error".to_string(), error: error_val.to_string() });
        },
        Err(e) => return error_response(502, SettingsLinkErr { status: "error".to_string(), error: e.to_string() }),
    };
}

async fn drive_run(state: Arc<AppState>, ws_id: &str, run_id: &str) -> () {
    drive_set_root(ws_id);
    drive_loop(state.clone(), ws_id, run_id).await;
    drive_clear_root()
}

async fn drive_loop(state: Arc<AppState>, ws_id: &str, run_id: &str) -> () {
    loop {
        let result = relay_advance(ws_id, run_id);
        if advance_is_none(result) {
            return None;
        }
        relay_publish(run_id, result);
        match advance_kind(result).as_str() {
            "execute" => {
                let role_id = advance_role_id(result);
                let step_err = run_step(state.clone(), ws_id, run_id, role_id.as_str()).await;
                if step_err_is_err(step_err) {
                    relay_submit_error(run_id, role_id, step_err);
                }
            },
            "wait" => return None,
            "completed" => return None,
            "failed" => return None,
            "paused" => return None,
        };
    }
}

async fn run_step(state: Arc<AppState>, ws_id: &str, run_id: &str, role_id: &str) -> Result<String, String> {
    let task_input = relay_step_context(ws_id, run_id);
    let agent = factory_build_agent(state, ws_id, run_id, role_id).await;
    let sink = DriveStreamSink { ws_id: ws_id.to_string(), run_id: run_id.to_string(), role_id: role_id.to_string() };
    let cancel = atomic_bool_false();
    let result = agent_run_stream_with_sink(agent, task_input, Arc::new(sink), cancel).await;
    match result {
        Ok(r) => {
            let output = drive_accumulated(ws_id, run_id);
            let final_output = drive_finalize_output(output, r);
            drive_submit_handoff(ws_id, run_id, role_id, final_output, r);
            return Ok(final_output);
        },
        Err(e) => return Err(e),
    };
}

trait DriveSink {
    fn on_event(&self, self: i32, ev: i32);
}


#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct DriveStreamSink {
    pub ws_id: String,
    pub run_id: String,
    pub role_id: String,
}

impl DriveSink for DriveStreamSink {
    fn on_event(&self, ev: i32) {

        drive_handle_stream_event(self.ws_id.clone(), self.run_id.clone(), self.role_id.clone(), ev);
    }
}
