use crate::auto_generated::extern_impl::*;
// Auto-generated by a2r transpiler

use axum::Json;
use axum::http::StatusCode;
use axum::response::Response;
use axum::response::sse::{Event, KeepAlive, Sse};
use std::sync::Arc;
use std::convert::Infallible;
use std::collections::HashMap;
use serde::{Serialize, Deserialize};
use serde_json::Value;
use crate::server::AppState;
use axum::extract::{State};


use crate::tools::{ReadFile, WriteFile, RunCommand};
/// server_stream.at — daemon/SSE handler (server.rs 的 🔴→🟡 部分).
/// 
/// 之前判为 🔴 的 6 个 daemon/SSE handler，经 Plan 380 P1-dyn(Arc<dyn T>) +
/// Plan 321(async_stream ~Stream+yield) 后重新评估为可移植。本文件移植它们。
/// 
/// 流式 handler 的 dyn Fn 闭包 → named sink struct（Arc<dyn StreamSink>，P1-dyn）。
/// json!() 宏 → DTO。impl IntoResponse → concrete Response/Result。
#[derive(Debug, Deserialize)]
pub struct WorkflowRunRequest {
    pub task: String,
    pub workflow: String,
}

#[derive(Debug, Serialize)]
pub struct WorkflowRunResponse {
    pub steps: HashMap<String, String>,
    pub outputs: HashMap<String, String>,
}

#[derive(Debug, Serialize)]
pub enum WorkflowEventDto {
    StepStart { step_id: String, role: String, input: String },
    StepDone { step_id: String, output: String },
    StepSkipped { step_id: String },
    Finished { steps: HashMap<String, String>, outputs: HashMap<String, String> },
}


#[derive(Debug, Serialize)]
pub enum SseEventDto {
    Delta { text: String },
    ToolStart { tool: String, args: String },
    Tool { tool: String, args: String, result: String },
    Warning { text: String },
    Done { output: String, turns: i32, tool_calls: Vec<ToolCallOut> },
    Cancelled,
    Error { message: String },
}


#[derive(Debug, Serialize)]
pub struct ToolCallOut {
    pub tool: String,
    pub args: String,
    pub result: String,
}

#[derive(Debug, Deserialize)]
pub struct WorkspaceQuery {
    pub workspace: Option<String>,
}

#[derive(Clone)]
pub struct Channel {
    pub tx: Value,
    pub rx: Value,
}

fn shared_tools() -> Vec<Arc<dyn Tool>> {
    let mut tools: Vec<Arc<dyn Tool>> = vec![];
    tools.push(Arc::new(ReadFile {}));
    tools.push(Arc::new(WriteFile {}));
    tools.push(Arc::new(RunCommand {}));
    return tools;
}

fn workflow_event_to_dto(ev: i32) -> WorkflowEventDto {
    return workflow_event_map(ev);
}

async fn workflow_run(s: State<AppState>, q: Query<WorkspaceQuery>, body: Json<WorkflowRunRequest>) -> Json<WorkflowRunResponse> {
    let resp = wf_run(s, q, body).await;
    return Json(resp);
}

async fn workflow_run_stream(s: State<AppState>, q: Query<WorkspaceQuery>, body: Json<WorkflowRunRequest>) -> Response {
    let ch = mpsc_channel();
    let tx = ch.tx.clone();
    let rx = ch.rx.clone();
    let sink = WorkflowStreamSink { tx: tx };
    wf_run_with_progress(s, q, body, Arc::new(sink)).await;
    let stream = workflow_sse_stream(rx);
    let mut sse = Sse::new(stream);
    let mut ka = KeepAlive::new();
    ka = ka.interval_secs(15);
    return sse::keep_alive(ka).into_response();
}

fn workflow_sse_stream(rx: i32) -> impl futures::Stream<Item = Result<Event, Infallible>> { async_stream::stream! {{
    loop {
        let msg = mpsc_recv(rx).await;
        if msg_is_none(msg) {
            

        } else {
            let dto = workflow_event_to_dto(msg);
            let event = Event::default().event("workflow").json_data(dto);
            yield Ok(event)
        }

    }
} } }

trait StreamSink {
    fn on_event(&self, ev: i32);
}


#[derive(Clone, Debug, PartialEq)]
struct WorkflowStreamSink {
    pub tx: Value,
}

impl StreamSink for WorkflowStreamSink {
    fn on_event(&self, ev: i32) {
        let dto = workflow_event_to_dto(ev);
        mpsc_try_send(self.tx.clone(), dto);
    }
}

async fn run_stream_handler(s: State<AppState>, q: Query<WorkspaceQuery>, body: Json<RunRequest>) -> Response {
    let ch = mpsc_channel();
    let tx = ch.tx.clone();
    let rx = ch.rx.clone();
    let sink = RunStreamSink { tx: tx };
    agent_run_stream(s, q, body, Arc::new(sink)).await;
    let stream = run_sse_stream(rx);
    let mut sse = Sse::new(stream);
    let mut ka = KeepAlive::new();
    ka = ka.interval_secs(15);
    return sse::keep_alive(ka).into_response();
}

fn run_sse_stream(rx: i32) -> impl futures::Stream<Item = Result<Event, Infallible>> { async_stream::stream! {{
    loop {
        let msg = mpsc_recv(rx).await;
        if msg_is_none(msg) {
            

        } else {
            let dto = stream_event_to_dto(msg);
            let event = Event::default().event("run").json_data(dto);
            yield Ok(event)
        }

    }
} } }

#[derive(Clone, Debug, PartialEq)]
struct RunStreamSink {
    pub tx: Value,
}

impl StreamSink for RunStreamSink {
    fn on_event(&self, ev: i32) {
        let dto = stream_event_to_dto(ev);
        mpsc_try_send(self.tx.clone(), dto);
    }
}

fn stream_event_to_dto(ev: i32) -> SseEventDto {
    return stream_event_map(ev);
}

#[derive(Debug, Deserialize)]
pub struct RunRequest {
    pub task: String,
    pub mode: Option<String>,
}

async fn conversation_stream(s: State<AppState>, p: Path<String>, q: Query<WorkspaceQuery>) -> Response {
    let rx = conversations_subscribe(s, q);
    let id = path_inner(p);
    let stream = conv_event_stream(rx, id.as_str());
    let mut sse = Sse::new(stream);
    let mut ka = KeepAlive::new();
    ka = ka.interval_secs(15);
    return sse::keep_alive(ka).into_response();
}

fn conv_event_stream(rx: i32, id: &str) -> impl futures::Stream<Item = Result<Event, Infallible>> { async_stream::stream! {{
    loop {
        let msg = broadcast_recv(rx).await;
        if msg_is_none(msg) {
            

        } else {
            let ev = msg_unwrap(msg);
            if conv_event_matches(ev, id) {
                let dto = ConvEventDto { conversation_id: conv_event_id(ev).to_string(), turn: conv_event_turn(ev), status: conv_event_status(ev) };
                let event = Event::default().event("conversation_event").json_data(dto);
                yield Ok(event)
            }        }

    }
} } }

#[derive(Debug, Serialize)]
pub struct ConvEventDto {
    pub conversation_id: String,
    pub turn: Option<String>,
    pub status: Option<String>,
}

async fn run(s: State<AppState>, q: Query<WorkspaceQuery>, body: Json<RunRequest>) -> Json<RunResponse> {
    let resp = agent_run(s, q, body).await;
    return Json(resp);
}

#[derive(Debug, Serialize)]
pub struct RunResponse {
    pub output: String,
    pub tool_calls: Vec<ToolCallOut>,
}

async fn chat_stream(s: State<AppState>, p: Path<String>, q: Query<WorkspaceQuery>) -> Response {
    let ch = mpsc_channel();
    let tx = ch.tx.clone();
    let rx = ch.rx.clone();
    let sink = ChatStreamSink { tx: tx };
    chat_run_stream(s, q, p, Arc::new(sink)).await;
    let stream = chat_sse_stream(rx);
    let mut sse = Sse::new(stream);
    let mut ka = KeepAlive::new();
    ka = ka.interval_secs(15);
    return sse::keep_alive(ka).into_response();
}

fn chat_sse_stream(rx: i32) -> impl futures::Stream<Item = Result<Event, Infallible>> { async_stream::stream! {{
    loop {
        let msg = mpsc_recv(rx).await;
        if msg_is_none(msg) {
            

        } else {
            let dto = stream_event_to_dto(msg);
            let event = Event::default().event("chat").json_data(dto);
            yield Ok(event)
        }

    }
} } }

#[derive(Clone, Debug, PartialEq)]
struct ChatStreamSink {
    pub tx: Value,
}

impl StreamSink for ChatStreamSink {
    fn on_event(&self, ev: i32) {
        let dto = stream_event_to_dto(ev);
        mpsc_try_send(self.tx.clone(), dto);
    }
}
