use super::extern_impl::*;
// Auto-generated by a2r transpiler

use axum::extract::{Query, Path, State};
use axum::Json;
use axum::http::StatusCode;
use axum::response::{Response, IntoResponse};
use axum::response::sse::{Event, KeepAlive, Sse};
use std::sync::Arc;
use std::convert::Infallible;
use std::collections::HashMap;
use serde::{Serialize, Deserialize};
use serde_json::Value;
use serde_json::to_value;
use crate::server::AppState;
use crate::tools::{ReadFile, WriteFile, RunCommand};
/// server_stream.at — daemon/SSE handler (server.rs 的 🔴→🟡 部分).
/// 
/// 之前判为 🔴 的 6 个 daemon/SSE handler，经 Plan 380 P1-dyn(Arc<dyn T>) +
/// Plan 321(async_stream ~Stream+yield) 后重新评估为可移植。本文件移植它们。
/// 
/// Plan 019 Phase 2-4:流式 handler 的 mpsc channel 由 extern side-table
/// 持有,handler 直接传递 tx 句柄给 extern(不再经 named sink struct 中转,
/// 便于 extern 在 run 结束后关闭 channel 让 SSE 流自然终止)。所有 SSE 流的
/// while 循环在 channel 关闭(None)时 break——与 hw 的
/// `while let Some(v) = rx.recv().await` 终止语义一致(前端靠 onerror 收尾)。
/// run/workflow_run 两个非流式 handler 改用 ~Response + 错误包络(经
/// resp_is_err/resp_err_message/resp_err_code),补齐 hw 的 400/500 状态码。
/// json!() 宏 → DTO。impl IntoResponse → concrete Response/Result。
#[derive(Debug, Deserialize)]
pub struct WorkflowRunRequest {
    pub task: String,
    pub workflow: String,
}

#[derive(Debug, Serialize)]
pub struct WorkflowRunResponse {
    pub steps: HashMap<String, String>,
    pub outputs: HashMap<String, String>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum WorkflowEventDto {
    StepStart { step_id: String, role: String, input: String },
    StepDone { step_id: String, output: String },
    StepSkipped { step_id: String },
    Finished { steps: HashMap<String, String>, outputs: HashMap<String, String> },
}


#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SseEventDto {
    Delta { text: String },
    Thinking { thinking: String },
    ToolCall { id: Option<String>, name: String, arguments: Value },
    ToolResult { id: Option<String>, name: String, arguments: Value, result: String, status: String },
    Warning { text: String },
    Done { output: String, turns: i32, tool_calls: Vec<ToolCallOut> },
    Cancelled { output: String, turns: i32, tool_calls: Vec<ToolCallOut> },
    Error { message: String },
}


#[derive(Debug, Serialize, Deserialize)]
pub struct ToolCallOut {
    pub name: String,
    pub arguments: Value,
    pub result: String,
}

#[derive(Debug, Deserialize)]
pub struct WorkspaceQuery {
    pub workspace: Option<String>,
}

#[derive(Clone)]
pub struct Channel {
    pub tx: Value,
    pub rx: Value,
}

fn shared_tools() -> Vec<Arc<dyn Tool>> {
    let mut tools: Vec<Arc<dyn Tool>> = vec![];
    tools.push(Arc::new(ReadFile {}));
    tools.push(Arc::new(WriteFile {}));
    tools.push(Arc::new(RunCommand {}));
    return tools;
}

fn workflow_event_to_dto(ev: Option<Value>) -> WorkflowEventDto {
    return workflow_event_map(ev);
}

pub async fn workflow_run(s: State<AppState>, q: Query<WorkspaceQuery>, body: Json<WorkflowRunRequest>) -> Response {
    let resp = wf_run(&s, q, body).await;
    if resp_is_err(&resp) {
        return err_response(resp_err_message(&resp), resp_err_code(&resp));
    }
    return ok_response(resp);
}

pub async fn workflow_run_stream(s: State<AppState>, q: Query<WorkspaceQuery>, body: Json<WorkflowRunRequest>) -> Response {


    let check = workflow_exists(&body.workflow);
    if resp_is_err(&check) {
        return err_response(resp_err_message(&check), resp_err_code(&check));
    }
    let ch = mpsc_channel();
    let tx = mpsc_sender(&ch);
    let rx = mpsc_receiver(&ch);
    wf_run_with_progress(&s, q, body, tx).await;
    let stream = workflow_sse_stream(rx.clone());
    let mut sse = Sse::new(stream);
    return sse.keep_alive(KeepAlive::new()).into_response();
}

fn workflow_sse_stream(rx: Value) -> impl futures::Stream<Item = Result<Event, Infallible>> { async_stream::stream! {{
    loop {
        let msg = mpsc_recv(&rx).await;
        if msg_is_none(&msg) {
            

            break;
        } else {
            let dto = workflow_event_to_dto(msg.clone());
            let event = sse_event("workflow", to_value(dto).unwrap());
            yield Ok(event);
        }

    }
} } }

pub async fn run_stream_handler(s: State<AppState>, q: Query<WorkspaceQuery>, body: Json<RunRequest>) -> Response {



    let mode_name = body.mode.clone().unwrap_or("superpowers".to_string());
    let check = mode_exists(&mode_name);
    if resp_is_err(&check) {
        return err_response(resp_err_message(&check), resp_err_code(&check));
    }
    let ch = mpsc_channel();
    let tx = mpsc_sender(&ch);
    let rx = mpsc_receiver(&ch);
    agent_run_stream(&s, q, body, tx).await;
    let stream = run_sse_stream(rx.clone());
    let mut sse = Sse::new(stream);
    return sse.keep_alive(KeepAlive::new()).into_response();
}

fn run_sse_stream(rx: Value) -> impl futures::Stream<Item = Result<Event, Infallible>> { async_stream::stream! {{
    loop {
        let msg = mpsc_recv(&rx).await;
        if msg_is_none(&msg) {
            

            break;
        } else {
            let dto = stream_event_to_dto(msg.clone());
            let event = sse_event("run", to_value(dto).unwrap());
            yield Ok(event);
        }

    }
} } }

fn stream_event_to_dto(ev: Option<Value>) -> SseEventDto {
    return stream_event_map(ev);
}

#[derive(Debug, Deserialize)]
pub struct RunRequest {
    pub task: String,
    pub mode: Option<String>,
}

pub async fn conversation_stream(s: State<AppState>, p: Path<String>, q: Query<WorkspaceQuery>) -> Response {
    let rx = conversations_subscribe(&s, q);
    let id = path_inner(&p);
    let stream = conv_event_stream(rx, id);
    let mut sse = Sse::new(stream);
    return sse.keep_alive(KeepAlive::new()).into_response();
}

fn conv_event_stream(rx: Value, id: String) -> impl futures::Stream<Item = Result<Event, Infallible>> { async_stream::stream! {{
    loop {
        let msg = broadcast_recv(&rx).await;
        if msg_is_none(&msg) {
            

            break;
        } else {
            let ev = msg_unwrap(msg);
            if conv_event_matches(&ev, &id) {
                let dto = ConvEventDto { conversation_id: conv_event_id(&ev).to_string(), turn: conv_event_turn(&ev), status: conv_event_status(&ev) };
                let event = sse_event("conversation_event", to_value(dto).unwrap());
                yield Ok(event);
            }        }

    }
} } }

#[derive(Debug, Serialize)]
pub struct ConvEventDto {
    pub conversation_id: String,
    pub turn: Option<Value>,
    pub status: Option<String>,
}

pub async fn run(s: State<AppState>, q: Query<WorkspaceQuery>, body: Json<RunRequest>) -> Response {
    let resp = agent_run(&s, q, body).await;
    if resp_is_err(&resp) {
        return err_response(resp_err_message(&resp), resp_err_code(&resp));
    }
    return ok_response(resp);
}

#[derive(Debug, Serialize)]
pub struct RunResponse {
    pub output: String,
    pub turns: i32,
    pub tool_calls: Vec<ToolCallOut>,
}

pub async fn chat_stream(s: State<AppState>, p: Path<String>, q: Query<WorkspaceQuery>) -> Response {
    let ch = mpsc_channel();
    let tx = mpsc_sender(&ch);
    let rx = mpsc_receiver(&ch);
    chat_run_stream(&s, q, p, tx).await;
    let stream = chat_sse_stream(rx.clone());
    let mut sse = Sse::new(stream);
    return sse.keep_alive(KeepAlive::new()).into_response();
}

fn chat_sse_stream(rx: Value) -> impl futures::Stream<Item = Result<Event, Infallible>> { async_stream::stream! {{
    loop {
        let msg = mpsc_recv(&rx).await;
        if msg_is_none(&msg) {
            

            break;
        } else {
            let dto = stream_event_to_dto(msg.clone());
            let event = sse_event("chat", to_value(dto).unwrap());
            yield Ok(event);
        }

    }
} } }