use super::extern_impl::*;
// Auto-generated by a2r transpiler

use axum::Router;
use axum::routing::{get};
use axum::response::Response;
use axum::Json;
use std::sync::Arc;
use std::path::PathBuf;
use serde::{Serialize};
use serde_json::Value;
#[derive(Serialize)]
pub struct SettingsLinkOk {
    pub status: String,
    pub url: String,
}

#[derive(Serialize)]
pub struct SettingsLinkErr {
    pub status: String,
    pub error: String,
}

async fn serve(addr: &str, client: Arc<dyn Client>) -> Result<String, String> {
    let state = serve_init_state(client);
    let static_service = serve_build_static();
    let cors = serve_build_cors();
    let app = serve_build_app(state, static_service, cors);
    serve_listen(addr, app).await;
    return Ok("".to_string());
}

async fn settings_link() -> Response {
    let cfg = app_config_load();
    let daemon_url = app_config_effective_daemon_url(cfg);
    let ensure_url: String = format!("{}{}", daemon_url, "/v1/services/os-config/ensure");
    let result = http_post_json(ensure_url.as_str()).await;
    match result {
        Ok(val) => {
            let status = value_get_str(&val, "status");
            let url = value_get_str(&val, "url");
            if status == "running" {
                if (url.len() as i32) > 0 {
                    return json_response(SettingsLinkOk { status: "running".to_string(), url: url.to_string() });
                }            }
            let error_val = value_get_str(&val, "error");
            return error_response(500, SettingsLinkErr { status: "error".to_string(), error: error_val.to_string() });
        },
        Err(e) => return error_response(502, SettingsLinkErr { status: "error".to_string(), error: e.to_string() }),
    }
}