use super::extern_impl::*;
// Auto-generated by a2r transpiler

use axum::Router;
use axum::routing::{get, post, delete, put, patch};
use axum::Json;
use axum::response::Response;
use axum::extract::{State, Path, Query};
use axum::http::HeaderMap;
use serde::{Serialize, Deserialize};
use serde_json::Value;
use crate::server::AppState;
/// server.at — ported from backend/crates/musk/src/server.rs (axum HTTP layer).
/// 
/// 全量移植 server.rs 的可移植 handler（45/52）。Strategy (plan 014):
/// - DTO struct + 所有 🟡 handler（json! 改 DTO、整体 extractor 参数、具体返回类型）-> Auto
/// - 7 个 🔴 handler（daemon/SSE/reqwest: run/run_stream/chat_stream/conversation_stream/
/// workflow_run/workflow_run_stream/settings_link）+ serve() 外壳（静态文件/CORS/
/// TcpListener/axum::serve）-> 手写 Rust
/// 
/// 关键转换规则（Plan 379 + 380 P0 后）:
/// - `impl IntoResponse` 多分支 -> 统一 `~Json<T>` 返回（错误也用 DTO，状态码在外壳层处理）
/// - `json!({"k":v})` -> 新建 DTO struct
/// - `State(s): State<AppState>` -> `s State<AppState>`（整体参数，函数体内访问 s.auth 等）
/// - `Path(id): Path<T>` -> `p Path<T>`
/// - handler 定义在 build_router 之前（a2r 单遍）
#[derive(Debug, Serialize)]
pub struct StatusOk {
    pub status: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ApiError {
    pub error: String,
}

#[derive(Debug, Serialize)]
pub struct Deleted {
    pub status: String,
    pub id: String,
}

#[derive(Debug, Serialize)]
pub struct Saved {
    pub status: String,
    pub name: String,
}

#[derive(Debug, Deserialize)]
pub struct LoginRequest {
    pub username: String,
    pub password: String,
}

/// Wire 形状与手写版对齐:{ token, user: { username, role } }。
/// C 阶段:ag server 的 UserInfo 自包含镜像(role 为字符串,序列化与 hw 的
/// Role enum 同名 —— "Admin"/"Developer"/"Viewer")。
#[derive(Debug, Serialize)]
pub struct UserInfo {
    pub username: String,
    pub role: String,
}

#[derive(Debug, Serialize)]
pub struct LoginResponse {
    pub token: String,
    pub user: UserInfo,
}

#[derive(Debug, Deserialize)]
pub struct SpecsUpsertRequest {
    pub section: String,
    pub item: SpecItemPayload,
}

#[derive(Debug, Deserialize)]
pub struct SpecItemPayload {
    pub id: String,
    pub title: String,
    pub content: String,
    pub status: String,
}

#[derive(Debug, Deserialize)]
pub struct SpecsTransitionRequest {
    pub section: String,
    pub item_id: String,
    pub new_status: String,
}

#[derive(Debug, Deserialize)]
pub struct RunRequest {
    pub task: String,
    pub mode: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct RunResponse {
    pub output: String,
    pub tool_calls: Vec<ToolCallOut>,
}

#[derive(Debug, Serialize)]
pub struct ToolCallOut {
    pub tool: String,
    pub args: String,
    pub result: String,
}

#[derive(Debug, Serialize)]
pub struct DriftResult {
    pub memory_version: u64,
    pub disk_version: u64,
    pub drifted: bool,
}

#[derive(Debug, Serialize)]
pub struct RelatedInfo {
    pub item_id: String,
    pub depends_on: Vec<String>,
    pub related: Vec<String>,
}

#[derive(Debug, Serialize)]
pub struct TransitionOk {
    pub status: String,
    pub new_status: String,
}

#[derive(Debug, Serialize)]
pub struct ProfessionsResp {
    pub professions: Vec<ProfessionItem>,
}

#[derive(Debug, Serialize)]
pub struct ProfessionItem {
    pub name: String,
    pub tier: String,
    pub model: String,
}

#[derive(Debug, Serialize)]
pub struct ModesResp {
    pub modes: Vec<ModeItem>,
}

#[derive(Debug, Serialize)]
pub struct ModeItem {
    pub name: String,
    pub description: String,
    pub role: String,
}

#[derive(Debug, Serialize)]
pub struct SkillsResp {
    pub skills: Vec<String>,
}

#[derive(Debug, Serialize)]
pub struct RolesResp {
    pub roles: Vec<RoleItem>,
}

#[derive(Debug, Serialize)]
pub struct RoleItem {
    pub name: String,
    pub tier: String,
    pub model: String,
}

#[derive(Debug, Serialize)]
pub struct RoleDetail {
    pub name: String,
    pub tier: String,
    pub model: String,
    pub temperature: f64,
    pub system_prompt: String,
}

#[derive(Debug, Deserialize)]
pub struct RoleSaveBody {
    pub model: Option<String>,
    pub tier: Option<String>,
    pub system_prompt: Option<String>,
    pub temperature: Option<f64>,
    pub description: Option<String>,
    pub inherit: Option<String>,
    pub allowed_tiers: Vec<String>,
    pub skills: Vec<String>,
    pub token_budget: Option<u64>,
    pub max_turns: Option<usize>,
    pub tools: Vec<String>,
    pub soul: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct ConfigOverview {
    pub modes: Vec<ModeItem>,
    pub professions: Vec<ProfessionItem>,
    pub skills: Vec<String>,
}

#[derive(Debug, Serialize)]
pub struct AppConfigResp {
    pub daemon_url: String,
    pub default_mode: String,
}

#[derive(Debug, Deserialize)]
pub struct AppConfigSaveBody {
    pub daemon_url: Option<String>,
    pub default_mode: Option<String>,
    pub forge_mode: Option<String>,
    pub context_file: Option<String>,
    pub serve_addr: Option<String>,
    pub auto_start_daemon: Option<bool>,
    pub harness: HarnessSelection,
}

#[derive(Debug, Deserialize)]
pub struct ForgeModeBody {
    pub mode: String,
}

#[derive(Debug, Deserialize, Default)]
pub struct HarnessSelection {
    pub roles: Vec<String>,
    pub skills: Vec<String>,
    pub modes: Vec<String>,
}

#[derive(Debug, Deserialize)]
pub struct HarnessBody {
    pub model: Option<String>,
    pub tier: Option<String>,
    pub system_prompt: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct AppHarnessSaveBody {
    pub model: Option<String>,
    pub tier: Option<String>,
    pub system_prompt: Option<String>,
    pub temperature: Option<f64>,
    pub description: Option<String>,
    pub inherit: Option<String>,
    pub allowed_tiers: Vec<String>,
    pub skills: Vec<String>,
    pub token_budget: Option<u64>,
    pub max_turns: Option<usize>,
    pub tools: Vec<String>,
    pub soul: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct WorkflowsResp {
    pub workflows: Vec<String>,
}

#[derive(Debug, Serialize)]
pub struct WorkspacesResp {
    pub workspaces: Vec<WorkspaceMeta>,
}

#[derive(Debug, Serialize)]
pub struct WorkspaceMeta {
    pub id: String,
    pub name: String,
    pub path: String,
}

#[derive(Debug, Serialize)]
pub struct WorkspaceResp {
    pub id: String,
    pub name: String,
}

#[derive(Debug, Serialize)]
pub struct WorkspaceStatusResp {
    pub id: String,
    pub empty: bool,
}

#[derive(Debug, Serialize)]
pub struct BrowseResp {
    pub entries: Vec<BrowseEntry>,
}

#[derive(Debug, Serialize)]
pub struct BrowseEntry {
    pub name: String,
    pub dir: bool,
}

#[derive(Debug, Serialize)]
pub struct Initialized {
    pub status: String,
}

#[derive(Debug, Serialize)]
pub struct SessionsResp {
    pub sessions: Vec<SessionSummary>,
}

#[derive(Debug, Serialize)]
pub struct SessionSummary {
    pub id: String,
    pub name: String,
    pub mode: String,
    pub message_count: u32,
}

#[derive(Debug, Serialize)]
pub struct SessionResp {
    pub id: String,
    pub name: String,
    pub mode: String,
}

#[derive(Debug, Deserialize)]
pub struct ChatCreateBody {
    pub mode: Option<String>,
    pub workspace_id: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct ChatRenameBody {
    pub name: String,
}

#[derive(Debug, Deserialize)]
pub struct ChatMessageBody {
    pub content: String,
    /// PLAN-055 ⑧(D1): optional run trigger — absent/None keeps the web-track
    /// subscription-driven semantics unchanged.
    pub run: Option<bool>,
}

#[derive(Debug, Serialize)]
pub struct QueuedResp {
    pub status: String,
}

#[derive(Debug, Serialize)]
pub struct ApproveResp {
    pub status: String,
    pub applied: bool,
}

#[derive(Debug, Serialize)]
pub struct DeletedAll {
    pub status: String,
    pub count: u32,
}

#[derive(Debug, Deserialize)]
pub struct ConversationTitleBody {
    pub title: String,
}

#[derive(Debug, Deserialize)]
pub struct OpenWorkspaceBody {
    pub path: String,
}

#[derive(Debug, Deserialize)]
pub struct BrowseQuery {
    pub path: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct WorkspaceQuery {
    pub workspace: Option<String>,
}

/// Extract bearer token from Authorization header.
fn bearer_token(headers: HeaderMap) -> Option<String> {

    return auth_header_token(headers);
}

async fn health() -> Json<StatusOk> {
    return Json(StatusOk { status: "ok".to_string() });
}

pub async fn auth_login(s: State<AppState>, body: Json<LoginRequest>) -> Response {



    let username: String = body.username.clone();
    let pair = auth_login_result(&s, username.clone(), body.password.clone());
    let token: String = pair.0.clone();
    let role: String = pair.1.clone();
    if (token.len() as i64) > 0 {
        return ok_response(LoginResponse { token: token.to_string(), user: UserInfo { username: username.to_string(), role: role.to_string() } });
    }
    return err_response("invalid credentials", 401);
}

pub async fn auth_register(s: State<AppState>, body: Json<LoginRequest>) -> Response {

    let username: String = body.username.clone();
    let pair = auth_register_result(&s, username.clone(), body.password.clone());
    let token: String = pair.0.clone();
    let role: String = pair.1.clone();
    if (token.len() as i64) > 0 {
        return ok_response(LoginResponse { token: token.to_string(), user: UserInfo { username: username.to_string(), role: role.to_string() } });
    }
    return err_response("username already exists", 409);
}

pub async fn auth_me(s: State<AppState>, headers: HeaderMap) -> Response {

    let token: String = auth_token_from_headers(&s, headers);
    if (token.len() as i64) == 0 {
        return err_response("missing Authorization header", 401);
    }
    let username: String = auth_username_from_token(&s, &token);
    if (username.len() as i64) == 0 {
        return err_response("invalid or expired session", 401);
    }
    let role: String = auth_role_from_token(&s, &token);
    return ok_response(UserInfo { username: username.to_string(), role: role.to_string() });
}

pub async fn auth_logout(s: State<AppState>, headers: HeaderMap) -> Json<StatusOk> {
    auth_logout_token(&s, headers);
    return Json(StatusOk { status: "logged out".to_string() });
}

pub async fn specs_list(s: State<AppState>, q: Query<WorkspaceQuery>) -> Response {
    return to_response(specs_load(&s, q), "failed to load specs", 500);
}

pub async fn specs_overview(s: State<AppState>, q: Query<WorkspaceQuery>) -> Response {
    return to_response(specs_overview_of(&s, q), "failed to build overview", 500);
}

pub async fn specs_drift_check(s: State<AppState>, q: Query<WorkspaceQuery>) -> Response {
    return to_response(specs_drift(&s, q), "drift check failed", 500);
}

pub async fn specs_rebuild_relations(s: State<AppState>, q: Query<WorkspaceQuery>) -> Response {
    return to_response(specs_rebuild(&s, q), "rebuild failed", 500);
}

pub async fn specs_related(s: State<AppState>, q: Query<WorkspaceQuery>, p: Path<String>) -> Response {
    return to_response(specs_related_of(&s, q, p), "item not found", 404);
}

pub async fn specs_upsert(s: State<AppState>, q: Query<WorkspaceQuery>, body: Json<SpecsUpsertRequest>) -> Response {
    return to_response(specs_upsert_of(&s, q, body), "upsert failed", 400);
}

pub async fn specs_transition(s: State<AppState>, q: Query<WorkspaceQuery>, body: Json<SpecsTransitionRequest>) -> Response {
    return to_response(specs_transition_of(&s, q, body), "transition failed", 400);
}

pub async fn specs_delete(s: State<AppState>, q: Query<WorkspaceQuery>, p: Path<(String, String)>) -> Response {
    return to_response(specs_delete_of(&s, q, p), "item not found", 404);
}

pub async fn professions() -> Json<Value> {
    let list = professions_list();
    return Json(list);
}

pub async fn config_overview() -> Json<Value> {
    let cfg = config_build();
    return Json(cfg);
}

pub async fn modes_list() -> Json<Value> {
    let list = modes_all();
    return Json(list);
}

pub async fn skills_list() -> Json<Value> {
    let list = skills_all();
    return Json(list);
}

pub async fn roles_list() -> Json<Value> {
    let list = roles_all();
    return Json(list);
}

pub async fn role_detail(p: Path<String>) -> Response {
    return to_response(role_get(&p), "role not found", 404);
}

pub async fn role_save(p: Path<String>, body: Json<RoleSaveBody>) -> Response {
    return to_response(role_save_of(&p, body), "failed to save role", 400);
}

pub async fn role_delete(p: Path<String>) -> Response {
    return to_response(role_delete_of(&p), "failed to delete role", 404);
}

pub async fn app_config_get() -> Json<Value> {
    let cfg = app_config_load();
    return Json(cfg);
}

pub async fn app_config_save(body: Json<AppConfigSaveBody>) -> Response {
    return to_response(app_config_write(body), "failed to save app config", 500);
}

pub async fn forge_mode_get() -> Json<Value> {
    let cfg = forge_mode_load();
    return Json(cfg);
}

pub async fn forge_mode_set(body: Json<ForgeModeBody>) -> Response {
    return to_response(forge_mode_write(body), "failed to save forge mode", 500);
}

pub async fn app_harness_list(p: Path<String>) -> Response {
    return to_response(harness_list(&p), "unknown harness kind", 404);
}

pub async fn app_harness_save(p: Path<(String, String)>, body: Json<AppHarnessSaveBody>) -> Response {
    return to_response(harness_save(&p, body), "failed to save harness item", 500);
}

pub async fn app_harness_delete(p: Path<(String, String)>) -> Response {
    return to_response(harness_delete(&p), "harness item not found", 404);
}

pub async fn chat_create(s: State<AppState>, q: Query<WorkspaceQuery>, body: Json<ChatCreateBody>) -> Response {
    return to_response(chats_create(&s, q, body), "failed to create session", 500);
}

pub async fn chat_list(s: State<AppState>, q: Query<WorkspaceQuery>) -> Json<Value> {
    let list = chats_list(&s, q);
    return Json(list);
}

pub async fn chat_get(s: State<AppState>, q: Query<WorkspaceQuery>, p: Path<String>) -> Response {
    return to_response(chats_get(&s, q, p), "session not found", 404);
}

pub async fn chat_rename(s: State<AppState>, q: Query<WorkspaceQuery>, p: Path<String>, body: Json<ChatRenameBody>) -> Response {
    return to_response(chats_rename(&s, q, p, body), "session not found", 404);
}

pub async fn chat_delete(s: State<AppState>, q: Query<WorkspaceQuery>, p: Path<String>) -> Response {
    return to_response(chats_delete(&s, q, &p), "session not found", 404);
}

pub async fn chat_delete_all(s: State<AppState>, q: Query<WorkspaceQuery>) -> Response {
    return to_response(chats_delete_all(&s, q), "failed to delete all sessions", 500);
}

pub async fn chat_message(s: State<AppState>, q: Query<WorkspaceQuery>, p: Path<String>, body: Json<ChatMessageBody>) -> Response {
    return to_response(chats_message(&s, q, p, body), "session not found", 404);
}

pub async fn chat_approve(s: State<AppState>, q: Query<WorkspaceQuery>, p: Path<(String, u32)>) -> Response {
    return to_response(chats_approve(&s, q, p), "session or change not found", 404);
}

pub async fn chat_reject(s: State<AppState>, q: Query<WorkspaceQuery>, p: Path<(String, u32)>) -> Response {
    return to_response(chats_reject(&s, q, p), "session not found", 404);
}

pub async fn chat_reject_all(s: State<AppState>, q: Query<WorkspaceQuery>, p: Path<String>) -> Response {
    return to_response(chats_reject_all(&s, q, p), "session not found", 404);
}

pub async fn conversation_list(s: State<AppState>, q: Query<WorkspaceQuery>) -> Json<Value> {
    let list = conversations_list(&s, q);
    return Json(list);
}

pub async fn conversation_get(s: State<AppState>, p: Path<String>, q: Query<WorkspaceQuery>) -> Response {
    return to_response(conversations_get(&s, q, p), "conversation not found", 404);
}

pub async fn conversation_delete(s: State<AppState>, q: Query<WorkspaceQuery>, p: Path<String>) -> Response {
    return to_response(conversations_delete(&s, q, &p), "conversation not found", 404);
}

pub async fn conversation_rename(s: State<AppState>, q: Query<WorkspaceQuery>, p: Path<String>, body: Json<ConversationTitleBody>) -> Response {
    return to_response(conversations_rename(&s, q, p, body), "conversation not found", 404);
}

pub async fn workspace_list(s: State<AppState>) -> Json<Value> {
    let list = workspace_list_all(&s);
    return Json(list);
}

pub async fn workspace_open(s: State<AppState>, body: Json<OpenWorkspaceBody>) -> Response {
    return to_response(workspace_open_of(&s, body), "failed to open workspace", 500);
}

pub async fn workspace_status(s: State<AppState>, q: Query<WorkspaceQuery>) -> Response {
    return to_response(workspace_status_of(&s, q), "workspace not found", 404);
}

pub async fn workspace_browse(q: Query<BrowseQuery>) -> Json<Value> {
    let resp = workspace_browse_of(&q);
    return Json(resp);
}

pub async fn workspace_initialize(s: State<AppState>, q: Query<WorkspaceQuery>) -> Response {
    return to_response(workspace_initialize_of(&s, q), "failed to initialize workspace", 500);
}

async fn workflows() -> Json<WorkflowsResp> {
    let list = workflows_builtin_names();
    return Json(WorkflowsResp { workflows: list });
}

pub async fn workspace_file(s: State<AppState>, p: Path<(String, String)>) -> Response {
    return workspace_file_do(&s, p);
}

pub fn build_router() -> Router<AppState> {
    let mut app = Router::new();
    app = app.route("/api/health", get(health));
    app = app.route("/api/professions", get(professions));
    app = app.route("/api/workflows", get(workflows));
    app = app.route("/api/files/{workspace_id}/{*path}", get(workspace_file));
    app = app.route("/api/auth/login", post(auth_login));
    app = app.route("/api/auth/register", post(auth_register));
    app = app.route("/api/auth/me", get(auth_me));
    app = app.route("/api/auth/logout", post(auth_logout));
    app = app.route("/api/specs", get(specs_list));
    app = app.route("/api/specs/item", post(specs_upsert));
    app = app.route("/api/specs/transition", post(specs_transition));
    app = app.route("/api/specs/item/{section}/{id}", delete(specs_delete));
    app = app.route("/api/specs/overview", get(specs_overview));
    app = app.route("/api/specs/drift-check", post(specs_drift_check));
    app = app.route("/api/specs/rebuild-relations", post(specs_rebuild_relations));
    app = app.route("/api/specs/related/{item_id}", get(specs_related));
    app = app.route("/api/config", get(config_overview));
    app = app.route("/api/modes", get(modes_list));
    app = app.route("/api/skills", get(skills_list));
    app = app.route("/api/roles", get(roles_list));
    app = app.route("/api/roles/{name}", get(role_detail).put(role_save).delete(role_delete));
    app = app.route("/api/app-config", get(app_config_get).put(app_config_save));
    app = app.route("/api/forge/mode", get(forge_mode_get).put(forge_mode_set));
    app = app.route("/api/app-harness/{kind}", get(app_harness_list));
    app = app.route("/api/app-harness/{kind}/{name}", put(app_harness_save).delete(app_harness_delete));
    app = app.route("/api/chats/sessions", get(chat_list).delete(chat_delete_all));
    app = app.route("/api/chats/session", post(chat_create));
    app = app.route("/api/chats/session/{id}", get(chat_get).patch(chat_rename).delete(chat_delete));
    app = app.route("/api/chats/session/{id}/message", post(chat_message));
    app = app.route("/api/chats/session/{id}/approve/{index}", post(chat_approve));
    app = app.route("/api/chats/session/{id}/reject/{index}", post(chat_reject));
    app = app.route("/api/chats/session/{id}/reject-all", post(chat_reject_all));
    app = app.route("/api/conversations", get(conversation_list));
    app = app.route("/api/conversations/{id}", get(conversation_get).delete(conversation_delete));
    app = app.route("/api/conversations/{id}/title", patch(conversation_rename));
    app = app.route("/api/workspace/list", get(workspace_list));
    app = app.route("/api/workspace/open", post(workspace_open));
    app = app.route("/api/workspace/status", get(workspace_status));
    app = app.route("/api/workspace/browse", get(workspace_browse));
    app = app.route("/api/workspace/initialize", post(workspace_initialize));
    return app;
}