use crate::auto_generated::extern_impl::*;
// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use std::time::{SystemTime, Duration};
use serde::{Serialize, Deserialize};
use std::collections::{HashSet, HashMap};
use std::fs;
use std::path::PathBuf;
use serde_json::{to_string_pretty, from_slice};
use serde_json::Value;
/// specs.at — PoC: Spec Ledger data-model subset, ported from
/// backend/crates/musk/src/specs.rs.
/// 
/// Goal: validate whether a2r can transpile a real, axum-free data-model
/// slice of auto-musk back to compiling Rust. Scope (v2): the two scalar
/// enums (SectionType / SpecStatus) + string conversions + SpecItem struct
/// + factory (exercises String/Vec/Option/u64 fields + time bridge).
/// 
/// Notes on porting choices (cross-referenced to auto-lang-creator skill):
/// - A 类规则: 函数体不写 `::` 路径; 返回类型用空格不用 `->`; 字段/参数
/// 类型用空格; 模式匹配用 `is` + `->`; 无分号。
/// - now_sec() via std::time SystemTime.elapsed() (NOT a2r_std::time — this
/// port targets native Rust via use.rust, no a2r-std runtime dependency).
/// Current unix timestamp in seconds (native std::time, no a2r-std).
fn now_sec() -> u64 {
    let now = SystemTime::now();
    let elapsed = now.elapsed().unwrap();
    return elapsed.as_secs();
}

/// - Rust 的 SectionType 是无 repr 的 unit 枚举 (Goals, Architecture, ...)。
/// Auto 的 scalar enum 形态是 `VARIANT = N` (见 02_types/002_enum)。这里先
/// 用 scalar 形态 (显式数字) — 这是 PoC 的第一个待测点: a2r 对此能否生成
/// 可编译的 Rust enum + Display。
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
enum SectionType {
    Goals = 1,
    Architecture = 2,
    Designs = 3,
    Plans = 4,
    Tests = 5,
    Reviews = 6,
    Reports = 7,
}

impl std::fmt::Display for SectionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            SectionType::Goals => write!(f, "Goals"),
            SectionType::Architecture => write!(f, "Architecture"),
            SectionType::Designs => write!(f, "Designs"),
            SectionType::Plans => write!(f, "Plans"),
            SectionType::Tests => write!(f, "Tests"),
            SectionType::Reviews => write!(f, "Reviews"),
            SectionType::Reports => write!(f, "Reports"),
        }
    }
}
impl SectionType {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Goals" | "goals" => SectionType::Goals,
            "Architecture" | "architecture" => SectionType::Architecture,
            "Designs" | "designs" => SectionType::Designs,
            "Plans" | "plans" => SectionType::Plans,
            "Tests" | "tests" => SectionType::Tests,
            "Reviews" | "reviews" => SectionType::Reviews,
            "Reports" | "reports" => SectionType::Reports,
            _ => SectionType::Goals
        }
    }
}

impl SectionType {
    pub fn as_str(&self) -> String {
        match self {
            SectionType::Goals => return "goals".to_string(),
            SectionType::Architecture => return "architecture".to_string(),
            SectionType::Designs => return "designs".to_string(),
            SectionType::Plans => return "plans".to_string(),
            SectionType::Tests => return "tests".to_string(),
            SectionType::Reviews => return "reviews".to_string(),
            SectionType::Reports => return "reports".to_string(),
        };
    }
    pub fn display_title(&self) -> String {
        match self {
            SectionType::Goals => return "Goals".to_string(),
            SectionType::Architecture => return "Architecture".to_string(),
            SectionType::Designs => return "Designs".to_string(),
            SectionType::Plans => return "Plans".to_string(),
            SectionType::Tests => return "Tests".to_string(),
            SectionType::Reviews => return "Reviews".to_string(),
            SectionType::Reports => return "Reports".to_string(),
        };
    }
}

/// snake_case string id (e.g. "goals", "architecture").
/// NOTE: a2r auto-generates `from_id` for scalar enums, so we only
/// hand-write `as_str` + `display_title` here.
/// display title with emoji (for .ad file headers).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
enum SpecStatus {
    Empty = 1,
    Proposed = 2,
    Draft = 3,
    UnderReview = 4,
    Approved = 5,
    InProgress = 6,
    InImplementation = 7,
    Implemented = 8,
    Verified = 9,
    Done = 10,
    Archived = 11,
    Rejected = 12,
    Backlog = 13,
    Ready = 14,
    InReview = 15,
    Blocked = 16,
    Superseded = 17,
    Outdated = 18,
    Stable = 19,
    Deprecated = 20,
    Published = 21,
    Analysed = 22,
    Obsolete = 23,
}

impl std::fmt::Display for SpecStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            SpecStatus::Empty => write!(f, "Empty"),
            SpecStatus::Proposed => write!(f, "Proposed"),
            SpecStatus::Draft => write!(f, "Draft"),
            SpecStatus::UnderReview => write!(f, "UnderReview"),
            SpecStatus::Approved => write!(f, "Approved"),
            SpecStatus::InProgress => write!(f, "InProgress"),
            SpecStatus::InImplementation => write!(f, "InImplementation"),
            SpecStatus::Implemented => write!(f, "Implemented"),
            SpecStatus::Verified => write!(f, "Verified"),
            SpecStatus::Done => write!(f, "Done"),
            SpecStatus::Archived => write!(f, "Archived"),
            SpecStatus::Rejected => write!(f, "Rejected"),
            SpecStatus::Backlog => write!(f, "Backlog"),
            SpecStatus::Ready => write!(f, "Ready"),
            SpecStatus::InReview => write!(f, "InReview"),
            SpecStatus::Blocked => write!(f, "Blocked"),
            SpecStatus::Superseded => write!(f, "Superseded"),
            SpecStatus::Outdated => write!(f, "Outdated"),
            SpecStatus::Stable => write!(f, "Stable"),
            SpecStatus::Deprecated => write!(f, "Deprecated"),
            SpecStatus::Published => write!(f, "Published"),
            SpecStatus::Analysed => write!(f, "Analysed"),
            SpecStatus::Obsolete => write!(f, "Obsolete"),
        }
    }
}
impl SpecStatus {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Empty" | "empty" => SpecStatus::Empty,
            "Proposed" | "proposed" => SpecStatus::Proposed,
            "Draft" | "draft" => SpecStatus::Draft,
            "UnderReview" | "underreview" => SpecStatus::UnderReview,
            "Approved" | "approved" => SpecStatus::Approved,
            "InProgress" | "inprogress" => SpecStatus::InProgress,
            "InImplementation" | "inimplementation" => SpecStatus::InImplementation,
            "Implemented" | "implemented" => SpecStatus::Implemented,
            "Verified" | "verified" => SpecStatus::Verified,
            "Done" | "done" => SpecStatus::Done,
            "Archived" | "archived" => SpecStatus::Archived,
            "Rejected" | "rejected" => SpecStatus::Rejected,
            "Backlog" | "backlog" => SpecStatus::Backlog,
            "Ready" | "ready" => SpecStatus::Ready,
            "InReview" | "inreview" => SpecStatus::InReview,
            "Blocked" | "blocked" => SpecStatus::Blocked,
            "Superseded" | "superseded" => SpecStatus::Superseded,
            "Outdated" | "outdated" => SpecStatus::Outdated,
            "Stable" | "stable" => SpecStatus::Stable,
            "Deprecated" | "deprecated" => SpecStatus::Deprecated,
            "Published" | "published" => SpecStatus::Published,
            "Analysed" | "analysed" => SpecStatus::Analysed,
            "Obsolete" | "obsolete" => SpecStatus::Obsolete,
            _ => SpecStatus::Empty
        }
    }
}

impl SpecStatus {
    pub fn to_str(&self) -> String {
        match self {
            SpecStatus::Empty => return "empty".to_string(),
            SpecStatus::Proposed => return "proposed".to_string(),
            SpecStatus::Draft => return "draft".to_string(),
            SpecStatus::UnderReview => return "under_review".to_string(),
            SpecStatus::Approved => return "approved".to_string(),
            SpecStatus::InProgress => return "in_progress".to_string(),
            SpecStatus::InImplementation => return "in_implementation".to_string(),
            SpecStatus::Implemented => return "implemented".to_string(),
            SpecStatus::Verified => return "verified".to_string(),
            SpecStatus::Done => return "done".to_string(),
            SpecStatus::Archived => return "archived".to_string(),
            SpecStatus::Rejected => return "rejected".to_string(),
            SpecStatus::Backlog => return "backlog".to_string(),
            SpecStatus::Ready => return "ready".to_string(),
            SpecStatus::InReview => return "in_review".to_string(),
            SpecStatus::Blocked => return "blocked".to_string(),
            SpecStatus::Superseded => return "superseded".to_string(),
            SpecStatus::Outdated => return "outdated".to_string(),
            SpecStatus::Stable => return "stable".to_string(),
            SpecStatus::Deprecated => return "deprecated".to_string(),
            SpecStatus::Published => return "published".to_string(),
            SpecStatus::Analysed => return "analysed".to_string(),
            SpecStatus::Obsolete => return "obsolete".to_string(),
        };
    }
    pub fn from_str_lossy(s: &str) -> SpecStatus {
        let mut table: std::collections::HashMap<String, SpecStatus> = std::collections::HashMap::new();
        table.insert("empty".to_string(), SpecStatus::Empty);
        table.insert("proposed".to_string(), SpecStatus::Proposed);
        table.insert("draft".to_string(), SpecStatus::Draft);
        table.insert("under_review".to_string(), SpecStatus::UnderReview);
        table.insert("approved".to_string(), SpecStatus::Approved);
        table.insert("in_progress".to_string(), SpecStatus::InProgress);
        table.insert("in_implementation".to_string(), SpecStatus::InImplementation);
        table.insert("implemented".to_string(), SpecStatus::Implemented);
        table.insert("verified".to_string(), SpecStatus::Verified);
        table.insert("done".to_string(), SpecStatus::Done);
        table.insert("archived".to_string(), SpecStatus::Archived);
        table.insert("rejected".to_string(), SpecStatus::Rejected);
        table.insert("backlog".to_string(), SpecStatus::Backlog);
        table.insert("ready".to_string(), SpecStatus::Ready);
        table.insert("in_review".to_string(), SpecStatus::InReview);
        table.insert("blocked".to_string(), SpecStatus::Blocked);
        table.insert("superseded".to_string(), SpecStatus::Superseded);
        table.insert("outdated".to_string(), SpecStatus::Outdated);
        table.insert("stable".to_string(), SpecStatus::Stable);
        table.insert("deprecated".to_string(), SpecStatus::Deprecated);
        table.insert("published".to_string(), SpecStatus::Published);
        table.insert("analysed".to_string(), SpecStatus::Analysed);
        table.insert("obsolete".to_string(), SpecStatus::Obsolete);

        match table.get(s) {
            Some(v) => return v.clone(),
            None => return SpecStatus::Draft,
        };
    }
}

/// snake_case string.
/// Parse from a string. Unknown -> Draft (lossy).
/// A21: str 的 `is` 匹配会被 a2r 渲染成 unstable 的 str_as_str —— 改用
/// Map 查表（避开字符串 is 匹配；A4: get() 返回 Option 需 ?? 兜底）。
/// The minimal spec unit (one Goal, one Architecture decision, ...).
/// - id: type-prefixed number (G1, A3, S1.1)
/// - depends_on: manually-declared forward deps (item IDs)
/// - related: derived reverse-links (filled by rebuild_relations, later)
/// - tags: label list
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SpecItem {
    pub id: String,
    pub title: String,
    pub content: String,
    pub status: SpecStatus,
    pub depends_on: Vec<String>,
    pub related: Vec<String>,
    pub priority: Option<String>,
    pub assignee: Option<String>,
    pub test_file: Option<String>,
    pub file: Option<String>,
    pub milestone: Option<String>,
    pub module: Option<String>,
    pub tags: Vec<String>,
    pub created_at: u64,
    pub modified_at: u64,
    pub completed_at: Option<u64>,
}

impl SpecItem {
    pub fn new(id: &str, title: &str) -> SpecItem {
        let now: u64 = now_sec();
        return SpecItem { id: id.clone().to_string(), title: title.clone().to_string(), content: "".to_string(), status: SpecStatus::Empty, depends_on: vec![], related: vec![], priority: None, assignee: None, test_file: None, file: None, milestone: None, module: None, tags: vec![], created_at: now, modified_at: now, completed_at: None };
    }
}

/// Factory: create with id + title, status Empty, timestamps = now.
/// Rust 原版用 impl Into<String> — Auto 无 trait 约束参数，简化为 str。
/// A15: now_sec() via time bridge. A8: id/title owned，多次用需 clone。
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SpecsSection {
    pub id: String,
    pub section_type: SectionType,
    pub title: String,
    pub items: Vec<SpecItem>,
    pub status: SpecStatus,
    pub content: String,
    pub depends_on: Vec<String>,
    pub last_modified: u64,
    pub last_verified: Option<u64>,
}

impl SpecsSection {
    pub fn new(st: SectionType) -> SpecsSection {
        return SpecsSection { id: st.as_str().to_string(), section_type: st, title: st.display_title().to_string(), items: vec![], status: SpecStatus::Empty, content: "".to_string(), depends_on: vec![], last_modified: now_sec(), last_verified: None };
    }
}

/// Factory: empty section of the given type (title = display title).
/// st is Copy in Rust; in Auto the owned value is consumed by the first
/// method call, so derive fields from copies.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SpecsDocument {
    pub project: String,
    pub version: u64,
    pub sections: Vec<SpecsSection>,
}

impl SpecsDocument {
    pub fn new(project: &str) -> SpecsDocument {
        return SpecsDocument { project: project.clone().to_string(), version: 0, sections: vec![SpecsSection::new(SectionType::Goals), SpecsSection::new(SectionType::Architecture), SpecsSection::new(SectionType::Designs), SpecsSection::new(SectionType::Plans), SpecsSection::new(SectionType::Tests), SpecsSection::new(SectionType::Reviews), SpecsSection::new(SectionType::Reports)] };
    }
    pub fn rebuild_relations(&mut self) {
        let mut known: HashSet<String> = all_ids(self.clone());

        let mut reverse: Vec<ReverseEntry> = vec![];

        for section in self.sections.clone() {
            for item in section.items.clone() {
                let mut forwards: Vec<String> = item.depends_on.clone();
                let scanned: Vec<String> = scan_refs(item.content.clone(), known.clone());
                for s in scanned.clone() {
                    forwards.push(s.clone());
                }
                forwards.sort();
                


                for target in forwards.clone() {
                    let mut updated_reverse: Vec<ReverseEntry> = vec![];
                    let mut target_found: bool = false;
                    for e in reverse.clone() {
                        if e.target_id == target {
                            target_found = true;
                            let mut more: Vec<String> = e.referrers.clone();
                            more.push(item.id.clone());
                            let updated: ReverseEntry = ReverseEntry { target_id: e.target_id.clone().to_string(), referrers: more };
                            updated_reverse.push(updated.clone())
                        } else {
                            updated_reverse.push(e.clone())
                        }

                    }
                    if target_found == false {
                        let entry: ReverseEntry = ReverseEntry { target_id: target.clone().to_string(), referrers: vec![item.id.clone()] };
                        updated_reverse.push(entry.clone());
                    }
                    reverse = updated_reverse;
                }
            }
        }



        let mut new_sections: Vec<SpecsSection> = vec![];
        for section in self.sections.clone() {
            let mut new_items: Vec<SpecItem> = vec![];
            for item in section.items.clone() {
                
                let mut new_related: Vec<String> = vec![];
                for e in reverse.clone() {
                    if e.target_id == item.id {
                        new_related = e.referrers.clone()
                    }
                }
                new_related.sort();
                
                let mut deduped: Vec<String> = vec![];
                let mut prev: String = "".to_string();
                for r in new_related.clone() {
                    if r != prev {
                        deduped.push(r.clone());
                    }
                    prev = r.clone();
                }
                
                let new_item: SpecItem = SpecItem { id: item.id.clone().to_string(), title: item.title.clone().to_string(), content: item.content.clone().to_string(), status: item.status, depends_on: item.depends_on.clone(), related: deduped, priority: item.priority.clone(), assignee: item.assignee.clone(), test_file: item.test_file.clone(), file: item.file.clone(), milestone: item.milestone.clone(), module: item.module.clone(), tags: item.tags.clone(), created_at: item.created_at, modified_at: item.modified_at, completed_at: item.completed_at };
                new_items.push(new_item.clone());
            }
            let new_section: SpecsSection = SpecsSection { id: section.id.clone().to_string(), section_type: section.section_type, title: section.title.clone().to_string(), items: new_items, status: section.status, content: section.content.clone().to_string(), depends_on: section.depends_on.clone(), last_modified: section.last_modified, last_verified: section.last_verified.clone() };
            new_sections.push(new_section.clone());
        }
        self.sections = new_sections;
    }
    pub fn derive_statuses(&mut self) {

        let mut snap: Vec<Snap> = vec![];
        for section in self.sections.clone() {
            for item in section.items.clone() {
                snap.push(Snap { id: item.id.clone().to_string(), section_type: section.section_type, status: item.status, related: item.related.clone() });
            }
        }

        let goal_cfg: SectionConfig = SectionConfig::for_type(SectionType::Goals);


        let mut new_sections: Vec<SpecsSection> = vec![];
        for section in self.sections.clone() {
            let mut new_section_status: SpecStatus = section.status;
            let mut new_last_modified: u64 = section.last_modified;
            

            let mut new_items: Vec<SpecItem> = vec![];
            for item in section.items.clone() {
                let mut new_status: SpecStatus = item.status;
                let mut new_item_modified: u64 = item.modified_at;
                
                if section.section_type == SectionType::Goals {
                    let forwards: Vec<String> = item.depends_on.clone();
                    let mut related_plans_all_done: bool = true;
                    let mut has_any_plan: bool = false;
                    for rid in forwards.clone() {
                        match find_snap(snap.clone(), rid.as_str()) {
                            Some(x) => {
                                if x.section_type == SectionType::Plans {
                                    has_any_plan = true;
                                    if x.status != SpecStatus::Done {
                                        related_plans_all_done = false
                                    }                                }
                            },
                            None => {},
                        };
                    }
                    


                    if has_any_plan {
                        if related_plans_all_done {
                            if is_goal_advanceable(item.status) {
                                if goal_cfg.can_transition(item.status, SpecStatus::Implemented) {
                                    new_status = SpecStatus::Implemented;
                                    new_item_modified = now_sec()
                                }                            }                        }                    }                    


                    if new_status == SpecStatus::Implemented {
                        let mut tests_ok: bool = true;
                        let mut has_tests: bool = false;
                        let mut has_review_published: bool = false;
                        for rid in forwards.clone() {
                            match find_snap(snap.clone(), rid.as_str()) {
                                Some(x) => {
                                    if x.section_type == SectionType::Tests {
                                        has_tests = true;
                                        if is_test_pending(x.status) {
                                            tests_ok = false
                                        }                                    }
                                    if x.section_type == SectionType::Reviews {
                                        if x.status == SpecStatus::Published {
                                            has_review_published = true
                                        }                                    }
                                },
                                None => {},
                            };
                        }
                        if has_tests {
                            if tests_ok {
                                if has_review_published {
                                    if goal_cfg.can_transition(SpecStatus::Implemented, SpecStatus::Verified) {
                                        new_status = SpecStatus::Verified;
                                        new_item_modified = now_sec()
                                    }                                }                            }                        }                    }                }
                




                let new_item: SpecItem = SpecItem { id: item.id.clone().to_string(), title: item.title.clone().to_string(), content: item.content.clone().to_string(), status: new_status, depends_on: item.depends_on.clone(), related: item.related.clone(), priority: item.priority.clone(), assignee: item.assignee.clone(), test_file: item.test_file.clone(), file: item.file.clone(), milestone: item.milestone.clone(), module: item.module.clone(), tags: item.tags.clone(), created_at: item.created_at, modified_at: new_item_modified, completed_at: item.completed_at };
                new_items.push(new_item.clone());
            }
            

            let mut all_items_empty: bool = (section.items.len() as i32) == 0;
            if all_items_empty {
                

            } else {
                let done_status: SpecStatus = section_complete_status(section.section_type);
                let cfg: SectionConfig = SectionConfig::for_type(section.section_type);
                let mut all_done: bool = true;
                for it in new_items.clone() {
                    if it.status != done_status {
                        all_done = false
                    }
                }
                if all_done {
                    if cfg.can_transition(new_section_status, done_status) {
                        if new_section_status != done_status {
                            new_section_status = done_status;
                            new_last_modified = now_sec()
                        }                    }                } else {
                    let mut any_non_empty: bool = false;
                    for it in new_items.clone() {
                        if it.status != SpecStatus::Empty {
                            any_non_empty = true
                        }
                    }
                    if any_non_empty {
                        if cfg.can_transition(new_section_status, SpecStatus::Draft) {
                            if new_section_status == SpecStatus::Empty {
                                new_section_status = SpecStatus::Draft;
                                new_last_modified = now_sec()
                            }                        }                    }                }
            }

            


            let new_section: SpecsSection = SpecsSection { id: section.id.clone().to_string(), section_type: section.section_type, title: section.title.clone().to_string(), items: new_items, status: new_section_status, content: section.content.clone().to_string(), depends_on: section.depends_on.clone(), last_modified: new_last_modified, last_verified: section.last_verified.clone() };
            new_sections.push(new_section.clone());
        }



        self.sections = new_sections;
    }
    pub fn overview(&self) -> SpecsOverview {
        let mut sections: Vec<SectionOverview> = vec![];
        let mut total: u32 = 0 as u32;
        for s in self.sections.clone() {
            
            let mut seen: Vec<String> = vec![];
            let mut counts: Vec<(String, u32)> = vec![];
            for it in s.items.clone() {
                let st: String = it.status.to_str();
                let mut found: bool = false;
                for pair in counts.clone() {
                    if pair.0.clone() == st {
                        found = true
                    }
                }
                if found == false {
                    seen.push(st.clone());
                }
            }
            
            for st in seen.clone() {
                let mut n: u32 = 0 as u32;
                for it in s.items.clone() {
                    if it.status.to_str() == st {
                        n = n + 1
                    }
                }
                counts.push((st.clone(), n));
            }
            let count: u32 = ((s.items.len() as u32) as u32);
            total = total + count;
            
            let so: SectionOverview = SectionOverview { id: s.id.clone().to_string(), section_type: s.section_type, title: s.title.clone().to_string(), status: s.status, item_count: count, status_counts: counts };
            sections.push(so.clone());
        }
        let result: SpecsOverview = SpecsOverview { project: self.project.clone().to_string(), version: self.version.clone(), total_items: total, sections: sections };
        return result;
    }
}

/// Factory: a document with all 7 empty sections.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SpecChange {
    pub section_id: String,
    pub item_id: String,
    pub title: Option<String>,
    pub content: Option<String>,
    pub status: Option<SpecStatus>,
    pub reason: String,
}

/// Per-section-type state-machine configuration.
/// A7 待测点: Vec<(SpecStatus, SpecStatus)> 作为字段类型 — Auto tuple 有限制。
#[derive(Clone, Debug)]
pub struct SectionConfig {
    pub section_type: SectionType,
    pub allowed_statuses: Vec<SpecStatus>,
    pub allowed_transitions: Vec<(SpecStatus, SpecStatus)>,
}

impl SectionConfig {
    pub fn for_type(st: SectionType) -> SectionConfig {
        match st {
            SectionType::Goals => return SectionConfig { section_type: st, allowed_statuses: vec![SpecStatus::Empty, SpecStatus::Proposed, SpecStatus::Analysed, SpecStatus::Approved, SpecStatus::InProgress, SpecStatus::Implemented, SpecStatus::Verified, SpecStatus::Done, SpecStatus::Archived], allowed_transitions: vec![(SpecStatus::Empty, SpecStatus::Proposed), (SpecStatus::Proposed, SpecStatus::Analysed), (SpecStatus::Analysed, SpecStatus::Approved), (SpecStatus::Approved, SpecStatus::InProgress), (SpecStatus::InProgress, SpecStatus::Implemented), (SpecStatus::Implemented, SpecStatus::Verified), (SpecStatus::Verified, SpecStatus::Done), (SpecStatus::Done, SpecStatus::Archived), (SpecStatus::InProgress, SpecStatus::Archived)] },
            SectionType::Architecture => return SectionConfig::for_arch_designs(st),
            SectionType::Designs => return SectionConfig::for_arch_designs(st),
            SectionType::Plans => return SectionConfig { section_type: st, allowed_statuses: vec![SpecStatus::Empty, SpecStatus::Draft, SpecStatus::Approved, SpecStatus::InProgress, SpecStatus::Done, SpecStatus::Obsolete], allowed_transitions: vec![(SpecStatus::Empty, SpecStatus::Draft), (SpecStatus::Draft, SpecStatus::Approved), (SpecStatus::Approved, SpecStatus::InProgress), (SpecStatus::InProgress, SpecStatus::Done), (SpecStatus::Done, SpecStatus::Obsolete)] },
            SectionType::Tests => return SectionConfig { section_type: st, allowed_statuses: vec![SpecStatus::Empty, SpecStatus::Draft, SpecStatus::Implemented, SpecStatus::Done, SpecStatus::Verified, SpecStatus::Blocked], allowed_transitions: vec![(SpecStatus::Empty, SpecStatus::Draft), (SpecStatus::Draft, SpecStatus::Implemented), (SpecStatus::Implemented, SpecStatus::Done), (SpecStatus::Done, SpecStatus::Verified), (SpecStatus::Implemented, SpecStatus::Blocked), (SpecStatus::Blocked, SpecStatus::Implemented)] },
            SectionType::Reviews => return SectionConfig::for_reviews_reports(st),
            SectionType::Reports => return SectionConfig::for_reviews_reports(st),
        };
    }
    pub fn for_arch_designs(st: SectionType) -> SectionConfig {
        return SectionConfig { section_type: st, allowed_statuses: vec![SpecStatus::Empty, SpecStatus::Draft, SpecStatus::UnderReview, SpecStatus::Approved, SpecStatus::Rejected, SpecStatus::Superseded, SpecStatus::Outdated], allowed_transitions: vec![(SpecStatus::Empty, SpecStatus::Draft), (SpecStatus::Draft, SpecStatus::UnderReview), (SpecStatus::UnderReview, SpecStatus::Approved), (SpecStatus::UnderReview, SpecStatus::Rejected), (SpecStatus::Approved, SpecStatus::Superseded), (SpecStatus::Approved, SpecStatus::Outdated)] };
    }
    pub fn for_reviews_reports(st: SectionType) -> SectionConfig {
        return SectionConfig { section_type: st, allowed_statuses: vec![SpecStatus::Empty, SpecStatus::Draft, SpecStatus::Published], allowed_transitions: vec![(SpecStatus::Empty, SpecStatus::Draft), (SpecStatus::Draft, SpecStatus::Published)] };
    }
    pub fn can_transition(&self, from_status: SpecStatus, to_status: SpecStatus) -> bool {
        if from_status == to_status {
            return true;
        }
        for pair in &self.allowed_transitions {
            if pair.0.clone() == from_status {
                if pair.1.clone() == to_status {
                    return true;
                }            }
        }
        return false;
    }
}

/// The state machine for a given section type.
/// Is `from_status -> to_status` a legal transition? Idempotent (equal)
/// always allowed; otherwise the pair must be in allowed_transitions.
/// A22: `from`/`to` 是 Auto 保留字 — 参数名改为 from_status/to_status。
/// A7: .contains((tuple)) 不支持 — 改用 for 循环逐对比较。
/// Collect all spec item IDs present in the document (across all sections).
fn all_ids(doc: SpecsDocument) -> HashSet<String> {
    let mut set: HashSet<String> = HashSet::new();
    for section in doc.sections {
        for item in section.items {
            set.insert(item.id.clone().to_string());
        }
    }
    return set;
}

/// Scan text for references to known item IDs (deduped). Only references to
/// IDs that actually exist in known are kept.
fn scan_refs(text: &str, known: HashSet<String>) -> Vec<String> {
    let mut refs: Vec<String> = vec![];
    for id in known {
        if text.contains(id.as_str()) {
            refs.push(id.clone());
        }
    }
    refs.sort();
    return refs;
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct ReverseEntry {
    pub target_id: String,
    pub referrers: Vec<String>,
}

/// Linear lookup: find or create the ReverseEntry for target_id in the list.
/// (replaces HashMap.entry(); a2r-10 blocks HashMap on composite generics.)
fn upsert_reverse(entries: Vec<ReverseEntry>, target_id: &str) -> ReverseEntry {
    for e in entries.clone() {
        if e.target_id == target_id {
            return e;
        }
    }
    let fresh: ReverseEntry = ReverseEntry { target_id: target_id.clone().to_string(), referrers: vec![] };
    return fresh;
}

/// Rebuild every item's derived `related` field (reverse-links).
/// For each forward edge A -> B (from depends_on + content-scanned refs),
/// B's related list gains A. After scan, each related list is sorted+deduped.
#[derive(Clone, Debug)]
struct Snap {
    pub id: String,
    pub section_type: SectionType,
    pub status: SpecStatus,
    pub related: Vec<String>,
}

/// Linear lookup in the snap list by id — returns Option<Snap> (owned clone).
/// 用 List 线性查找替代 HashMap.get（a2r-10: HashMap 复合泛型方法调用有缺陷）。
fn find_snap(snap: Vec<Snap>, id: &str) -> Option<Snap> {
    for s in snap {
        if s.id == id {
            return Some(s.clone());
        }
    }
    return None;
}

fn is_goal_advanceable(s: SpecStatus) -> bool {
    match s {
        SpecStatus::Empty => return true,
        SpecStatus::Proposed => return true,
        SpecStatus::Analysed => return true,
        SpecStatus::Approved => return true,
        SpecStatus::InProgress => return true,
        _ => return false,
    };
}

fn is_test_done(s: SpecStatus) -> bool {
    match s {
        SpecStatus::Done => return true,
        SpecStatus::Verified => return true,
        _ => return false,
    };
}

fn is_test_pending(s: SpecStatus) -> bool {
    match s {
        SpecStatus::Done => return false,
        SpecStatus::Verified => return false,
        _ => return true,
    };
}

/// The "done-ish" terminal status for a section type (used by aggregate rule).
fn section_complete_status(st: SectionType) -> SpecStatus {
    match st {
        SectionType::Goals => return SpecStatus::Archived,
        SectionType::Architecture => return SpecStatus::Approved,
        SectionType::Designs => return SpecStatus::Approved,
        SectionType::Plans => return SpecStatus::Done,
        SectionType::Tests => return SpecStatus::Verified,
        SectionType::Reviews => return SpecStatus::Published,
        SectionType::Reports => return SpecStatus::Published,
    };
}

/// Derive (auto-advance) statuses from the relation graph (see plan 014).
/// WORKAROUND for a2r-11 (no mutable-borrow iteration / in-place nested
/// mutation): instead of mutating item.status in place, build NEW lists of
/// sections/items with updated statuses and whole-field reassign
/// self.sections at the end (a2r handles `self.field = new_list` fine).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SectionOverview {
    pub id: String,
    pub section_type: SectionType,
    pub title: String,
    pub status: SpecStatus,
    pub item_count: u32,
    pub status_counts: Vec<(String, u32)>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SpecsOverview {
    pub project: String,
    pub version: u64,
    pub total_items: u32,
    pub sections: Vec<SectionOverview>,
}

/// Build an aggregate overview (per-section item counts + status dist).
/// A file-backed spec store. The whole document is serialized to one JSON file.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct SpecsStore {
    pub path: PathBuf,
}

impl SpecsStore {
    pub fn new(path: PathBuf) -> SpecsStore {
        return SpecsStore { path: path };
    }
    pub fn load(&self) -> SpecsDocument {
        let read_result = fs::read(self.path.clone());
        match read_result {
            Ok(bytes) => {
                let parse_result = from_slice(&bytes);
                match parse_result {
                    Ok(doc) => return doc,
                    Err(e) => return SpecsDocument::new("project"),
                };
            },
            Err(e) => {
                

                let doc: SpecsDocument = SpecsDocument::new("project");
                self.save(doc.clone());
                return doc;
            },
        };
    }
    pub fn save(&self, doc: SpecsDocument) {

        let parent = self.path.parent();
        match parent {
            Some(p) => {
                let mkdir_result = fs::create_dir_all(p.clone());
                match mkdir_result {
                    Ok(ok) => {},
                    Err(e) => {},
                };
            },
            None => {},
        };



        let json_result = to_string_pretty(&doc);
        match json_result {
            Ok(json) => {
                


                std::fs::write(self.path.to_str().unwrap(), json.as_str()).is_ok();
            },
            Err(e) => {},
        };
    }
    pub fn upsert_item(&self, doc: SpecsDocument, section_id: &str, item: SpecItem) -> Option<SpecsDocument> {
        let mut section_found: bool = false;
        let mut new_sections: Vec<SpecsSection> = vec![];
        for s in doc.sections.clone() {
            if s.id == section_id {
                section_found = true;
                

                let mut item_found: bool = false;
                let mut new_items: Vec<SpecItem> = vec![];
                for existing in s.items.clone() {
                    if existing.id == item.id {
                        item_found = true;
                        new_items.push(item.clone())
                    } else {
                        new_items.push(existing.clone())
                    }

                }
                if item_found == false {
                    new_items.push(item.clone());
                }                let now: u64 = now_sec();
                let updated_section: SpecsSection = SpecsSection { id: s.id.clone().to_string(), section_type: s.section_type, title: s.title.clone().to_string(), items: new_items, status: s.status, content: s.content.clone().to_string(), depends_on: s.depends_on.clone(), last_modified: now, last_verified: s.last_verified.clone() };
                new_sections.push(updated_section.clone())
            } else {
                new_sections.push(s.clone())
            }

        }
        if section_found == false {
            return None;
        }

        let mut new_doc: SpecsDocument = SpecsDocument { project: doc.project.clone().to_string(), version: doc.version + 1, sections: new_sections };
        new_doc.rebuild_relations();
        new_doc.derive_statuses();
        return Some(new_doc);
    }
    pub fn transition_item(&self, doc: SpecsDocument, section_id: &str, item_id: &str, new_status: SpecStatus) -> Option<SpecsDocument> {
        let mut section_found: bool = false;
        let mut new_sections: Vec<SpecsSection> = vec![];
        let mut transition_ok: bool = false;
        for s in doc.sections.clone() {
            if s.id == section_id {
                section_found = true;
                let cfg: SectionConfig = SectionConfig::for_type(s.section_type);
                let mut new_items: Vec<SpecItem> = vec![];
                for it in s.items.clone() {
                    if it.id == item_id {
                        if cfg.can_transition(it.status, new_status) {
                            transition_ok = true;
                            let now: u64 = now_sec();
                            let mut completed: Option<u64> = it.completed_at.clone();
                            if new_status == SpecStatus::Done {
                                completed = Some(now)
                            }                            let updated: SpecItem = SpecItem { id: it.id.clone().to_string(), title: it.title.clone().to_string(), content: it.content.clone().to_string(), status: new_status, depends_on: it.depends_on.clone(), related: it.related.clone(), priority: it.priority.clone(), assignee: it.assignee.clone(), test_file: it.test_file.clone(), file: it.file.clone(), milestone: it.milestone.clone(), module: it.module.clone(), tags: it.tags.clone(), created_at: it.created_at, modified_at: now, completed_at: completed };
                            new_items.push(updated.clone())
                        } else {
                            new_items.push(it.clone())
                        }
                    } else {
                        new_items.push(it.clone())
                    }

                }
                let now: u64 = now_sec();
                let updated_section: SpecsSection = SpecsSection { id: s.id.clone().to_string(), section_type: s.section_type, title: s.title.clone().to_string(), items: new_items, status: s.status, content: s.content.clone().to_string(), depends_on: s.depends_on.clone(), last_modified: now, last_verified: s.last_verified.clone() };
                new_sections.push(updated_section.clone())
            } else {
                new_sections.push(s.clone())
            }

        }
        if section_found == false {
            return None;
        }
        if transition_ok == false {
            return None;
        }
        let new_doc: SpecsDocument = SpecsDocument { project: doc.project.clone().to_string(), version: doc.version + 1, sections: new_sections };
        return Some(new_doc);
    }
    pub fn delete_item(&self, doc: SpecsDocument, section_id: &str, item_id: &str) -> Option<SpecsDocument> {
        let mut section_found: bool = false;
        let mut any_removed: bool = false;
        let mut new_sections: Vec<SpecsSection> = vec![];
        for s in doc.sections.clone() {
            if s.id == section_id {
                section_found = true;
                let mut new_items: Vec<SpecItem> = vec![];
                for it in s.items.clone() {
                    if it.id == item_id {
                        any_removed = true
                    } else {
                        new_items.push(it.clone())
                    }

                }
                if any_removed {
                    let now: u64 = now_sec();
                    let updated_section: SpecsSection = SpecsSection { id: s.id.clone().to_string(), section_type: s.section_type, title: s.title.clone().to_string(), items: new_items, status: s.status, content: s.content.clone().to_string(), depends_on: s.depends_on.clone(), last_modified: now, last_verified: s.last_verified.clone() };
                    new_sections.push(updated_section.clone())
                } else {
                    new_sections.push(s.clone())
                }
            } else {
                new_sections.push(s.clone())
            }

        }
        if section_found == false {
            return None;
        }
        if any_removed == false {
            return None;
        }
        let mut new_doc: SpecsDocument = SpecsDocument { project: doc.project.clone().to_string(), version: doc.version + 1, sections: new_sections };
        new_doc.rebuild_relations();
        new_doc.derive_statuses();
        return Some(new_doc);
    }
    pub fn drift_check(&self, doc: SpecsDocument) -> Option<(u64, bool)> {
        let disk: SpecsDocument = self.load();
        let drifted: bool = disk.version != doc.version;
        return Some((disk.version, drifted));
    }
}
