use super::extern_impl::*;
// Auto-generated by a2r transpiler

use serde_json::Value;
#[async_trait::async_trait]
trait Tool {
    fn name(&self) -> String;
    fn description(&self) -> String;
    fn parameters(&self) -> Value;
    async fn execute(&self, args: Value) -> Result<String, ToolError>;
}


/// spec_tools.at — 5 个 spec Tool impl (spec_tools.rs). 同 tools.at 模式。
#[derive(Clone, Debug, PartialEq)]
struct ReadSpecs {}

#[async_trait::async_trait]
impl Tool for ReadSpecs {
    fn name(&self) -> String {
        return "read_specs".to_string();
    }
    fn description(&self) -> String {
        return "Read spec sections".to_string();
    }
    fn parameters(&self) -> Value {
        return parse_json(read_specs_schema);
    }
    async fn execute(&self, args: Value) -> Result<String, ToolError> {
        let section = value_get_str(args, "section");
        let result = specs_read(section);
        return Ok(result);
    }
}

#[derive(Clone, Debug, PartialEq)]
struct ListSpecs {}

#[async_trait::async_trait]
impl Tool for ListSpecs {
    fn name(&self) -> String {
        return "list_specs".to_string();
    }
    fn description(&self) -> String {
        return "List all spec sections".to_string();
    }
    fn parameters(&self) -> Value {
        return parse_json(list_specs_schema);
    }
    async fn execute(&self, args: Value) -> Result<String, ToolError> {
        let result = specs_list();
        return Ok(result);
    }
}

#[derive(Clone, Debug, PartialEq)]
struct WriteSpec {}

#[async_trait::async_trait]
impl Tool for WriteSpec {
    fn name(&self) -> String {
        return "write_spec".to_string();
    }
    fn description(&self) -> String {
        return "Write a spec section".to_string();
    }
    fn parameters(&self) -> Value {
        return parse_json(write_spec_schema);
    }
    async fn execute(&self, args: Value) -> Result<String, ToolError> {
        let section = value_get_str(args, "section");
        let content = value_get_str(args, "content");
        let result = specs_write(section, content);
        return Ok(result);
    }
}

#[derive(Clone, Debug, PartialEq)]
struct UpdateSpec {}

#[async_trait::async_trait]
impl Tool for UpdateSpec {
    fn name(&self) -> String {
        return "update_spec".to_string();
    }
    fn description(&self) -> String {
        return "Update a spec item".to_string();
    }
    fn parameters(&self) -> Value {
        return parse_json(update_spec_schema);
    }
    async fn execute(&self, args: Value) -> Result<String, ToolError> {
        let action = value_get_str(args, "action");
        let section = value_get_str(args, "section");
        let result = specs_update(action, section, args);
        return Ok(result);
    }
}

#[derive(Clone, Debug, PartialEq)]
struct WriteGoals {}

#[async_trait::async_trait]
impl Tool for WriteGoals {
    fn name(&self) -> String {
        return "write_goals".to_string();
    }
    fn description(&self) -> String {
        return "Write goals section".to_string();
    }
    fn parameters(&self) -> Value {
        return parse_json(write_goals_schema);
    }
    async fn execute(&self, args: Value) -> Result<String, ToolError> {
        let goals = value_get_str(args, "goals");
        let result = specs_write_goals(goals);
        return Ok(result);
    }
}

fn main() {
    let read_specs_schema: String = format!("{{\"type\":\"object\",\"properties\":{{\"section\":{{\"type\":\"string\"}}}}");;
    let list_specs_schema: String = format!("{{\"type\":\"object\"}}");;
    let write_spec_schema: String = format!("{{\"type\":\"object\",\"properties\":{{\"section\":{{\"type\":\"string\"}},\"content\":{{\"type\":\"string\"}},\"required\":[\"section\",\"content\"]}}");;
    let update_spec_schema: String = format!("{{\"type\":\"object\",\"properties\":{{\"action\":{{\"type\":\"string\"}},\"section\":{{\"type\":\"string\"}},\"item_id\":{{\"type\":\"string\"}},\"required\":[\"action\",\"section\"]}}");;
    let write_goals_schema: String = format!("{{\"type\":\"object\",\"properties\":{{\"goals\":{{\"type\":\"string\"}},\"required\":[\"goals\"]}}");;
}
