use super::extern_impl::*;
// Auto-generated by a2r transpiler

use std::collections::HashMap;
use std::path::PathBuf;
use std::fs;
use serde::Serialize;
use crate::auto_generated::task_plan::TaskPlan;
use crate::auto_generated::relay_flows::get_builtin_flow;
use crate::auto_generated::task_plan_parser::parse_task_plan;
/// task_plan_registry.at — port of backend/crates/musk/src/relay/task_plan_registry.rs
/// (Plan 020 Phase B)。对齐 hw 306 行。
/// 
/// 移植策略:
/// - TaskPlanSource / TaskPlanSummary / RegistryEntry(hw 的
/// `(TaskPlan, TaskPlanSource)` 元组 → 具名 struct)全移植。
/// - TaskPlanRegistry(HashMap + user_dir,Mutex 在 WorkspaceStores 外层)全移植:
/// new / get / source / list / insert / remove / validate / register /
/// load_builtin / load_from_dir。
/// - 2 个副作用 extern:task_plan_builtin_atom(include_str 内建 atom)、
/// task_plan_delete_file(fs::remove_file)。
/// - fs.write / create_dir_all 经 a2r 桥(nativeize 重写为 .is_ok()/原生)——
/// 错误文本丢失但 Err/Ok 行为保留(文档化偏差)。
/// - parse_task_plan / get_builtin_flow 跨模块调用 ag 版(全链路 Auto)。
/// Source of a TaskPlan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum TaskPlanSource {
    Builtin = 0,
    User = 1,
}

impl std::fmt::Display for TaskPlanSource {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            TaskPlanSource::Builtin => write!(f, "Builtin"),
            TaskPlanSource::User => write!(f, "User"),
        }
    }
}
impl TaskPlanSource {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Builtin" | "builtin" => TaskPlanSource::Builtin,
            "User" | "user" => TaskPlanSource::User,
            _ => TaskPlanSource::Builtin
        }
    }
}

/// Summary returned by `list`。
#[derive(Debug, Clone, Serialize)]
pub struct TaskPlanSummary {
    pub id: String,
    pub source: TaskPlanSource,
    pub phase_count: i32,
    pub run_count: i32,
}

/// plans 映射的值(hw `(TaskPlan, TaskPlanSource)` 元组;a2r 无 tuple 字段)。
#[derive(Debug, Clone)]
pub struct RegistryEntry {
    pub plan: TaskPlan,
    pub source: TaskPlanSource,
}

/// Registry of all available TaskPlans (built-in + user-defined) for one workspace.
#[derive(Debug, Clone)]
pub struct TaskPlanRegistry {
    pub plans: HashMap<String, RegistryEntry>,
    pub user_dir: PathBuf,
}

impl TaskPlanRegistry {
    pub fn new(data_dir: PathBuf) -> TaskPlanRegistry {
        let user_dir = data_dir.join("task_plans");
        let mut registry = TaskPlanRegistry { plans: HashMap::new(), user_dir: user_dir };
        registry.load_builtin();
        registry.load_from_dir();
        return registry;
    }
    pub fn load_builtins_only() -> TaskPlanRegistry {
        let mut registry = TaskPlanRegistry { plans: HashMap::new(), user_dir: PathBuf::new() };
        registry.load_builtin();
        return registry;
    }
    pub fn get(&self, plan_id: &str) -> Option<TaskPlan> {
        match self.plans.get(plan_id) {
            Some(entry) => return Some(entry.plan.clone()),
            None => return None,
        }
    }
    pub fn source(&self, plan_id: &str) -> Option<TaskPlanSource> {
        match self.plans.get(plan_id) {
            Some(entry) => return Some(entry.source),
            None => return None,
        }
    }
    pub fn list(&self) -> Vec<TaskPlanSummary> {
        let mut summaries: Vec<TaskPlanSummary> = vec![];
        for entry in self.plans.values() {
            let mut run_count: i32 = 0;
            for phase in entry.plan.phases.clone() {
                run_count = run_count + (phase.runs.len() as i32);
            }
            summaries.push(TaskPlanSummary { id: entry.plan.id.clone().to_string(), source: entry.source, phase_count: (entry.plan.phases.len() as i32), run_count: run_count });
        }
        return summaries;
    }
    pub fn insert(&mut self, plan: TaskPlan, source: TaskPlanSource) {
        self.plans.insert(plan.id.clone(), RegistryEntry { plan: plan, source: source });
    }
    pub fn remove(&mut self, plan_id: &str) -> Option<TaskPlan> {
        match self.plans.get(plan_id) {
            None => return None,
            Some(entry) => {
                match entry.source {
                    TaskPlanSource::Builtin => return None,
                    TaskPlanSource::User => {
                        let removed = self.plans.remove(plan_id);
                        

                        let path = self.user_dir.join(format!("{}{}", plan_id.clone(), ".atom"));
                        task_plan_delete_file(path);
                        match removed {
                            Some(e) => return Some(e.plan),
                            None => return None,
                        };
                    },
                };
            },
        }
    }
    pub fn validate(&self, plan: TaskPlan) -> Result<(), String> {
        match plan.validate() {
            Err(e) => return Err(e.to_string()),
            Ok(_) => {},
        };
        for phase in plan.phases.clone() {
            for run in phase.runs.clone() {
                match get_builtin_flow(&run.flow_id) {
                    Some(_) => {},
                    None => return Err(format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "run '", run.name), "' references unknown flow '"), run.flow_id), "'")),
                };
            }
        }
        return Ok(());
    }
    pub fn register(&mut self, atom: &str) -> Result<TaskPlan, String> {
        let parsed = parse_task_plan(&atom);
        let mut plan: TaskPlan = TaskPlan::new("");
        match parsed {
            Err(e) => return Err(e),
            Ok(p) => plan = p,
        };
        match self.validate(plan.clone()) {
            Err(e) => return Err(e),
            Ok(_) => {},
        };

        if (self.user_dir.as_os_str().len() as i32) > 0 {
            match fs::create_dir_all(self.user_dir.clone()) {
                Err(_) => return Err("failed to create task_plans directory".into()),
                Ok(_) => {},
            };
            let path = self.user_dir.join(format!("{}{}", plan.id.clone(), ".atom"));
            let ok = task_plan_write_atom(path, atom);
            if ok == false {
                return Err("failed to write plan file".into());
            }        }

        self.plans.insert(plan.id.clone(), RegistryEntry { plan: plan.clone(), source: TaskPlanSource::User });
        return Ok(plan);
    }
    pub fn load_builtin(&mut self) {
        let atom = task_plan_builtin_atom();
        let parsed = parse_task_plan(&atom);
        match parsed {
            Err(_) => {},
            Ok(plan) => {
                match plan.validate() {
                    Err(e) => {},
                    Ok(_) => {
                        self.plans.insert(plan.id.clone(), RegistryEntry { plan: plan, source: TaskPlanSource::Builtin });
                        return;
                    },
                };
            },
        };
    }
    pub fn load_from_dir(&mut self) {
        if self.user_dir.is_dir() == false {
            return;
        }
        let dir_res = fs::read_dir(self.user_dir.clone());
        match dir_res {
            Err(_) => return,
            Ok(dir) => {
                for entry in dir.flatten() {
                    let path = entry.path();
                    let ext = path_extension_str(path.clone());
                    if ext != "atom" {
                        continue;
                    }
                    let content_res = task_plan_read_file(path.clone());
                    match content_res {
                        Err(_) => {},
                        Ok(content) => {
                            let parsed = parse_task_plan(&content);
                            match parsed {
                                Err(_) => {},
                                Ok(plan) => {
                                    match self.validate(plan.clone()) {
                                        Err(_) => {},
                                        Ok(_) => {
                                            self.plans.insert(plan.id.clone(), RegistryEntry { plan: plan, source: TaskPlanSource::User });
                                            return;
                                        },
                                    };
                                },
                            };
                        },
                    };
                }
            },
        };
    }
}