use super::extern_impl::*;
// Auto-generated by a2r transpiler

use std::collections::{HashMap, HashSet};
use std::sync::Arc;
use serde::{Serialize, Deserialize};
use serde_json::Value;
use serde_json::to_value;
use crate::server::AppState;
use crate::relay::handoff_store::HandoffStore;
use crate::auto_generated::task_plan::{Phase, PhaseMode, RunRef, TaskMode, TaskPlan};
use crate::auto_generated::relay_flows::get_builtin_flow;
use auto_ai_agent::orchestration::HandoffDocument;
/// task_plan_engine.at — port of backend/crates/musk/src/relay/task_plan_engine.rs
/// (Plan 020 Phase B: TaskPlan 引擎层 .at 移植)。对齐 hw 672 行。
/// 
/// 移植策略:
/// - 全部数据类型 + 纯逻辑移植:TaskPlanContext / RunRequest /
/// RunExecutionResult / TaskPlanStatus / PhaseStatus / PhaseState /
/// TaskPlanRunState / TaskPlanEngine + new / validate / topological_order
/// (迭代 DFS,与 hw 递归 dfs 同序)/ build_run_request / set_phase_status /
/// broadcast。
/// - execute 的 pluggable executor(hw 闭包参数 F: Fn(RunRequest) -> Fut)以
/// pub spec TaskPlanExecutor(#[async_trait]) 表达:execute 接收
/// Arc<dyn TaskPlanExecutor>,生产/测试分别以 hw 结构实现该 trait。
/// - hw 并行 phase 是"先建 future 再逐个 await"——无真并发,顺序 await 与
/// 串行等价 → .at 统一按序 run_one(hw build_run_request 纯读,惰性构建
/// 不可观测)。
/// - 3 个副作用 extern:task_plan_uuidish(hex 纳秒)、task_plan_broadcast
/// (SSE bus)、handoff_resolve_path(HandoffStore 读取)。
/// - 事件 payload 用单一 DTO(Option 字段 skip-none),与 hw json! 逐键等价。
/// Shared context needed to execute a TaskPlan instance (hw TaskPlanContext)。
#[derive(Clone)]
pub struct TaskPlanContext {
    pub state: AppState,
    pub workspace_id: String,
}

/// A request to execute a single relay run inside a TaskPlan.
#[derive(Clone, Debug)]
pub struct RunRequest {
    pub task_plan_id: String,
    pub phase_name: String,
    pub phase_index: u32,
    pub run_ref: RunRef,
    pub run_id: String,
    pub parent_run_id: Option<String>,
    pub root_run_id: String,
    pub task_text: String,
    pub mode: TaskMode,
}

/// Result of executing a single relay run.
#[derive(Clone, Debug)]
pub struct RunExecutionResult {
    pub run_id: String,
    pub status: String,
    pub handoff: Option<HandoffDocument>,
    pub error: Option<String>,
}

/// Terminal status string from the run store (e.g. "completed", "failed").
/// Overall status of a TaskPlan execution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TaskPlanStatus {
    Pending = 0,
    Running = 1,
    Completed = 2,
    Failed = 3,
    Paused = 4,
}

impl std::fmt::Display for TaskPlanStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            TaskPlanStatus::Pending => write!(f, "Pending"),
            TaskPlanStatus::Running => write!(f, "Running"),
            TaskPlanStatus::Completed => write!(f, "Completed"),
            TaskPlanStatus::Failed => write!(f, "Failed"),
            TaskPlanStatus::Paused => write!(f, "Paused"),
        }
    }
}
impl TaskPlanStatus {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Pending" | "pending" => TaskPlanStatus::Pending,
            "Running" | "running" => TaskPlanStatus::Running,
            "Completed" | "completed" => TaskPlanStatus::Completed,
            "Failed" | "failed" => TaskPlanStatus::Failed,
            "Paused" | "paused" => TaskPlanStatus::Paused,
            _ => TaskPlanStatus::Pending
        }
    }
}

/// Status of an individual phase within a TaskPlan execution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PhaseStatus {
    Pending = 0,
    Running = 1,
    Completed = 2,
    Failed = 3,
}

impl std::fmt::Display for PhaseStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            PhaseStatus::Pending => write!(f, "Pending"),
            PhaseStatus::Running => write!(f, "Running"),
            PhaseStatus::Completed => write!(f, "Completed"),
            PhaseStatus::Failed => write!(f, "Failed"),
        }
    }
}
impl PhaseStatus {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Pending" | "pending" => PhaseStatus::Pending,
            "Running" | "running" => PhaseStatus::Running,
            "Completed" | "completed" => PhaseStatus::Completed,
            "Failed" | "failed" => PhaseStatus::Failed,
            _ => PhaseStatus::Pending
        }
    }
}

/// Per-phase execution state.
#[derive(Debug, Clone)]
pub struct PhaseState {
    pub status: PhaseStatus,
    pub run_results: HashMap<String, RunExecutionResult>,
}

/// Per-run execution state tracked by the engine.
#[derive(Debug, Clone)]
pub struct TaskPlanRunState {
    pub run_id: String,
    pub phase_name: String,
    pub run_name: String,
    pub status: String,
    pub handoff: Option<HandoffDocument>,
}

/// Deterministic executor for TaskPlan instances.
#[derive(Debug, Clone)]
pub struct TaskPlanEngine {
    pub plan: TaskPlan,
    pub instance_id: String,
    pub initial_input: String,
    pub status: TaskPlanStatus,
    pub phase_states: HashMap<String, PhaseState>,
    pub run_states: HashMap<String, TaskPlanRunState>,
}

impl TaskPlanEngine {
    pub fn new(plan: TaskPlan, initial_input: &str) -> TaskPlanEngine {
        let instance_id: String = format!("{}{}", format!("{}{}", plan.id.clone(), "-"), task_plan_uuidish());
        let mut phase_states: HashMap<String, PhaseState> = HashMap::new();
        for phase in plan.phases.clone() {
            phase_states.insert(phase.name.clone(), PhaseState { status: PhaseStatus::Pending, run_results: HashMap::new() });
        }
        return TaskPlanEngine { plan: plan, instance_id: instance_id.to_string(), initial_input: initial_input.to_string(), status: TaskPlanStatus::Pending, phase_states: phase_states, run_states: HashMap::new() };
    }
    pub fn validate(&self) -> Result<(), String> {
        match self.plan.validate() {
            Err(e) => return Err(e.to_string()),
            Ok(_) => {},
        };
        for phase in self.plan.phases.clone() {
            for run in phase.runs.clone() {
                match get_builtin_flow(&run.flow_id) {
                    Some(_) => {},
                    None => return Err(format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "run '", run.name), "' references unknown flow '"), run.flow_id), "'")),
                };
            }
        }
        return Ok(());
    }
    pub async fn execute(&mut self, handoffs: HandoffStore, executor: Arc<dyn TaskPlanExecutor>) -> Result<(), String> {
        match self.validate() {
            Err(e) => return Err(e),
            Ok(_) => {},
        };

        self.status = TaskPlanStatus::Running;
        task_plan_broadcast(&self.instance_id, "task_plan_started", to_value(TaskPlanEvtPayload { task_plan_id: self.plan.id.clone().to_string(), instance_id: self.instance_id.clone().to_string(), phase: None, mode: None, run: None, run_id: None, status: None, error: None }).unwrap());

        let order_result = self.topological_order();
        let mut order: Vec<String> = vec![];
        match order_result {
            Err(e) => return Err(e),
            Ok(o) => order = o,
        };

        for phase_name in &order {
            let phase = self.find_phase(&phase_name);
            let mut phase_obj: Phase = Phase::new("");
            let mut have_phase: bool = true;
            match phase {
                None => return Err(format!("{}{}", format!("{}{}", "phase '", phase_name), "' disappeared")),
                Some(p) => phase_obj = p,
            };
            
            self.set_phase_status(&phase_obj.name, PhaseStatus::Running);
            task_plan_broadcast(&self.instance_id, "phase_started", to_value(TaskPlanEvtPayload { task_plan_id: self.plan.id.clone().to_string(), instance_id: self.instance_id.clone().to_string(), phase: Some(phase_obj.name.clone()), mode: Some(phase_mode_str(phase_obj.mode)), run: None, run_id: None, status: None, error: None }).unwrap());
            
            let phase_index = self.find_phase_index(&phase_obj.name);
            let run_refs = phase_obj.runs.clone();
            

            let mut run_names: Vec<String> = vec![];
            let mut run_results: Vec<RunExecutionResult> = vec![];
            for run_ref in &run_refs {
                


                let mut resolved_inputs: Vec<String> = vec![];
                for path in run_ref.input_from.clone() {
                    let full_path = format!("{}{}", format!("{}{}", self.plan.id.clone(), "."), path);
                    match handoff_resolve_path(&&handoffs, &&full_path) {
                        Some(value) => resolved_inputs.push(format!("{}{}", format!("{}{}", format!("{}{}", "## Input from ", path), "\n\n"), value)),
                        None => resolved_inputs.push(format!("{}{}", format!("{}{}", "## Input from ", path), "\n\n(resolved value missing)")),
                    };
                }
                let req = self.build_run_request(phase_obj.clone(), phase_index, run_ref.clone(), resolved_inputs);
                let one = self.run_one(executor.clone(), req).await;
                match one {
                    Err(e) => return Err(e),
                    Ok(r) => {
                        run_names.push(run_ref.name.clone());
                        run_results.push(r.clone());
                    },
                };
            }
            
            let mut phase_failed: bool = false;
            let mut failure_error: Option<String> = None;
            let mut i: u32 = 0 as u32;
            for run_name in run_names.clone() {
                
                let run_name_owned = run_name.clone();
                let result = run_results[(i) as usize].clone().clone();
                if result.status.to_string() != "completed" {
                    phase_failed = true;
                    let default_msg: String = format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "run '", run_name), "' ended with status '"), result.status), "'");
                    match result.error {
                        Some(e) => failure_error = Some(e),
                        None => failure_error = Some(default_msg),
                    };
                }
                match result.handoff.clone() {
                    Some(h) => {
                        match handoffs.save(&self.plan.id, &phase_obj.name, &run_name, &h) {
                            Ok(_) => {},
                            Err(e) => {},
                        };
                    },
                    None => {},
                };
                self.run_states.insert(result.run_id.clone(), TaskPlanRunState { run_id: result.run_id.clone().to_string(), phase_name: phase_obj.name.clone().to_string(), run_name: run_name_owned.to_string(), status: result.status.clone().to_string(), handoff: result.handoff.clone() });
                i = i + 1;
            }
            

            match self.phase_states.get(&phase_obj.name) {
                Some(state) => {
                    let mut new_state = state.clone();
                    let mut j: u32 = 0 as u32;
                    for run_name in run_names.clone() {
                        new_state.run_results.insert(run_name, run_results[(j) as usize].clone().clone());
                        j = j + 1;
                    }
                    self.phase_states.insert(phase_obj.name.clone(), new_state.clone());
                },
                None => {},
            };
            
            if phase_failed {
                self.set_phase_status(&phase_obj.name, PhaseStatus::Failed);
                let error = failure_error.unwrap_or_default();
                task_plan_broadcast(&self.instance_id, "phase_failed", to_value(TaskPlanEvtPayload { task_plan_id: self.plan.id.clone().to_string(), instance_id: self.instance_id.clone().to_string(), phase: Some(phase_obj.name.clone()), mode: None, run: None, run_id: None, status: None, error: Some(error.clone()) }).unwrap());
                self.status = TaskPlanStatus::Failed;
                task_plan_broadcast(&self.instance_id, "task_plan_failed", to_value(TaskPlanEvtPayload { task_plan_id: self.plan.id.clone().to_string(), instance_id: self.instance_id.clone().to_string(), phase: Some(phase_obj.name.clone()), mode: None, run: None, run_id: None, status: None, error: Some(error.clone()) }).unwrap());
                return Err(error);
            }
            
            self.set_phase_status(&phase_obj.name, PhaseStatus::Completed);
            task_plan_broadcast(&self.instance_id, "phase_completed", to_value(TaskPlanEvtPayload { task_plan_id: self.plan.id.clone().to_string(), instance_id: self.instance_id.clone().to_string(), phase: Some(phase_obj.name.clone()), mode: None, run: None, run_id: None, status: None, error: None }).unwrap());
        }

        self.status = TaskPlanStatus::Completed;
        task_plan_broadcast(&self.instance_id, "task_plan_completed", to_value(TaskPlanEvtPayload { task_plan_id: self.plan.id.clone().to_string(), instance_id: self.instance_id.clone().to_string(), phase: None, mode: None, run: None, run_id: None, status: None, error: None }).unwrap());
        return Ok(());
    }
    pub async fn run_one(&self, executor: Arc<dyn TaskPlanExecutor>, req: RunRequest) -> Result<RunExecutionResult, String> {
        task_plan_broadcast(&self.instance_id, "run_started", to_value(TaskPlanEvtPayload { task_plan_id: self.plan.id.clone().to_string(), instance_id: self.instance_id.clone().to_string(), phase: Some(req.phase_name.clone()), mode: None, run: Some(req.run_ref.name.clone()), run_id: Some(req.run_id.clone()), status: None, error: None }).unwrap());

        let run_name = req.run_ref.name.clone();
        let phase_name = req.phase_name.clone();
        let result = executor.run(req).await;
        match result {
            Err(e) => return Err(format!("{}{}", "executor error: ", e)),
            Ok(r) => {
                task_plan_broadcast(&self.instance_id, "run_completed", to_value(TaskPlanEvtPayload { task_plan_id: self.plan.id.clone().to_string(), instance_id: self.instance_id.clone().to_string(), phase: Some(phase_name), mode: None, run: Some(run_name), run_id: Some(r.run_id.clone()), status: Some(r.status.clone()), error: None }).unwrap());
                return Ok(r);
            },
        }
    }
    pub fn build_run_request(&self, phase: Phase, phase_index: u32, run_ref: RunRef, resolved_inputs: Vec<String>) -> RunRequest {
        let run_id: String = format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", self.instance_id.clone(), "--"), phase.name), "--"), run_ref.name), "--"), task_plan_uuidish());

        let mut task_parts: Vec<String> = vec![];
        match run_ref.input.clone() {
            Some(input) => task_parts.push(input.clone()),
            None => {
                if phase_index == 0 {
                    task_parts.push(self.initial_input.clone());
                }
            },
        };

        let mut from_i: u32 = 0 as u32;
        for path in run_ref.input_from.clone() {
            let text = resolved_inputs[(from_i) as usize].clone().clone();
            task_parts.push(text.clone());
            from_i = from_i + 1;
        }

        match run_ref.context.clone() {
            Some(context) => task_parts.push(format!("{}{}", "## Context\n\n", context)),
            None => {},
        };


        let mut task_text: String = "".to_string();
        let mut first_part: bool = true;
        for part in task_parts.clone() {
            if first_part {
                task_text = part;
                first_part = false;
            } else {
                task_text = format!("{}{}", format!("{}{}", task_text, "\n\n"), part);
            }

        }

        let mut mode: TaskMode = self.plan.default_mode;
        match run_ref.mode_override.clone() {
            Some(m) => mode = m,
            None => {},
        };

        return RunRequest { task_plan_id: self.plan.id.clone().to_string(), phase_name: phase.name.clone().to_string(), phase_index: phase_index, run_ref: run_ref, run_id: run_id.to_string(), parent_run_id: None, root_run_id: self.instance_id.clone().to_string(), task_text: task_text.to_string(), mode: mode };
    }
    pub fn set_phase_status(&mut self, phase_name: &str, mut status: PhaseStatus) {
        match self.phase_states.get(phase_name.clone()) {
            Some(state) => {
                let mut new_state = state.clone();
                new_state.status = status;
                self.phase_states.insert(phase_name.to_string(), new_state.clone());
            },
            None => {},
        };
    }
    pub fn topological_order(&self) -> Result<Vec<String>, String> {
        let mut visited: HashSet<String> = HashSet::new();
        let mut on_stack: HashSet<String> = HashSet::new();
        let mut order: Vec<String> = vec![];

        for phase in self.plan.phases.clone() {
            if visited.contains(&phase.name.clone()) {
                continue;
            }
            
            let mut nodes: Vec<String> = vec![phase.name.clone()];
            let mut indices: Vec<i32> = vec![0];
            let _: bool = on_stack.insert(phase.name.clone());
            while (nodes.len() as i32) > 0 {
                let node = nodes[((nodes.len() as i32) - 1) as usize].clone().clone();
                let idx = indices[((indices.len() as i32) - 1) as usize].clone();
                let deps = self.dep_names(&node);
                if idx < (deps.len() as i32) {
                    

                    indices.pop();
                    indices.push(idx + 1);
                    let dependency = deps[(idx) as usize].clone();
                    if on_stack.contains(&dependency.clone()) {
                        return Err(format!("{}{}", format!("{}{}", "cycle detected at phase '", dependency), "'"));
                    }                    if visited.contains(&dependency.clone()) {
                        continue;
                    }                    nodes.push(dependency.clone());
                    indices.push(0);
                    let _: bool = on_stack.insert(dependency);
                } else {
                    

                    nodes.pop();
                    indices.pop();
                    let _: bool = on_stack.remove(&node);
                    let _: bool = visited.insert(node.clone());
                    order.push(node.clone());
                }

            }
        }
        return Ok(order);
    }
    pub fn dep_names(&self, name: &str) -> Vec<String> {
        for phase in self.plan.phases.clone() {
            if phase.name == name {
                return phase.depends_on.clone();
            }
        }
        return vec![];
    }
    pub fn find_phase(&self, name: &str) -> Option<Phase> {
        for phase in self.plan.phases.clone() {
            if phase.name == name {
                return Some(phase);
            }
        }
        return None;
    }
    pub fn find_phase_index(&self, name: &str) -> u32 {
        let mut i: u32 = 0 as u32;
        for phase in self.plan.phases.clone() {
            if phase.name == name {
                return i;
            }
            i = i + 1;
        }
        return 0;
    }
}

#[async_trait::async_trait]
pub trait TaskPlanExecutor {
    async fn run(&self, req: RunRequest) -> Result<RunExecutionResult, String>;
}


/// Pluggable single-run executor(hw execute 的 F: Fn(RunRequest) -> Fut)。
/// 生产/测试分别实现:生产用 drive_task_plan_run(hw,Phase F 接线),
/// parity 测试用假 executor。
#[derive(Serialize)]
pub struct TaskPlanEvtPayload {
    pub task_plan_id: String,
    pub instance_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phase: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub run: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub run_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// Create a new engine for a plan (hw new;instance_id = plan.id-uuidish)。
/// Validate that the plan can be executed (plan.validate + flow refs)。
/// Execute the plan to completion using the provided run executor。
/// Execute a single run through the supplied executor (hw run_one)。
/// Build the execution request for a single run。input_from 的解析结果
/// (已格式化的 "## Input from..." 文本)由 execute 传入 resolved_inputs
/// (与 run_ref.input_from 平行;hw 在方法内直接读 store,a2r 按值参数
/// 无法借出 store,故前移)。
/// Topological order(hw 递归 dfs 的迭代等价;同序 + 同 cycle 报错)。
/// PhaseMode → 小写字符串(hw `format!("{:?}", mode).to_lowercase()`)。
fn phase_mode_str(mode: PhaseMode) -> String {
    match mode {
        PhaseMode::Serial => return "serial".to_string(),
        PhaseMode::Parallel => return "parallel".to_string(),
    }
}

// ============================================================
// Plan 020 Phase H — RelayTaskPlanExecutor: ag 版单 run 执行内核
// (替代 hand-written DriveTaskPlanExecutor 透传 hw drive_task_plan_run)。
// 5 步顺序逻辑(等价 hw task_plan_engine.rs:472-513):start_run → drive_run
// (复用 Phase G 的 ag drive_run)→ 读 run status → 组装 RunExecutionResult。
// ============================================================

/// 携带 ctx 的 ag executor(字段对齐 hw TaskPlanContext)。声明为实现
/// TaskPlanExecutor;run 方法把 drive_task_plan_run 全在 ag 表达(经 extern
/// 委托 hw store + ag drive_run)。
#[derive(Clone)]
pub struct RelayTaskPlanExecutor {
    pub ctx: TaskPlanContext,
}

#[async_trait::async_trait]
impl TaskPlanExecutor for RelayTaskPlanExecutor {
    async fn run(&self, req: RunRequest) -> Result<RunExecutionResult, String> {
        // ctx.state is owned AppState; externs take &Arc<AppState> — wrap once.
        let state: std::sync::Arc<crate::server::AppState> = std::sync::Arc::new(self.ctx.state.clone());
        // 1. start_run:在 run store 注册一个 relay run(flow_id 来自 run_ref)。
        task_plan_start_run(&state, &self.ctx.workspace_id, &req.run_id, &req.run_ref.flow_id, &req.task_text);
        // 2. drive_run:复用 Phase G 的 ag drive_run(推进到终态)。
        let _ = drive_run(&state, &self.ctx.workspace_id, &req.run_id).await;
        // 3. 读回 run status;丢失则报错(hw:496-497)。
        let status_opt = task_plan_run_status(&state, &self.ctx.workspace_id, &req.run_id);
        match status_opt {
            None => return Err(format!("run {} disappeared after execution", req.run_id)),
            Some(status) => {
                // 4. status==completed → error=None;否则 error=Some(...)。
                let mut error_msg: Option<String> = None;
                if status != "completed" {
                    error_msg = Some(format!("run ended with status '{}'", status));
                }
                // 5. 读回 handoff;组装 RunExecutionResult(hw:505-513)。
                let handoff = task_plan_last_handoff(&state, &self.ctx.workspace_id, &req.run_id);
                return Ok(RunExecutionResult { run_id: req.run_id.to_string(), status: status.to_string(), handoff, error: error_msg });
            }
        }
    }
}