use super::extern_impl::*;
// Auto-generated by a2r transpiler

use auto_atom::*;
use auto_val::Node;
use auto_val::*;
use crate::auto_generated::task_plan::TaskPlan;
pub fn parse_task_plan(input: &str) -> Result<TaskPlan, String> {
    let parsed = AtomParser::parse(&input);
    match parsed {
        Err(e) => return Err(e.to_string()),
        Ok(atom) => {
            match atom {
                Atom::Node(node) => {
                    match TaskPlan::from_node(node) {
                        Err(e) => return Err(e.to_string()),
                        Ok(plan) => return Ok(plan),
                    };
                },
                _ => return Err(format!("{}{}", "invalid type: expected Node, found ", atom_debug_value(&atom))),
            };
        },
    }
}