use super::extern_impl::*;
// Auto-generated by a2r transpiler

use std::collections::{HashMap, HashSet};
use auto_atom::*;
use auto_val::*;
use serde::{Serialize, Deserialize};
/// task_plan.at — TaskPlan data model (relay/task_plan.rs) — Plan 018 Phase 3.3。
/// 
/// Ported from backend/crates/musk/src/relay/task_plan.rs. Scope:
/// - 数据模型 (TaskPlan/Phase/RunRef/TaskMode/PhaseMode) + builder + validate
/// + detect_cycle/dfs -> Auto
/// - Atom 解析 (impl TryFrom<Node>) -> Auto static fn from_node 形态
/// (a2r 无法表达 trait impl; 行为等价)
/// 
/// a2r 惯用法注记:
/// - `impl TryFrom<Node>` trait impl 不支持 -> `static fn from_node`
/// - HashMap<String, Vec<String>> 的 insert/get 已可用 (C3 闭环)
/// - 枚举 Default: `#[default]` 被丢弃但 derive(Default) 生效
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum TaskMode {
    #[default]
    Gsd = 0,
    Check = 1,
}

impl std::fmt::Display for TaskMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            TaskMode::Gsd => write!(f, "Gsd"),
            TaskMode::Check => write!(f, "Check"),
        }
    }
}
impl TaskMode {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Gsd" | "gsd" => TaskMode::Gsd,
            "Check" | "check" => TaskMode::Check,
            _ => TaskMode::Gsd
        }
    }
}

impl TaskMode {
    pub fn as_str(&self) -> String {
        match self {
            TaskMode::Gsd => return "gsd".to_string(),
            TaskMode::Check => return "check".to_string(),
        }
    }
    pub fn from_str(s: &str) -> Option<TaskMode> {
        match s {
            "gsd" => return Some(TaskMode::Gsd),
            "check" => return Some(TaskMode::Check),
            _ => return None,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum PhaseMode {
    #[default]
    Serial = 0,
    Parallel = 1,
}

impl std::fmt::Display for PhaseMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            PhaseMode::Serial => write!(f, "Serial"),
            PhaseMode::Parallel => write!(f, "Parallel"),
        }
    }
}
impl PhaseMode {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Serial" | "serial" => PhaseMode::Serial,
            "Parallel" | "parallel" => PhaseMode::Parallel,
            _ => PhaseMode::Serial
        }
    }
}

impl PhaseMode {
    pub fn as_str(&self) -> String {
        match self {
            PhaseMode::Serial => return "serial".to_string(),
            PhaseMode::Parallel => return "parallel".to_string(),
        }
    }
    pub fn from_str(s: &str) -> Option<PhaseMode> {
        match s {
            "serial" => return Some(PhaseMode::Serial),
            "parallel" => return Some(PhaseMode::Parallel),
            _ => return None,
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TaskPlan {
    pub id: String,
    pub version: u32,
    pub title: Option<String>,
    pub description: Option<String>,
    pub default_mode: TaskMode,
    pub phases: Vec<Phase>,
}

impl TaskPlan {
    pub fn new(id: &str) -> TaskPlan {
        TaskPlan { id: id.to_string(), version: 1, title: None, description: None, default_mode: TaskMode::default(), phases: vec![] }
    }
    pub fn add_phase(&self, phase: Phase) -> TaskPlan {
        let mut result: TaskPlan = self.clone();
        result.phases.push(phase.clone());
        return result;
    }
    pub fn validate(&self) -> Result<bool, AtomError> {
        let mut phase_names: HashSet<String> = HashSet::new();
        for phase in self.phases.clone() {
            if phase_names.contains(&phase.name.clone()) {
                return Err(AtomError::ValidationError(format!("{}{}", format!("{}{}", "duplicate phase name '", phase.name), "'")));
            }
            let _: bool = phase_names.insert(phase.name.clone());
        }

        for phase in self.phases.clone() {
            let mut run_names: HashSet<String> = HashSet::new();
            for run in phase.runs.clone() {
                if run_names.contains(&run.name.clone()) {
                    return Err(AtomError::ValidationError(format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "duplicate run name '", run.name), "' in phase '"), phase.name), "'")));
                }
                let _: bool = run_names.insert(run.name.clone());
            }
            
            for dependency in phase.depends_on.clone() {
                if phase_names.contains(&dependency.clone()) == false {
                    return Err(AtomError::ValidationError(format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "phase '", phase.name), "' depends on unknown phase '"), dependency), "'")));
                }
            }
        }


        let cycle: bool = self.detect_cycle();
        if cycle {
            return Err(AtomError::ValidationError("dependency cycle detected between phases".to_string()));
        }


        for phase in self.phases.clone() {
            for run in phase.runs.clone() {
                for path in run.input_from.clone() {
                    let path_result: Result<bool, AtomError> = validate_handoff_path(&path);
                    match path_result {
                        Err(e) => return Err(e),
                        Ok(_) => {},
                    };
                }
            }
        }

        return Ok(true);
    }
    pub fn detect_cycle(&self) -> bool {
        let mut graph: HashMap<String, Vec<String>> = HashMap::new();
        for phase in self.phases.clone() {
            graph.insert(phase.name.clone(), phase.depends_on.clone());
        }
        let mut visited: HashSet<String> = HashSet::new();
        let mut stack: HashSet<String> = HashSet::new();
        for phase in self.phases.clone() {
            if visited.contains(&phase.name.clone()) == false {
                let has_cycle: bool = dfs(&phase.name, &graph, &mut visited, &mut stack);
                if has_cycle {
                    return true;
                }            }
        }
        return false;
    }
    pub fn from_node(node: Node) -> Result<TaskPlan, AtomError> {
        if node.name != "task_plan" {
            return Err(AtomError::ValidationError(format!("{}{}", format!("{}{}", "expected root node 'task_plan', found '", node.name), "'")));
        }

        let id: String = require_string_prop(node.clone(), "id");
        let mut version: u32 = 1;
        let version_prop: Option<Value> = prop(node.clone(), "version");
        match version_prop {
            Some(v) => {
                let vr: Result<u32, AtomError> = value_as_u32(v.clone());
                match vr {
                    Ok(n) => version = n,
                    Err(e) => return Err(e),
                };
            },
            None => {},
        };
        let mut title: Option<String> = None;
        let title_prop: Option<Value> = prop(node.clone(), "title");
        match title_prop {
            Some(v) => {
                let tr: Result<String, AtomError> = value_as_string(v.clone());
                match tr {
                    Ok(s) => title = Some(s),
                    Err(e) => return Err(e),
                };
            },
            None => {},
        };
        let mut description: Option<String> = None;
        let desc_prop: Option<Value> = prop(node.clone(), "description");
        match desc_prop {
            Some(v) => {
                let dr: Result<String, AtomError> = value_as_string(v.clone());
                match dr {
                    Ok(s) => description = Some(s),
                    Err(e) => return Err(e),
                };
            },
            None => {},
        };
        let mut default_mode: TaskMode = TaskMode::default();
        let dm_prop: Option<Value> = prop(node.clone(), "default_mode");
        match dm_prop {
            Some(v) => {
                let mr: Result<TaskMode, AtomError> = value_as_task_mode(v.clone());
                match mr {
                    Ok(m) => default_mode = m,
                    Err(e) => return Err(e),
                };
            },
            None => {},
        };

        let mut phases: Vec<Phase> = vec![];
        for (_key, kid) in node.kids_iter() {
            match kid {
                Kid::Node(child) => {
                    if child.name == "phase" {
                        let phase_result: Result<Phase, AtomError> = Phase::from_node(child.as_ref().clone());
                        match phase_result {
                            Ok(p) => phases.push(p.clone()),
                            Err(e) => return Err(e),
                        };
                    }
                },
                _ => {},
            };
        }

        let plan: TaskPlan = TaskPlan { id: id.to_string(), version: version, title: title, description: description, default_mode: default_mode, phases: phases };
        let valid: Result<bool, AtomError> = plan.validate();
        match valid {
            Err(e) => return Err(e),
            Ok(_) => {},
        };
        return Ok(plan);
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Phase {
    pub name: String,
    pub mode: PhaseMode,
    pub depends_on: Vec<String>,
    pub runs: Vec<RunRef>,
}

impl Phase {
    pub fn new(name: &str) -> Phase {
        Phase { name: name.to_string(), mode: PhaseMode::default(), depends_on: vec![], runs: vec![] }
    }
    pub fn with_mode(&self, mut mode: PhaseMode) -> Phase {
        let mut result: Phase = self.clone();
        result.mode = mode;
        return result;
    }
    pub fn depends_on(&self, names: Vec<String>) -> Phase {
        let mut result: Phase = self.clone();
        result.depends_on = names;
        return result;
    }
    pub fn add_run(&self, run: RunRef) -> Phase {
        let mut result: Phase = self.clone();
        result.runs.push(run.clone());
        return result;
    }
    pub fn from_node(node: Node) -> Result<Phase, AtomError> {
        if node.name != "phase" {
            return Err(AtomError::ValidationError(format!("{}{}", format!("{}{}", "expected node 'phase', found '", node.name), "'")));
        }

        let name: String = require_string_prop(node.clone(), "name");
        let mut mode: PhaseMode = PhaseMode::default();
        let mode_prop: Option<Value> = prop(node.clone(), "mode");
        match mode_prop {
            Some(v) => {
                let mr: Result<PhaseMode, AtomError> = value_as_phase_mode(v.clone());
                match mr {
                    Ok(m) => mode = m,
                    Err(e) => return Err(e),
                };
            },
            None => {},
        };
        let mut depends_on: Vec<String> = vec![];
        let deps_prop: Option<Value> = prop(node.clone(), "depends_on");
        match deps_prop {
            Some(v) => {
                let dr: Result<Vec<String>, AtomError> = value_as_string_list(v.clone());
                match dr {
                    Ok(l) => depends_on = l,
                    Err(e) => return Err(e),
                };
            },
            None => {},
        };

        let mut runs: Vec<RunRef> = vec![];
        for (_key, kid) in node.kids_iter() {
            match kid {
                Kid::Node(child) => {
                    if child.name == "run" {
                        let run_result: Result<RunRef, AtomError> = RunRef::from_node(child.as_ref().clone());
                        match run_result {
                            Ok(r) => runs.push(r.clone()),
                            Err(e) => return Err(e),
                        };
                    }
                },
                _ => {},
            };
        }

        return Ok(Phase { name: name.to_string(), mode: mode, depends_on: depends_on, runs: runs });
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RunRef {
    pub name: String,
    pub flow_id: String,
    pub input: Option<String>,
    pub input_from: Vec<String>,
    pub context: Option<String>,
    pub mode_override: Option<TaskMode>,
}

impl RunRef {
    pub fn new(name: &str, flow_id: &str) -> RunRef {
        RunRef { name: name.to_string(), flow_id: flow_id.to_string(), input: None, input_from: vec![], context: None, mode_override: None }
    }
    pub fn with_input(&self, mut input: &str) -> RunRef {
        let mut result: RunRef = self.clone();
        result.input = Some(input.to_string());
        return result;
    }
    pub fn with_input_from(&self, paths: Vec<String>) -> RunRef {
        let mut result: RunRef = self.clone();
        result.input_from = paths;
        return result;
    }
    pub fn with_context(&self, mut context: &str) -> RunRef {
        let mut result: RunRef = self.clone();
        result.context = Some(context.to_string());
        return result;
    }
    pub fn with_mode_override(&self, mode: TaskMode) -> RunRef {
        let mut result: RunRef = self.clone();
        result.mode_override = Some(mode);
        return result;
    }
    pub fn from_node(node: Node) -> Result<RunRef, AtomError> {
        if node.name != "run" {
            return Err(AtomError::ValidationError(format!("{}{}", format!("{}{}", "expected node 'run', found '", node.name), "'")));
        }

        let name: String = require_string_prop(node.clone(), "name");
        let flow_id: String = require_string_prop(node.clone(), "flow_id");
        let mut input: Option<String> = None;
        let input_prop: Option<Value> = prop(node.clone(), "input");
        match input_prop {
            Some(v) => {
                let ir: Result<String, AtomError> = value_as_string(v.clone());
                match ir {
                    Ok(s) => input = Some(s),
                    Err(e) => return Err(e),
                };
            },
            None => {},
        };
        let mut input_from: Vec<String> = vec![];
        let if_prop: Option<Value> = prop(node.clone(), "input_from");
        match if_prop {
            Some(v) => {
                let ir: Result<Vec<String>, AtomError> = value_as_string_list(v.clone());
                match ir {
                    Ok(l) => input_from = l,
                    Err(e) => return Err(e),
                };
            },
            None => {},
        };
        let mut context: Option<String> = None;
        let ctx_prop: Option<Value> = prop(node.clone(), "context");
        match ctx_prop {
            Some(v) => {
                let cr: Result<String, AtomError> = value_as_string(v.clone());
                match cr {
                    Ok(s) => context = Some(s),
                    Err(e) => return Err(e),
                };
            },
            None => {},
        };
        let mut mode_override: Option<TaskMode> = None;
        let mo_prop: Option<Value> = prop(node.clone(), "mode_override");
        match mo_prop {
            Some(v) => {
                let mr: Result<TaskMode, AtomError> = value_as_task_mode(v.clone());
                match mr {
                    Ok(m) => mode_override = Some(m),
                    Err(e) => return Err(e),
                };
            },
            None => {},
        };

        return Ok(RunRef { name: name.to_string(), flow_id: flow_id.to_string(), input: input, input_from: input_from, context: context, mode_override: mode_override });
    }
}

/// Create a new empty TaskPlan.
/// Add a phase to the plan.
/// Validate the plan structure.
/// Convert a parsed Atom node into a `TaskPlan` (hw: `TryFrom<Node>`).
fn dfs(node: &str, graph: &HashMap<String, Vec<String>>, mut visited: &mut HashSet<String>, mut stack: &mut HashSet<String>) -> bool {
    if stack.contains(node) {
        return true;
    }
    if visited.contains(node) {
        return false;
    }
    let _: bool = visited.insert(node.to_string());
    let _: bool = stack.insert(node.to_string());



    let deps_opt: Option<&Vec<String>> = graph.get(node);
    match deps_opt {
        Some(deps) => {
            for dependency in deps.clone() {
                let has_cycle: bool = dfs(dependency.as_str(), &graph, &mut visited, &mut stack);
                if has_cycle {
                    return true;
                }
            }
        },
        None => {},
    };

    stack.remove(node);
    return false;
}

fn prop(node: Node, key: &str) -> Option<Value> {
    let v: Value = node.get_prop_of(key);
    match v {
        Value::Nil => return None,
        _ => return Some(v),
    }
}

fn require_string_prop(node: Node, key: &str) -> String {
    let p: Option<Value> = prop(node.clone(), key);
    match p {
        Some(v) => {
            let r: Result<String, AtomError> = value_as_string(v.clone());
            match r {
                Ok(s) => return s,
                Err(_) => return "".to_string(),
            };
        },
        None => return "".to_string(),
    }
}

fn value_as_string(value: Value) -> Result<String, AtomError> {
    match value {
        Value::Str(s) => return Ok(s.to_string()),
        Value::Node(n) => return Ok(n.id().to_string()),
        _ => return Err(AtomError::InvalidType { expected: "String".to_string(), found: format!("{:?}", value) }),
    }
}

fn value_as_u32(value: Value) -> Result<u32, AtomError> {
    match value {
        Value::Int(i) => return Ok((i as u32)),
        Value::Uint(u) => return Ok(u),
        _ => return Err(AtomError::InvalidType { expected: "Integer".to_string(), found: format!("{:?}", value) }),
    }
}

fn value_as_string_list(value: Value) -> Result<Vec<String>, AtomError> {
    match value {
        Value::Array(arr) => {
            let mut out: Vec<String> = vec![];
            for item in arr.values.clone() {
                let r: Result<String, AtomError> = value_as_string(item.clone());
                match r {
                    Ok(s) => out.push(s.clone()),
                    Err(e) => return Err(e),
                };
            }
            return Ok(out);
        },
        Value::Str(s) => {
            let out: Vec<String> = vec![s.to_string()];
            return Ok(out);
        },
        _ => return Err(AtomError::InvalidType { expected: "String or Array of Strings".to_string(), found: format!("{:?}", value) }),
    }
}

fn value_as_task_mode(value: Value) -> Result<TaskMode, AtomError> {
    let s: Result<String, AtomError> = value_as_string(value.clone());
    match s {
        Ok(str_val) => {
            let m: Option<TaskMode> = TaskMode::from_str(&str_val);
            match m {
                Some(tm) => return Ok(tm),
                None => return Err(AtomError::ValidationError(format!("{}{}", format!("{}{}", "invalid task mode '", str_val), "', expected 'gsd' or 'check'"))),
            };
        },
        Err(e) => return Err(e),
    }
}

fn value_as_phase_mode(value: Value) -> Result<PhaseMode, AtomError> {
    let s: Result<String, AtomError> = value_as_string(value.clone());
    match s {
        Ok(str_val) => {
            let m: Option<PhaseMode> = PhaseMode::from_str(&str_val);
            match m {
                Some(pm) => return Ok(pm),
                None => return Err(AtomError::ValidationError(format!("{}{}", format!("{}{}", "invalid phase mode '", str_val), "', expected 'serial' or 'parallel'"))),
            };
        },
        Err(e) => return Err(e),
    }
}

/// Validate a handoff path like `phase.run.handoff.field`.
fn validate_handoff_path(path: &str) -> Result<bool, AtomError> {


    let parts = path.split(".").collect::<Vec<_>>();
    if (parts.len() as i32) < 3 {
        return Err(AtomError::ValidationError(format!("{}{}", format!("{}{}", "input_from path '", path), "' must have at least 3 segments (phase.run.field)")));
    }
    if parts[2].clone() != "handoff" && parts[2].clone() != "output" {
        return Err(AtomError::ValidationError(format!("{}{}", format!("{}{}", "input_from path '", path), "' must use 'handoff' or 'output' as third segment")));
    }
    return Ok(true);
}