use super::extern_impl::*;
// Auto-generated by a2r transpiler

use std::sync::Arc;
use crate::server::AppState;
/// tool_context.at — ToolContext struct (tool_context.rs).
/// Orchestr tools 持有的执行上下文。
#[derive(Clone)]
pub struct ToolContext {
    pub state: Arc<AppState>,
    pub workspace_id: String,
    pub parent_conversation_id: String,
}
