use crate::auto_generated::extern_impl::*;
// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use serde_json::Value;
use std::fs;
#[async_trait::async_trait]
trait Tool {
    fn name(&self) -> String;
    fn description(&self) -> String;
    fn parameters(&self) -> Value;
    async fn execute(&self, args: Value) -> Result<String, ToolError>;
}


/// tools.at — 9 个 Tool impl (tools.rs). P5b 后 async trait impl 可用。
/// parameters json!() → backtick 原始字符串 + parse_json。
#[derive(Clone, Debug, PartialEq)]
struct ReadFile {}

#[async_trait::async_trait]
impl Tool for ReadFile {
    fn name(&self) -> String {
        return "read_file".to_string();
    }
    fn description(&self) -> String {
        return "Read file contents".to_string();
    }
    fn parameters(&self) -> Value {
        return parse_json(read_file_schema);
    }
    async fn execute(&self, args: Value) -> Result<String, ToolError> {
        let path = value_get_str(args, "path");
        let resolved = resolve_within_project(path);
        let content = std::fs::read_to_string(resolved.as_str()).unwrap();
        return Ok(content);
    }
}

#[derive(Clone, Debug, PartialEq)]
struct WriteFile {}

#[async_trait::async_trait]
impl Tool for WriteFile {
    fn name(&self) -> String {
        return "write_file".to_string();
    }
    fn description(&self) -> String {
        return "Write file".to_string();
    }
    fn parameters(&self) -> Value {
        return parse_json(write_file_schema);
    }
    async fn execute(&self, args: Value) -> Result<String, ToolError> {
        let path = value_get_str(args, "path");
        let content = value_get_str(args, "content");
        write_file_do(path, content);
        return Ok("wrote file");
    }
}

#[derive(Clone, Debug, PartialEq)]
struct RunCommand {}

#[async_trait::async_trait]
impl Tool for RunCommand {
    fn name(&self) -> String {
        return "run_command".to_string();
    }
    fn description(&self) -> String {
        return "Run shell command".to_string();
    }
    fn parameters(&self) -> Value {
        return parse_json(run_command_schema);
    }
    async fn execute(&self, args: Value) -> Result<String, ToolError> {
        let cmd = value_get_str(args, "cmd");
        let force = value_get_bool(args, "force");
        if force == false {
            let needs = command_needs_approval(cmd);
            if needs {
                return Ok("PAUSED: needs approval");
            }        }
        let output = run_shell_command(cmd);
        return Ok(output);
    }
}

#[derive(Clone, Debug, PartialEq)]
struct EditFile {}

#[async_trait::async_trait]
impl Tool for EditFile {
    fn name(&self) -> String {
        return "edit_file".to_string();
    }
    fn description(&self) -> String {
        return "Replace unique string in file".to_string();
    }
    fn parameters(&self) -> Value {
        return parse_json(edit_file_schema);
    }
    async fn execute(&self, args: Value) -> Result<String, ToolError> {
        let path = value_get_str(args, "path");
        let old_str = value_get_str(args, "old_string");
        let new_str = value_get_str(args, "new_string");
        let result = edit_file_do(path, old_str, new_str);
        return Ok(result);
    }
}

#[derive(Clone, Debug, PartialEq)]
struct BatchReplace {}

#[async_trait::async_trait]
impl Tool for BatchReplace {
    fn name(&self) -> String {
        return "batch_replace".to_string();
    }
    fn description(&self) -> String {
        return "Multiple replacements".to_string();
    }
    fn parameters(&self) -> Value {
        return parse_json(batch_replace_schema);
    }
    async fn execute(&self, args: Value) -> Result<String, ToolError> {
        let path = value_get_str(args, "path");
        let replacements = value_get_array(args, "replacements");
        let result = batch_replace_do(path, replacements);
        return Ok(result);
    }
}

#[derive(Clone, Debug, PartialEq)]
struct Search {}

#[async_trait::async_trait]
impl Tool for Search {
    fn name(&self) -> String {
        return "search".to_string();
    }
    fn description(&self) -> String {
        return "Search file tree".to_string();
    }
    fn parameters(&self) -> Value {
        return parse_json(search_schema);
    }
    async fn execute(&self, args: Value) -> Result<String, ToolError> {
        let pattern = value_get_str(args, "pattern");
        let result = search_files(pattern);
        return Ok(result);
    }
}

#[derive(Clone, Debug, PartialEq)]
struct ListDir {}

#[async_trait::async_trait]
impl Tool for ListDir {
    fn name(&self) -> String {
        return "list_dir".to_string();
    }
    fn description(&self) -> String {
        return "List directory".to_string();
    }
    fn parameters(&self) -> Value {
        return parse_json(list_dir_schema);
    }
    async fn execute(&self, args: Value) -> Result<String, ToolError> {
        let path = value_get_str(args, "path");
        let result = list_directory(path);
        return Ok(result);
    }
}

#[derive(Clone, Debug, PartialEq)]
struct ListSymbols {}

#[async_trait::async_trait]
impl Tool for ListSymbols {
    fn name(&self) -> String {
        return "list_symbols".to_string();
    }
    fn description(&self) -> String {
        return "List code symbols".to_string();
    }
    fn parameters(&self) -> Value {
        return parse_json(list_symbols_schema);
    }
    async fn execute(&self, args: Value) -> Result<String, ToolError> {
        let path = value_get_str(args, "path");
        let result = list_symbols_in(path);
        return Ok(result);
    }
}

#[derive(Clone, Debug, PartialEq)]
struct Glob {}

#[async_trait::async_trait]
impl Tool for Glob {
    fn name(&self) -> String {
        return "glob".to_string();
    }
    fn description(&self) -> String {
        return "Find files by glob".to_string();
    }
    fn parameters(&self) -> Value {
        return parse_json(glob_schema);
    }
    async fn execute(&self, args: Value) -> Result<String, ToolError> {
        let pattern = value_get_str(args, "pattern");
        let result = glob_files(pattern);
        return Ok(result);
    }
}

fn main() {
    let read_file_schema: String = format!("{{\"type\":\"object\",\"properties\":{{\"path\":{{\"type\":\"string\"}},\"required\":[\"path\"]}}");;
    let write_file_schema: String = format!("{{\"type\":\"object\",\"properties\":{{\"path\":{{\"type\":\"string\"}},\"content\":{{\"type\":\"string\"}},\"required\":[\"path\",\"content\"]}}");;
    let run_command_schema: String = format!("{{\"type\":\"object\",\"properties\":{{\"cmd\":{{\"type\":\"string\"}},\"force\":{{\"type\":\"boolean\"}},\"required\":[\"cmd\"]}}");;
    let edit_file_schema: String = format!("{{\"type\":\"object\",\"properties\":{{\"path\":{{\"type\":\"string\"}},\"old_string\":{{\"type\":\"string\"}},\"new_string\":{{\"type\":\"string\"}},\"required\":[\"path\",\"old_string\",\"new_string\"]}}");;
    let batch_replace_schema: String = format!("{{\"type\":\"object\",\"properties\":{{\"path\":{{\"type\":\"string\"}},\"replacements\":{{\"type\":\"array\"}},\"required\":[\"path\",\"replacements\"]}}");;
    let search_schema: String = format!("{{\"type\":\"object\",\"properties\":{{\"pattern\":{{\"type\":\"string\"}},\"required\":[\"pattern\"]}}");;
    let list_dir_schema: String = format!("{{\"type\":\"object\",\"properties\":{{\"path\":{{\"type\":\"string\"}},\"required\":[\"path\"]}}");;
    let list_symbols_schema: String = format!("{{\"type\":\"object\",\"properties\":{{\"path\":{{\"type\":\"string\"}},\"required\":[\"path\"]}}");;
    let glob_schema: String = format!("{{\"type\":\"object\",\"properties\":{{\"pattern\":{{\"type\":\"string\"}},\"required\":[\"pattern\"]}}");;
}
