use super::extern_impl::*;
// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
/// tool_safety.at — ported from backend/crates/musk/src/tool_safety.rs.
/// 
/// Tool safety layer — path confinement + run_command classification.
/// Strategy (plan 014 mixed):
/// - run_command classification (CommandTier + classify_command) -> Auto
/// (pure string logic: contains/starts_with/trim/to_lowercase)
/// - path confinement (PROJECT_ROOT/ROOT_OVERRIDE/CURRENT_ROOT +
/// resolve_within_project) -> hand-written Rust (OnceLock + thread_local!
/// + RefCell + Path methods are a2r blind spots)
/// The safety tier of a shell command.
/// NeedsApproval carries a human-readable reason (e.g. "not on whitelist"
/// or "matches dangerous pattern").
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CommandTier {
    Allowed,
    NeedsApproval { reason: String },
}


/// Commands that are always safe (matched by prefix). Modeled as a function
/// returning a List (Auto has no &'static [&str]); mirrors ALLOWED_PREFIXES.
fn allowed_prefixes() -> Vec<String> {
    return vec!["cargo".to_string(), "npm".to_string(), "npx".to_string(), "yarn".to_string(), "pnpm".to_string(), "node".to_string(), "python".to_string(), "python3".to_string(), "pip".to_string(), "pytest".to_string(), "rustc".to_string(), "rustup".to_string(), "tsc".to_string(), "eslint".to_string(), "prettier".to_string(), "git status".to_string(), "git diff".to_string(), "git log".to_string(), "git show".to_string(), "git branch".to_string(), "git add".to_string(), "git stash".to_string(), "git fetch".to_string(), "git remote".to_string(), "echo".to_string(), "type".to_string(), "cat".to_string(), "ls".to_string(), "dir".to_string(), "pwd".to_string(), "cd".to_string(), "mkdir".to_string(), "touch".to_string(), "head".to_string(), "tail".to_string(), "wc".to_string(), "sort".to_string(), "uniq".to_string(), "grep".to_string(), "find".to_string(), "which".to_string(), "where".to_string(), "test".to_string(), "[".to_string(), "true".to_string(), "false".to_string(), "go ".to_string(), "go test".to_string(), "go build".to_string(), "go vet".to_string(), "go run".to_string(), "make".to_string(), "cmake".to_string()];
}

/// Patterns that are explicitly dangerous (checked first, override whitelist).
fn danger_patterns() -> Vec<String> {
    return vec!["rm -rf".to_string(), "rm -fr".to_string(), "rmdir /s".to_string(), "del /s".to_string(), "del /f".to_string(), "format ".to_string(), "mkfs".to_string(), "shutdown".to_string(), "reboot".to_string(), "halt".to_string(), "curl ".to_string(), "wget ".to_string(), ">".to_string(), ">>".to_string(), "| sh".to_string(), "| bash".to_string(), "|sh".to_string(), "|bash".to_string(), "chmod 777".to_string(), "chown".to_string(), "kill -9".to_string(), "taskkill".to_string(), ":(){".to_string(), "dd if".to_string(), "mv /".to_string(), "cp /".to_string()];
}

pub fn classify_command(cmd: &str) -> CommandTier {
    let trimmed: String = cmd.trim().to_string();

    let dangers: Vec<String> = danger_patterns();
    for pat in &dangers {
        if trimmed.as_str().contains(pat.as_str()) {
            return CommandTier::NeedsApproval { reason: format!("{}{}", format!("{}{}", "dangerous pattern detected: ", pat), " — needs approval") };
        }
    }

    let lower: String = trimmed.to_lowercase();
    let prefixes: Vec<String> = allowed_prefixes();
    for prefix in &prefixes {
        if lower == prefix.clone() {
            return CommandTier::Allowed;
        }
        let with_space: String = format!("{}{}", prefix, " ");
        if lower.starts_with(&with_space) {
            return CommandTier::Allowed;
        }
    }

    return CommandTier::NeedsApproval { reason: format!("{}{}", format!("{}{}", "command ", trimmed), " is not on the whitelist and needs approval") };
}