use super::extern_impl::*;
// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Mutex;
use std::fs;
use serde::{Serialize, Deserialize};
use serde_json::{to_string_pretty, from_str};
use serde_json::Value;
use std::time::{SystemTime, Duration};
/// wiki.at — Wiki Knowledge Layer 数据层 + 纯 CRUD (Plan 018 Phase 3 试点)。
/// 
/// Ported from backend/crates/musk/src/wiki.rs, flattened to the portable
/// subset per the Phase 2 pattern:
/// - data model (WikiPage/WikiSource/WikiPageMeta/TreeNode/WikiManifest) -> Auto
/// - WikiStore 纯 Mutex CRUD + fs + serde_json -> Auto
/// - axum 路由/handler (wiki_routes/wiki_tree/.../Multipart) + API DTO +
/// guess_mime -> 手写边界 (axum/async/&'static str 是 a2r 盲区)
/// 
/// a2r 惯用法注记(本轮探测确认):
/// - `or`/`and` 关键字不支持 -> 布尔组合用嵌套 if
/// - `sort_by(fn-ref)` 不支持 -> 手动插入排序(comes_first)
/// - Result 链式 `.ok()` 不支持 -> `is` 匹配逐层展开
/// - Mutex guard 迭代: `for pair in guard` -> 发射 `&guard`
/// - TreeNode size/modified: file 节点省略 metadata(见 build_tree 内注记)
/// WikiSource: 与手写版完全对齐 —— 无判别值 + snake_case wire 格式。
/// 手写版用手动 `impl Default` 返回 Custom; a2r 丢弃 `#[default]` 且
/// enum 上 derive(Default) 必须带 `#[default]`(E0665), 所以不 derive
/// Default —— load() 里显式 `WikiSource.Custom` 兜底, 行为一致。
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WikiSource {
    Manual = 0,
    Guide = 1,
    ApiRef = 2,
    Custom = 3,
}

impl std::fmt::Display for WikiSource {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            WikiSource::Manual => write!(f, "Manual"),
            WikiSource::Guide => write!(f, "Guide"),
            WikiSource::ApiRef => write!(f, "ApiRef"),
            WikiSource::Custom => write!(f, "Custom"),
        }
    }
}
impl WikiSource {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Manual" | "manual" => WikiSource::Manual,
            "Guide" | "guide" => WikiSource::Guide,
            "ApiRef" | "apiref" => WikiSource::ApiRef,
            "Custom" | "custom" => WikiSource::Custom,
            _ => WikiSource::Manual
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct WikiPage {
    pub slug: String,
    pub title: String,
    pub content: String,
    pub source_type: WikiSource,
    pub tags: Vec<String>,
    pub version: u32,
    pub created_at: u64,
    pub updated_at: u64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct WikiPageMeta {
    pub slug: String,
    pub title: String,
    pub source_type: WikiSource,
    pub tags: Vec<String>,
    pub version: u32,
    pub updated_at: u64,
}

/// Internal manifest shape (private in the hand-written version).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct WikiManifest {
    pub pages: Vec<WikiPageMeta>,
}

/// Tree node — recursive (folders carry children).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TreeNode {
    pub name: String,
    pub path: String,
    #[serde(rename = "type")]
    pub node_type: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<TreeNode>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub modified: Option<u64>,
}

/// Seconds since the UNIX epoch (used for page timestamps).
fn now() -> u64 {
    let elapsed = SystemTime::now().duration_since(SystemTime::UNIX_EPOCH).unwrap_or_default();
    return elapsed.as_secs();
}

/// 单项目 wiki 存储: wiki_dir 放 .md + _manifest.json; raw_dir 放上传资源。
/// pages 是懒加载内存缓存; 磁盘是源, 每次变更落盘。
#[derive(Debug)]
pub struct WikiStore {
    pub wiki_dir: PathBuf,
    pub raw_dir: PathBuf,
    pub pages: Mutex<HashMap<String, WikiPage>>,
}

impl WikiStore {
    pub fn new(wiki_dir: PathBuf, raw_dir: PathBuf) -> WikiStore {
        let m1 = fs::create_dir_all(wiki_dir.clone());
        match m1 {
            Ok(ok) => {},
            Err(e) => {},
        };
        let m2 = fs::create_dir_all(raw_dir.clone());
        match m2 {
            Ok(ok) => {},
            Err(e) => {},
        };
        let store: WikiStore = WikiStore { wiki_dir: wiki_dir, raw_dir: raw_dir, pages: Mutex::new(HashMap::new()) };
        return store;
    }
    pub fn load(&self) {
        let mut guard = self.pages.lock().unwrap();
        guard.clear();



        let mut metas: Vec<WikiPageMeta> = vec![];
        let r1 = std::fs::read_to_string(self.wiki_dir.join("_manifest.json"));
        match r1 {
            Ok(c) => {
                let pr = parse_manifest(c.as_str());
                match pr {
                    Ok(m) => {
                        for p in &m.pages {
                            metas.push(p.clone());
                        }
                    },
                    Err(e) => {},
                };
            },
            Err(e) => {
                let r2 = std::fs::read_to_string(self.wiki_dir.join("manifest.json"));
                match r2 {
                    Ok(c2) => {
                        let pr2 = parse_manifest(c2.as_str());
                        match pr2 {
                            Ok(m2) => {
                                for p in &m2.pages {
                                    metas.push(p.clone());
                                }
                            },
                            Err(e2) => {},
                        };
                    },
                    Err(e2) => {},
                };
            },
        };

        let slugs_res = walk_md_files(self.wiki_dir.clone(), "");
        match slugs_res {
            Ok(slugs) => {
                for slug in &slugs {
                    let page_path: PathBuf = self.wiki_dir.join(format!("{}{}", slug.clone(), ".md"));
                    let read_res = std::fs::read_to_string(page_path);
                    match read_res {
                        Ok(content) => {
                            let meta = find_meta(metas.clone(), slug.as_str());
                            let mut source_type: WikiSource = WikiSource::Custom;
                            let mut tags: Vec<String> = vec![];
                            let mut version: u32 = 1 as u32;
                            let mut updated_at: u64 = 0;
                            let mut title: String = slug.clone();
                            match meta {
                                Some(m) => {
                                    title = m.title.clone();
                                    source_type = m.source_type;
                                    tags = m.tags.clone();
                                    version = m.version;
                                    updated_at = m.updated_at;
                                },
                                None => {},
                            };
                            let page: WikiPage = WikiPage { slug: slug.clone().to_string(), title: title.to_string(), content: content.to_string(), source_type: source_type, tags: tags, version: version, created_at: updated_at, updated_at: updated_at };
                            guard.insert(slug.to_string(), page.clone());
                        },
                        Err(e) => {},
                    };
                }
            },
            Err(e) => {},
        };
    }
    pub fn list_pages(&self) -> Vec<WikiPageMeta> {
        let mut result: Vec<WikiPageMeta> = vec![];
        let mut guard = self.pages.lock().unwrap();
        for pair in guard.iter() {
            let p = pair.1.clone();
            result.push(WikiPageMeta { slug: p.slug.clone().to_string(), title: p.title.clone().to_string(), source_type: p.source_type, tags: p.tags.clone(), version: p.version, updated_at: p.updated_at });
        }
        return result;
    }
    pub fn get_page(&self, slug: &str) -> Option<WikiPage> {
        let mut guard = self.pages.lock().unwrap();
        match guard.get(slug) {
            Some(p) => return Some(p.clone()),
            None => return None,
        }
    }
    pub fn search(&self, query: &str) -> Vec<WikiPage> {
        let q: String = query.to_lowercase();
        let mut result: Vec<WikiPage> = vec![];
        let mut guard = self.pages.lock().unwrap();
        for pair in guard.iter() {
            let p = pair.1.clone();
            let in_content = p.content.to_lowercase().contains(&q.clone());
            let in_title = p.title.to_lowercase().contains(&q.clone());
            if in_content {
                result.push(p.clone());
            } else if in_title {
                result.push(p.clone());
            }
        }
        return result;
    }
}

/// 从磁盘加载(或刷新)页面缓存: 读 manifest 元数据 + 每个 .md 内容。
/// 幂等 — 任何读操作前调用都安全。
/// 列出所有页面元数据。
/// 取单个页面(克隆)。
/// 全文搜索(content/title 含 query, 不区分大小写)。
/// 解析 manifest 文本为 WikiManifest。
fn parse_manifest(content: &str) -> Result<WikiManifest, String> {
    let pr = from_str(content);
    match pr {
        Ok(m) => return Ok(m),
        Err(e) => return Err(e.to_string()),
    }
}

/// 在 manifest 元数据列表里线性查找 slug(a2r HashMap.get() 借用不可靠)。
fn find_meta(metas: Vec<WikiPageMeta>, slug: &str) -> Option<WikiPageMeta> {
    for m in &metas {
        if m.slug == slug {
            return Some(m.clone());
        }
    }
    return None;
}

pub fn walk_md_files(root: PathBuf, prefix: &str) -> Result<Vec<String>, String> {
    let mut result: Vec<String> = vec![];
    let dir_res = fs::read_dir(root);
    match dir_res {
        Err(e) => return Err(e.to_string()),
        Ok(dir) => {
            for entry in dir.flatten() {
                let name: String = entry.file_name().to_string_lossy().to_string();
                if name.starts_with(".") {
                    continue;
                }
                if name == "_manifest.json" {
                    continue;
                }
                if name == "manifest.json" {
                    continue;
                }
                let mut path: String = name.clone();
                if (prefix.len() as i32) > 0 {
                    path = format!("{}{}", format!("{}{}", prefix, "/"), name)
                }
                let is_dir = entry.path().is_dir();
                if is_dir {
                    let sub = walk_md_files(entry.path(), path.as_str());
                    match sub {
                        Ok(slugs) => {
                            for s in &slugs {
                                result.push(s.clone());
                            }
                        },
                        Err(e) => return Err(e),
                    };
                } else if name.ends_with(".md") {
                    let slug: String = path.trim_end_matches(".md").to_string();
                    result.push(slug);
                }
            }
        },
    };
    return Ok(result);
}

/// 递归收集 .md 文件(slug = 相对路径去 .md 扩展名)。
/// 文件夹在前 + 字母序 —— 插入排序(a2r 无 sort_by)。
fn comes_first(mut a: TreeNode, mut b: TreeNode) -> bool {
    if a.node_type == "folder" {
        if b.node_type != "folder" {
            return true;
        }        if a.name < b.name {
            return true;
        }        return false;
    }
    if b.node_type == "folder" {
        return false;
    }
    if a.name < b.name {
        return true;
    }
    return false;
}

fn insert_sorted(list: Vec<TreeNode>, item: TreeNode) -> Vec<TreeNode> {
    let mut result: Vec<TreeNode> = vec![];
    let mut inserted: bool = false;
    for e in &list {
        if inserted == false {
            if comes_first(item.clone(), e.clone()) {
                result.push(item.clone());
                inserted = true
            }        }
        result.push(e.clone());
    }
    if inserted == false {
        result.push(item.clone());
    }
    return result;
}

pub fn build_tree(root: PathBuf, prefix: &str) -> Vec<TreeNode> {
    let mut entries: Vec<TreeNode> = vec![];
    let dir_res = fs::read_dir(root);
    match dir_res {
        Err(e) => return entries,
        Ok(dir) => {
            for entry in dir.flatten() {
                let name: String = entry.file_name().to_string_lossy().to_string();
                if name.starts_with(".") {
                    continue;
                }
                if name == "_manifest.json" {
                    continue;
                }
                if name == "manifest.json" {
                    continue;
                }
                let mut path: String = name.clone();
                if (prefix.len() as i32) > 0 {
                    path = format!("{}{}", format!("{}{}", prefix, "/"), name)
                }
                let entry_path = entry.path();
                let is_dir = entry_path.is_dir();
                if is_dir {
                    let children = build_tree(entry_path.clone(), path.as_str());
                    let node: TreeNode = TreeNode { name: name.to_string(), path: path.to_string(), node_type: "folder".to_string(), children: Some(children), size: None, modified: None };
                    entries = insert_sorted(entries, node.clone())
                } else {
                    






                    let node: TreeNode = TreeNode { name: name.to_string(), path: path.to_string(), node_type: "file".to_string(), children: None, size: None, modified: None };
                    entries = insert_sorted(entries, node.clone())
                }

            }
        },
    };
    return entries;
}

pub fn strip_md_extensions(nodes: Vec<TreeNode>) -> Vec<TreeNode> {
    let mut result: Vec<TreeNode> = vec![];
    for node in &nodes {
        let mut name: String = node.name.clone();
        let mut path: String = node.path.clone();
        if node.node_type == "file" {
            if name.ends_with(".md") {
                name = name.trim_end_matches(".md").to_string();
                path = path.trim_end_matches(".md").to_string()
            }        }
        let mut children: Option<Vec<TreeNode>> = node.children.clone();
        match children {
            Some(c) => {
                let stripped = strip_md_extensions(c);
                children = Some(stripped);
            },
            None => {},
        };
        result.push(TreeNode { name: name.to_string(), path: path.to_string(), node_type: node.node_type.clone().to_string(), children: children, size: node.size, modified: node.modified });
    }
    return result;
}