//! Handoff Document — the token-efficiency mechanism.
//!
//! When an agent finishes its step, its work is compressed into a structured
//! `HandoffDocument` — NOT raw chat history — which the next agent consumes.
//! This keeps context bounded as the pipeline grows.
//!
//! Ported verbatim from auto-forge `backend/src/relay/handoff.rs` (the
//! structure is stable and central to the relay contract).

use serde::{Deserialize, Serialize};

/// A structured handoff between agents.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HandoffDocument {
    pub from: String,
    pub to: String,
    pub run_id: String,
    pub checkpoint_id: u64,
    pub summary: String,
    pub decisions: Vec<Decision>,
    pub open_questions: Vec<Question>,
    pub spec_updates: Vec<SpecUpdate>,
    pub work_product: Vec<WorkProduct>,
    pub context_for_next: ContextPointers,
    pub token_usage: TokenUsage,
    /// Optional: report generated by the documenter agent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generated_report: Option<ReportReference>,
    /// Set by the architect if architecture changes were introduced.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arch_change_flag: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arch_change_description: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Decision {
    pub id: String,
    pub title: String,
    pub status: String, // "made" | "deferred" | "rejected"
    pub rationale: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Question {
    pub id: String,
    pub text: String,
    pub status: String, // "open" | "answered" | "blocked"
    pub assigned_to: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpecUpdate {
    pub section_id: String,
    pub item_id: Option<String>,
    pub change_type: String, // "added" | "modified" | "removed"
    pub description: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkProduct {
    pub path: String,
    pub description: String,
    pub lines: Option<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ContextPointers {
    pub files_to_read: Vec<String>,
    pub specs_to_follow: Vec<String>,
    pub warnings: Vec<String>,
    /// Files the previous agent wrote/edited that should be tested.
    #[serde(default)]
    pub files_to_test: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct TokenUsage {
    pub step_input: u64,
    pub step_output: u64,
    pub cumulative: u64,
    pub budget_remaining: u64,
}

/// Optional report generation metadata (set by the documenter).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReportReference {
    pub report_id: String,
    pub report_title: String,
    pub wiki_slug: Option<String>,
}

impl HandoffDocument {
    pub fn new(from: &str, to: &str, run_id: &str, checkpoint_id: u64) -> Self {
        Self {
            from: from.into(),
            to: to.into(),
            run_id: run_id.into(),
            checkpoint_id,
            summary: String::new(),
            decisions: Vec::new(),
            open_questions: Vec::new(),
            spec_updates: Vec::new(),
            work_product: Vec::new(),
            context_for_next: ContextPointers::default(),
            token_usage: TokenUsage::default(),
            generated_report: None,
            arch_change_flag: None,
            arch_change_description: None,
        }
    }

    /// Render as markdown for the next agent's consumption.
    pub fn render(&self) -> String {
        let mut lines = Vec::new();
        lines.push(format!(
            "/// handoff:from={} to={} run={} checkpoint={}\n",
            self.from, self.to, self.run_id, self.checkpoint_id
        ));
        lines.push(format!("# Handoff: {} → {}", self.from, self.to));
        lines.push(String::new());

        lines.push("## Summary".into());
        lines.push(self.summary.clone());
        lines.push(String::new());

        if !self.decisions.is_empty() {
            lines.push("## Decisions Made".into());
            for d in &self.decisions {
                lines.push(format!("- **{}** ({}): {}", d.id, d.status, d.title));
                if !d.rationale.is_empty() {
                    lines.push(format!("  - Rationale: {}", d.rationale));
                }
            }
            lines.push(String::new());
        }

        if !self.open_questions.is_empty() {
            lines.push("## Open Questions".into());
            for q in &self.open_questions {
                lines.push(format!("- **{}** ({}): {}", q.id, q.status, q.text));
            }
            lines.push(String::new());
        }

        if !self.spec_updates.is_empty() {
            lines.push("## Spec Updates".into());
            for u in &self.spec_updates {
                lines.push(format!("- {} {}: {}", u.change_type, u.section_id, u.description));
            }
            lines.push(String::new());
        }

        if !self.work_product.is_empty() {
            lines.push("## Work Product".into());
            for wp in &self.work_product {
                let size = wp.lines.map(|l| format!(" ({} lines)", l)).unwrap_or_default();
                lines.push(format!("- `{}`{}{}", wp.path, size, wp.description));
            }
            lines.push(String::new());
        }

        let ctx = &self.context_for_next;
        if !ctx.files_to_read.is_empty()
            || !ctx.files_to_test.is_empty()
            || !ctx.specs_to_follow.is_empty()
            || !ctx.warnings.is_empty()
        {
            lines.push("## Context for Next Agent".into());
            if !ctx.files_to_read.is_empty() {
                lines.push("\n### Files to Read".into());
                for f in &ctx.files_to_read {
                    lines.push(format!("- {}", f));
                }
            }
            if !ctx.files_to_test.is_empty() {
                lines.push("\n### Files to Test".into());
                for f in &ctx.files_to_test {
                    lines.push(format!("- `{}`", f));
                }
            }
            if !ctx.specs_to_follow.is_empty() {
                lines.push("\n### Specs to Follow".into());
                for s in &ctx.specs_to_follow {
                    lines.push(format!("- {}", s));
                }
            }
            if !ctx.warnings.is_empty() {
                lines.push("\n### Warnings".into());
                for w in &ctx.warnings {
                    lines.push(format!("- ⚠️ {}", w));
                }
            }
            lines.push(String::new());
        }

        lines.push(format!(
            "## Token Spend\n- This step: {} tokens\n- Cumulative: {} tokens\n- Budget remaining: {} tokens\n",
            self.token_usage.step_input + self.token_usage.step_output,
            self.token_usage.cumulative,
            self.token_usage.budget_remaining
        ));

        lines.join("\n")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_contains_summary_and_sections() {
        let mut doc = HandoffDocument::new("advisor", "architect", "run-1", 1);
        doc.summary = "Define the module layout.".into();
        doc.decisions.push(Decision {
            id: "D1".into(),
            title: "Use SQLite".into(),
            status: "made".into(),
            rationale: "zero-config persistence".into(),
        });
        doc.work_product.push(WorkProduct {
            path: "src/db.rs".into(),
            description: " schema".into(),
            lines: Some(42),
        });
        let md = doc.render();
        assert!(md.contains("advisor → architect"));
        assert!(md.contains("Define the module layout."));
        assert!(md.contains("**D1** (made): Use SQLite"));
        assert!(md.contains("`src/db.rs` (42 lines)"));
    }
}
